### ISSUE TITLE
NULL pointer dereferencing in the touchscreen driver of clover-o-oss branch

### ISSUE THREAD

**Issue by scafroglia93** [MiCode/Xiaomi_Kernel_OpenSource#1005]
There is a suspected NULL pointer dereferencing issue (http://cwe.mitre.org/data/definitions/476.html) with the clover-o-oss, in drivers/input/touchscreen/gt9xx_zql6019/gt9xx.c, line 1593

https://github.com/MiCode/Xiaomi_Kernel_OpenSource/blob/942325021f5300719dd52cbb875120fa0ddc061a/drivers/input/touchscreen/gt9xx_zql6019/gt9xx.c#L1593

Same like previous issue found inside daisy branch oreo/pie
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/issues/972

**Comment by leoaccount** [comment]
Yes, in fact many branches share similar code of gt9xx.c, thus having a similar issue.

**Comment by 0xXA** [comment]
goodix drivers isn't xiaomi's property it's a different company so it's not their fault. Mail goodix about this

**Comment by scafroglia93** [comment]
Don't touch Xiaomi because it's my religion, it's my life

**Comment by ryan-andri** [comment]
lul, ftw @scafroglia93
