### ISSUE TITLE
Redmi Note 6 Pro Kernel Source Code Not Available In The Repository

### ISSUE THREAD

**Issue by zignd** [MiCode/Xiaomi_Kernel_OpenSource#1006]
As the title says, it seems that you guys usually release the kernel source code for your phones, but I could not find the branch for Redmi Note 6 Pro. Are you guys planning to release it?

**Comment by ryan-andri** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/commit/efbbb9cce47475c49f28d227b2a52eca6f0d02a7
they've pushed tulip in whyred-o-oss branch.

**Comment by zignd** [comment]
Oh, thanks for letting me know @ryan-andri!
