### ISSUE TITLE
红米note2 内核在手机上编译失败

### ISSUE THREAD

**Issue by zixijian** [MiCode/Xiaomi_Kernel_OpenSource#1022]
我在手机上部署了一个debian9，gcc这些工具都有，而且曾经成功的编译过一个谷歌系内核，我感觉就除了交叉编译环境不一样。
难道小米的内核就只能在pc上编译？

ocalhost:~/kernel# make O=build
/root/kernel/tools/dct/DrvGen: 1: /root/kernel/tools/dct/DrvGen: Syntax error: "(" unexpected
/root/kernel/scripts/drvgen/drvgen.mk:61: recipe for target '/root/kernel/build/drivers/misc/mediatek/mach/mt6795/lcsh6795_lwt_l/dct/dct/inc/cust_kpd.h' failed
make[1]: *** [/root/kernel/build/drivers/misc/mediatek/mach/mt6795/lcsh6795_lwt_l/dct/dct/inc/cust_kpd.h] Error 2
Makefile:130: recipe for target 'sub-make' failed
make: *** [sub-make] Error 2

**Comment by Z5X67280** [comment]
Debian的默认GCC我记得是GCC 6吧……编译Kernel的GCC版本应该还要再低一点（最多4.9），否则就得改Makefile
至于这个语法错误……🤔

**Comment by zixijian** [comment]
我有用gcc4.9，debian8上面一样的报错，这个语法错误我还真不知道哪里有问题

**Comment by zixijian** [comment]
也是糊弄人的

**Comment by anik0D** [comment]
I also facing same problem
Did you find any solution
