### ISSUE TITLE
请问Redmi 6A内核源代码配置文件是那个？

### ISSUE THREAD

**Issue by fbia1232000** [MiCode/Xiaomi_Kernel_OpenSource#1023]
请问在Redmi 6A内核源代码cactus-o-oss/arch/arm64/configs/目录下的哪一个配置文件是Redmi 6A的配置文件呀？

cactus_defconfig
cereus_defconfig
k62mv1_bsp_debug_defconfig
k62mv1_bsp_defconfig
k62v1_64_bsp_debug_defconfig
k62v1_64_bsp_defconfig
k62v1_bsp_debug_defconfig
k62v1_bsp_defconfig
k65v1_64_bsp_defconfig
k65v1_64_bsp_debug_defconfig
mt2712_agl_defconfig
mt2712_agl_nand_defconfig
mt2712_defconfig

**Comment by SamarV-121** [comment]
/arch/arm/configs/cactus_defconfig

* 6a is arm not arm64

**Comment by fbia1232000** [comment]
好的
