### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by DroidKali** [MiCode/Xiaomi_Kernel_OpenSource#1046]
/media/root/E8D49AD8223FB1C3/Xiaomi_Kernel_OpenSource/drivers/soc/qcom/subsystem_restart.c:1561:19: error: 'WT_SUBSYSTEM_RESTART_LEVEL' undeclared (first use in this function)
/media/root/E8D49AD8223FB1C3/Xiaomi_Kernel_OpenSource/drivers/soc/qcom/subsystem_restart.c:1561:19: note: each undeclared identifier is reported only once for each function it appears in

机型:Redmi 4X
编译Host: Ubuntu 18.04
gcc版本:Linaro gcc 4.9

**Comment by ivan19871002** [comment]
删除这行即可，这行是为了debug   从外部配置的

**Comment by DroidKali** [comment]
ok，我再试试

**Comment by DroidKali** [comment]
依然报错
../drivers/soc/qcom/subsystem_restart.c: In function ‘subsys_register’:
../drivers/soc/qcom/subsystem_restart.c:1546:6: warning: unused variable ‘ret’ [-Wunused-variable]
error, forbidden warning: subsystem_restart.c:1546
../scripts/Makefile.build:257: recipe for target 'drivers/soc/qcom/subsystem_restart.o' failed
make[4]: *** [drivers/soc/qcom/subsystem_restart.o] Error 1
make[4]: *** 正在等待未完成的任务....

**Comment by DroidKali** [comment]
你们能把源码改好后再上传吗？

**Comment by DroidKali** [comment]
> 删除这行即可，这行是为了debug 从外部配置的

依然报错
../drivers/soc/qcom/subsystem_restart.c: In function ‘subsys_register’:
../drivers/soc/qcom/subsystem_restart.c:1546:6: warning: unused variable ‘ret’ [-Wunused-variable]
error, forbidden warning: subsystem_restart.c:1546
../scripts/Makefile.build:257: recipe for target 'drivers/soc/qcom/subsystem_restart.o' failed
make[4]: *** [drivers/soc/qcom/subsystem_restart.o] Error 1
make[4]: *** 正在等待未完成的任务....

你们能修改后再上传吗？

**Comment by DroidKali** [comment]
> 删除这行即可，这行是为了debug 从外部配置的

麻烦给个话啊

**Comment by ivan19871002** [comment]
改好了，你自己去看新的提交吧。看过去你是基本不会改代码的同学。
