### ISSUE TITLE
小米空气净化器2S什么时候开源？

### ISSUE THREAD

**Issue by adaaaaaa** [MiCode/Xiaomi_Kernel_OpenSource#1047]
想自己调RGB灯和风扇转速。。。😄

**Comment by adaaaaaa** [comment]
@ivan19871002 所以，是否可以开源呢？

**Comment by ivan19871002** [comment]
@adaaaaaa 所以就是无法开源。

**Comment by adaaaaaa** [comment]
@ivan19871002  emmm？哪些可以开源，哪些不可以开源？？

**Comment by ivan19871002** [comment]
@adaaaaaa 你说的这个不清楚是否开源，所以在我这边就是无法开源，你可以查询一下说明书上的厂商，然后联系厂商搞定你需要的东西，另外 看过去 净化器也不是linux的。。所以应该无法开源
