### ISSUE TITLE
Redmi Note 7 Pro Kernel Source

### ISSUE THREAD

**Issue by Haseo97** [MiCode/Xiaomi_Kernel_OpenSource#1048]
Would be nice if released more faster like Mi 9 😀

**Comment by SunnyRaj84348** [comment]
This is not a flagship device ;(

**Comment by merothh** [comment]
> This is not a flagship device ;(

so what. that doesnt make it any different

**Comment by ivan19871002** [comment]
Has it been sold yet？

**Comment by rupansh** [comment]
> Has it been sold yet？

gib msm8937 little kernel much thank

**Comment by Scissordragonboy** [comment]
It would be nice if they release kernel source for redmi note 7.

**Comment by rama982** [comment]
They will release it with unified kernel for other device, Tulip, Wayne, and Whyred. Beat me.

**Comment by emman-bautista** [comment]
Mi9 Kernel was release first? I can see how top secret this note 7 kernel is. Which one is more stable to release, note 7 or mi 9? I can image the age of the device and the internal developer's attentions are pretty useless.

**Comment by ramabondanp** [comment]
what this, redmi note 7 lavender with sdm660?

**Comment by Hasaber8** [comment]
> what this, redmi note 7 lavender with sdm660?

no, Redmi Note 7 Pro (India) with sdm675

**Comment by rashedsahaji** [comment]
Please release

**Comment by Russiarain** [comment]
发布会开完啦，内核源码快快公布吧。

**Comment by Haseo97** [comment]
Up

**Comment by Jealno-zz** [comment]
+1

**Comment by Russiarain** [comment]
lavender 's kernel source has been released...it seems that note 7 and note 7 pro share the same one.

**Comment by Haseo97** [comment]
> lavender 's kernel source has been released...it seems that note 7 and note 7 pro share the same one.

No

**Comment by ramabondanp** [comment]
@Russiarain nope, 7 pro use sdm675 which use kernel 4.9
Note 7 is still on sdm660 with kernel 4.4

**Comment by Haseo97** [comment]
> @Russiarain nope, 7 pro use sdm675 which use kernel 4.9
> Note 7 is still on sdm660 with kernel 4.4

sm6150 uses 4.14 kernel (sd675)

**Comment by ramabondanp** [comment]
@Haseo97 oh yes, just know about it.

**Comment by zixijian** [comment]
It’s not so good to call lavender now.lilac looks good.

**Comment by Scissordragonboy** [comment]
> > @Russiarain nope, 7 pro use sdm675 which use kernel 4.9
> > Note 7 is still on sdm660 with kernel 4.4
> 
> sm6150 uses 4.14 kernel (sd675)

When can we expect note 7 pro kernel source released? As I have seen you did up kernel source for Redmi note 7 ...

**Comment by Haseo97** [comment]
> > > @Russiarain nope, 7 pro use sdm675 which use kernel 4.9
> > > Note 7 is still on sdm660 with kernel 4.4
> > 
> > 
> > sm6150 uses 4.14 kernel (sd675)
> 
> When can we expect note 7 pro kernel source released? As I have seen you did up kernel source for Redmi note 7 ...

Need to wait for Xiaomi to release

**Comment by Scissordragonboy** [comment]
> > > > @Russiarain nope, 7 pro use sdm675 which use kernel 4.9
> > > > Note 7 is still on sdm660 with kernel 4.4
> > > 
> > > 
> > > sm6150 uses 4.14 kernel (sd675)
> > 
> > 
> > When can we expect note 7 pro kernel source released? As I have seen you did up kernel source for Redmi note 7 ...
> 
> Need to wait for Xiaomi to release

If you got Redmi note 7. Bring up for vendor tree for Redmi note 7.

**Comment by Haseo97** [comment]
> > > > > @Russiarain nope, 7 pro use sdm675 which use kernel 4.9
> > > > > Note 7 is still on sdm660 with kernel 4.4
> > > > 
> > > > 
> > > > sm6150 uses 4.14 kernel (sd675)
> > > 
> > > 
> > > When can we expect note 7 pro kernel source released? As I have seen you did up kernel source for Redmi note 7 ...
> > 
> > 
> > Need to wait for Xiaomi to release
> 
> If you got Redmi note 7. Bring up for vendor tree for Redmi note 7.

Not interested in ROM bring-up or building, need kernel only.

**Comment by Scissordragonboy** [comment]
> > > > > > @Russiarain nope, 7 pro use sdm675 which use kernel 4.9
> > > > > > Note 7 is still on sdm660 with kernel 4.4
> > > > > 
> > > > > 
> > > > > sm6150 uses 4.14 kernel (sd675)
> > > > 
> > > > 
> > > > When can we expect note 7 pro kernel source released? As I have seen you did up kernel source for Redmi note 7 ...
> > > 
> > > 
> > > Need to wait for Xiaomi to release
> > 
> > 
> > If you got Redmi note 7. Bring up for vendor tree for Redmi note 7.
> 
> Not interested in ROM bring-up or building, need kernel only.

I want to build ROM for it. But I don't have this device. So that's why I can't bring up vendor blobs without having device. If you got an note 7. Then you can pull them from your device

**Comment by ramabondanp** [comment]
@Scissordragonboy do you mean dump rom like this
https://github.com/TadiT7/xiaomi_violet_dump
