### ISSUE TITLE
Mi 8  (dipper) dev kernel source request 

### ISSUE THREAD

**Issue by liuwang97123** [MiCode/Xiaomi_Kernel_OpenSource#1049]
We need to dev kernel source code, dipper-p-oss has not been updated for two months

**Comment by liuwang97** [comment]
希望小米工程师尽快放出开发版内核的源码，   dipper-p-oss 的源码已经有两个月没有更新了。

**Comment by ivan19871002** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/issues/1052
