### ISSUE TITLE
Mi 8 (dipper) dev kernel source request

### ISSUE THREAD

**Issue by 6QXD9** [MiCode/Xiaomi_Kernel_OpenSource#1052]
We need to dev kernel source code, dipper-p-oss has not been updated for two months，thanks

**Comment by ivan19871002** [comment]
Any questions?  is all feature work？

**Comment by mvraux** [comment]
Yes actually developers are having a hard time to keep up as sources as been updated almost 6 months ago.
Please update your sources !

**Comment by ivan19871002** [comment]
Any questions? is all feature work？

**Comment by 6QXD9** [comment]
Dc dimming and game acceleration touch settings are not available
