### ISSUE TITLE
Mi 8 lite (platina) pie kernel

### ISSUE THREAD

**Issue by J0K3RAS** [MiCode/Xiaomi_Kernel_OpenSource#1065]
Please release the android pie kernel source of mi 8 lite. Considering the release of the redmi note 7 kernel source code, which is a much newer device, the request of the mi 8 lite community is more than mature and it is fair to be seriously taken into consideration

**Comment by ramabondanp** [comment]
its released, be glad

**Comment by ramabondanp** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/nitrogen-p-oss
