### ISSUE TITLE
Redmi 7 (onclite) Kernel Source

### ISSUE THREAD

**Issue by ramabondanp** [MiCode/Xiaomi_Kernel_OpenSource#1067]
Hope it released asap too,

**Comment by noiver** [comment]
Hope it released asap too,

**Comment by laststandrighthere** [comment]
Waiting

**Comment by Kenexed** [comment]
Developers i think you need too release the kernel source immediately because there are many developers are waiting for it and the phone itself has become popular due to its specs and low price and many people wanted to root their redmi 7 (onclite) i hope you release it asap

**Comment by mylove90** [comment]
Please release the source code of the kernel

**Comment by bju2000** [comment]
Moto g7 kernel https://github.com/Alberto97/android_kernel_motorola_sdm632

Motorola has already made public.

**Comment by mylove90** [comment]
> Moto g7 kernel https://github.com/Alberto97/android_kernel_motorola_sdm632
> 
> Motorola has already made public.

how about extracting kernel configuration from boot.img and use it with moto g7 kernel sources to compile the kernel for the Redmi 7 ?

**Comment by mylove90** [comment]
> > Moto g7 kernel https://github.com/Alberto97/android_kernel_motorola_sdm632
> > Motorola has already made public.
> 
> how about extracting kernel configuration from boot.img and use it with moto g7 kernel sources to compile the kernel for the Redmi 7 ?

I was able to extract the configuration 
Here we go : [https://pastebin.com/tNPphPR7](https://pastebin.com/tNPphPR7)

**Comment by ramabondanp** [comment]
@mylove90 thats not simply, there is some specific driver changes and dts configuration which is not found on other device kernel source.

**Comment by laststandrighthere** [comment]
> > Moto g7 kernel https://github.com/Alberto97/android_kernel_motorola_sdm632
> > Motorola has already made public.
> 
> how about extracting kernel configuration from boot.img and use it with moto g7 kernel sources to compile the kernel for the Redmi 7 ?

excuse me but wtf

**Comment by mylove90** [comment]
Excuse me but i am still learning :D

**Comment by Z5X67280** [comment]
@mylove90 excuce me but how can u get the dts and driver (etc) stuff from kernel 🤔 😂

**Comment by ramabondanp** [comment]
Released: https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/onc-p-oss

**Comment by vvr3ddy** [comment]
> Please release the source code of the kernel

How bout bigNO

**Comment by mylove90** [comment]
> > > Moto g7 kernel https://github.com/Alberto97/android_kernel_motorola_sdm632
> > > Motorola has already made public.
> > 
> > 
> > how about extracting kernel configuration from boot.img and use it with moto g7 kernel sources to compile the kernel for the Redmi 7 ?
> 
> excuse me but wtf

I remember that day now :D

**Comment by tamimsoft** [comment]
Please release the source code of the kernel
