### ISSUE TITLE
Release RN5 (Whyred) Pie sources

### ISSUE THREAD

**Issue by Kugumin** [MiCode/Xiaomi_Kernel_OpenSource#1070]
So, title speaks for itself. Update them to make them compatible with Pie firmware, as without it's support kernel won't boot in system

**Comment by PrimoDev23** [comment]
So there is a way to make kernel booting, but frequencies are locked, many bugs are there and and and... Custom Kernel devs need the sources to give their users the best feeling and let them enjoy their work. Hope to get new pie sources soon!

**Comment by zakiy99** [comment]
gib pie kernel source

**Comment by GuaiYiHu** [comment]
This does work.
https://github.com/GuaiYiHu/android_kernel_xiaomi_whyred/commit/b2647f1433f94f7fd913d908aead108526586cd2

**Comment by PrimoDev23** [comment]
Problem is that this only works for pie. It is not booting on Oreo anymore after this

**Comment by GuaiYiHu** [comment]
Good, why not take nougat into consideration?

**Comment by ramabondanp** [comment]
Pie kernel changes will never boot on Oreo, same case on tulip

**Comment by PrimoDev23** [comment]
And exactly this isn't right. There is a decompiled dts version that works for Oreo aswell as for pie firmwares (for whyred its there, idk about tulip)
I wouldn't have asked if this statement would be true. The only problem (and the fact why I don't like this decompiled dts version) is that we can't easily add includes. We can't even add some nodes bc they are always giving errors. I am not talking about every nodes, just about a few... So hope anyone will find a solution for this

**Comment by ramabondanp** [comment]
The solution is when Xiaomi push pie kernel source public.
For now we only can settle with that temporary solution i think .
Also in case of tulip, they massively change  dts panel & camera in case of firmware updates.
Pie kernel dts changes make display glitch and blinking on tulip using Oreo firmware and vice versa in annoying state.

**Comment by rcstar6696** [comment]
On wayne all good no issues with pie a2 kernel base on oreo or pie custom rom

**Comment by shekhawat2** [comment]
> This does work.
> [GuaiYiHu/android_kernel_xiaomi_whyred@b2647f1](https://github.com/GuaiYiHu/android_kernel_xiaomi_whyred/commit/b2647f1433f94f7fd913d908aead108526586cd2)

this works perfectly. but dt2w gesture is not working on some devices. and fukin drains battery when enabled.
we need phix either from xiaomi or from you.😁

**Comment by Kugumin** [comment]
Sources were released!
