### ISSUE TITLE
MITV 3 60'' kernel source 

### ISSUE THREAD

**Issue by saalmaan** [MiCode/Xiaomi_Kernel_OpenSource#1072]
Hello,

Can you please release MITV 3 60'' kernel source code. Its been years since new update has arrived, very frustrating that we are stuck with Android 5.1.1. With the release of this Kernel source code, developers can at least bring latest Android TV to MITV 3 60'' and give this TV new lease of life.

Any update on this? @ivan19871002 mentioned on Weibo that MITV source kernel is coming soon, do you know any approximate dates? https://m.weibo.cn/detail/4341835327348409

@ivan19871002
https://github.com/MiCode/MiBox_Kernel_OpenSource is not for MiTV 60''. Or you are suggesting that MIBOX3(global) kernel can be used for MiTV 3 60''?

Thanks

**Comment by ivan19871002** [comment]
IF you have anyqutesion ,pls create issue on https://github.com/MiCode/MiBox_Kernel_OpenSource
