### ISSUE TITLE
Mi9 无限卡logo

### ISSUE THREAD

**Issue by xiangfeidexiaohuo** [MiCode/Xiaomi_Kernel_OpenSource#1078]
知道官方在调整，从开发9.4.8开始，那时候只是相机挂掉，现在到了9.4.23、9.4.25直接无限卡logo。

**Comment by ivan19871002** [comment]
内部已经排查一轮了，4月初相机团队进行了相机部分的大改，已经在开源计划上了。

**Comment by ivan19871002** [comment]
目前开源代码只基于稳定版开源，所有开发版开源都需要等待或者等下一个大稳定版更新，会在开源计划。所有开发版有问题的请等待
