### ISSUE TITLE
小米8青春版 platina ADSP出现问题

### ISSUE THREAD

**Issue by pomelohan** [MiCode/Xiaomi_Kernel_OpenSource#1081]
目前用的是给出的MAX3, MI 8 Lite （nitrogen-p-oss分支），不做任何直接编译出来刷入MIUI 9.4.25中，查看日志发现ADSP炸了。
在无内核源码时，使用 MIUI 9.2.* 的预编译内核和 vendor 时，无此问题。自从把 vendor 和 Prebuilt Kernel 升级至 9.3.* 后台存开始出现 ADSP 爆炸。
此外，在类原生中必须要使用 MIUI 9.2.* frimware，否则audio直接挂掉。使用 MIUI 最新 Prebuilt Kernel 时无此问题。
附件为目前正在使用的 MIUI 系统版本和 ADSP 的 crash log
![Screenshot_2019-05-07-08-54-53-020_com pluscubed matlog](https://user-images.githubusercontent.com/30499527/57266972-e6c90700-70b0-11e9-873a-41083b21881f.png)
![Screenshot_2019-05-07-10-00-29-389_com android settings](https://user-images.githubusercontent.com/30499527/57266979-f0eb0580-70b0-11e9-8dd0-1978612782b5.png)

**Comment by ivan19871002** [comment]
没明白你要表达的意思，我不管类原生和第三方所有ROM
你帮忙把在MIUI版本上 会出问题的组合都整理一下即可

**Comment by pomelohan** [comment]
目前直接用nitrogen p oss分支的源码编译出来刷入MIUI 9.4.25，ADSP炸了
简单说就这一个问题
crash log在上面

**Comment by ivan19871002** [comment]
9.4.25之前的版本呢

**Comment by pomelohan** [comment]
自从开源之后的MIUI版本都炸了应该
MIUI 9.3.*测试过一次是炸的
MIUI 9.4.*测试过两个版本是炸的
具体日期记得不的了

**Comment by ivan19871002** [comment]
log 用https://pastebin.com 发出来

另外 我看你这个简单的log 跟我认为的adsp挂是不一样的 挂， 你确定声音是没有的吗

**Comment by pomelohan** [comment]
抱歉这两天学校组织旅游信号不好编译测试较慢。
https://pastebin.com/ZWndwG6m
经过测试 audio sensor adsp 相机 目前这四个炸了 直接p oss未改动
后期还有什么炸不清楚
我在类原生开发中采取的方案是用 MIUI 9.2.*的 firmware ，除了 adsp 其他都没问题了 
（11 :53更正 相机也炸了在  MIUI 9.4.25）

**Comment by ivan19871002** [comment]
log 不够，给我一份284吧

**Comment by pomelohan** [comment]
完整的存在这里了 从开机开始的 请速度下载查看～
您说的284是什么我不理解，还需要吗？

**Comment by ivan19871002** [comment]
我double check 了一下，开源的代码是基于稳定版的，请使用稳定版的vendor 和匹配的kernel。不匹配开发版

**Comment by ivan19871002** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/commit/dc8e417a8d54d8c0893f19b97fb448d2a72b058d

这条修改，开发版上 改了adsp 挂载名称，需要配合对应开发版的 firmware

**Comment by pomelohan** [comment]
@ivan19871002 谢谢男神，辛苦您了
