### ISSUE TITLE
Tiare Broken Source

### ISSUE THREAD

**Issue by SunnyRaj84348** [MiCode/Xiaomi_Kernel_OpenSource#1084]
Even it can't get compiled successfully lol

**Comment by ramabondanp** [comment]
gib log, maybe xiaomi dev will fix

**Comment by 0xXA** [comment]
> Even it can't get compiled successfully lol

[Watch](https://asciinema.org/a/NgBCkKUZOWmGPV5iH6avxMIL1)

**Comment by SunnyRaj84348** [comment]
> > Even it can't get compiled successfully lol
> 
> [Watch](https://asciinema.org/a/NgBCkKUZOWmGPV5iH6avxMIL1)

Oh man , why it has riva dtb

**Comment by 0xXA** [comment]
> Oh man , why it has riva dtb
Those two have same boards that's why some pll and memory reasons should differ or possibly xiaomi used same code of Riva and ported to this device **redmi go**

**Comment by 0xXA** [comment]
> Oh man , why it has riva dtb

Those two have same boards,pll and memory should differ or possibly xiaomi used same code of Riva and ported to this device **redmi go**

**Comment by SunnyRaj84348** [comment]
> > Oh man , why it has riva dtb
> 
> Those two have same boards,pll and memory should differ or possibly xiaomi used same code of Riva and ported to this device **redmi go**

Oh, I thought they released riva oreo source with tiare 
Thanks.
