### ISSUE TITLE
Redmi K20Pro kernel source please

### ISSUE THREAD

**Issue by ghost** [MiCode/Xiaomi_Kernel_OpenSource#1090]
Redmi K20Pro (-Raphael) has been released several weeks ago, we hope to provide source code in the near future.Thanks.

**Comment by Zenderable** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/raphael-p-oss/drivers/input/touchscreen it's here

**Comment by scafroglia93** [comment]
A beautiful milestone from a private release released by qualcomm that will never be updated by the manufacturer.
If this is open source I am Xi Jinping

**Comment by ivan19871002** [comment]
That is not a joke, dont talk about leaders.  only about code

**Comment by ivan19871002** [comment]
@scafroglia93  If you talk about leaders , i will block you.

**Comment by scafroglia93** [comment]
That's moral liberty
