### ISSUE TITLE
davinci Kernel Sources (Redmi K20/Mi 9T)

### ISSUE THREAD

**Issue by FaserF** [MiCode/Xiaomi_Kernel_OpenSource#1091]
Please release the Kernel Sources for the davinci as the kernel sources for raphael (Redmi K20 Pro) have already been released.

Thank you.

**Comment by sorryusernameisalreadytaken** [comment]
Are there any plans for a release for the Mi 9T. We really need it 👍

**Comment by kairusds** [comment]
mi 9t is redmi k20 and it's already in the readme

**Comment by sorryusernameisalreadytaken** [comment]
> 
> 
> mi 9t is redmi k20 and it's already in the readme

Did they have 100% the same kernel? I mean the differ in some hardware points. Or?

**Comment by FaserF** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/davinci-p-oss
