### ISSUE TITLE
[grus-p-oss] fingerprint-on-display issues on latest miui dev rom

### ISSUE THREAD

**Issue by ghost** [MiCode/Xiaomi_Kernel_OpenSource#1092]
It works before on MIUI 9.5.25.
But on the MIUI 9.6.5, it can't read any events on the FOD's anymore.
Any plans for source updates ? thanks.

**Comment by ghost** [comment]
after comparing dmesg, I saw that it has a new `gtp_init_touchmode_data()` that invokes `xiaomitouch_register_modedata()` (probably for pocket sensor detection), and the `goodix_gt9886_cfg_f2.bin` has a different esd register and bumped version.

**Comment by Gah0** [comment]
before miui 9.6.5 
`[    0.966609] [GTP-INF][goodix_parse_cfg_bin:153] esd reg:303f`

after miui 9.6.5
```
[    0.976325] [GTP-INF][goodix_parse_cfg_bin:153] esd reg:30f3
[    1.178402] [GTP-INF][goodix_check_update:307] Firmware needs to be updated
```

**Comment by ghost** [comment]
still no updates huh
