### ISSUE TITLE
integer overflow in sde_connector [andromeda-p-oss]

### ISSUE THREAD

**Issue by scafroglia93** [MiCode/Xiaomi_Kernel_OpenSource#1098]
Possible Integer Overflow in _sde_debugfs_conn_cmd_tx_write method in drivers/gpu/drm/msm/sde/sde_connector.c

https://github.com/MiCode/Xiaomi_Kernel_OpenSource/blob/74347f5521fb444936f5986ff0937264307d78fe/drivers/gpu/drm/msm/sde/sde_connector.c#L1564

Although the problem was previously reported on the twin device was not resolved, a copy / paste of the part was performed

**Comment by ivan19871002** [comment]
Feedback has been given to the display team.
Thank you.
