### ISSUE TITLE
Error in building the kernel

### ISSUE THREAD

**Issue by deeplyarnab** [MiCode/Xiaomi_Kernel_OpenSource#11]
> arch/arm/mach-msm/smd_init_dt.c:23:25: fatal error: smd_private.h: No such file or directory
> # include smd_private.h
> 
> ```
>                     ^
> ```
> 
> compilation terminated.
> make[1]: **\* [arch/arm/mach-msm/smd_init_dt.o] Error 1
> make: **\* [arch/arm/mach-msm] Error 2
> make: **\* Waiting for unfinished jobs....

Error while building the kernel in the file (line 24)

> arch/arm/mach-msm/smd_init_dt.c
> cannot find smd_private.h

Solution:-
Replace <> with ""

**Comment by emceethemouth** [comment]
That's not the proper way to fix this, you should do this: https://github.com/emceethemouth/kernel_cancro/commit/f5dcfd29b029deeafacb39b82bd5ff94cb437fee

**Comment by deeplyarnab** [comment]
Anyways, these work too
