### ISSUE TITLE
Please update MIX 3 kernel source code

### ISSUE THREAD

**Issue by SubDragonzj** [MiCode/Xiaomi_Kernel_OpenSource#1100]
The newest MIUI distance sensors HAL cannot work on Xiaomi now open source kernel code. So,need xiaomi update the kernel source.

**Comment by YumeMichi** [comment]
They've forgotten SDM845 series.

**Comment by ramabondanp** [comment]
Help please @ivan19871002

**Comment by ivan19871002** [comment]
after new device  release,  then upgrade old device
