### ISSUE TITLE
Xiaomi Mi 6 (sagit) Android P (9.0) kernel sources

### ISSUE THREAD

**Issue by Zenderable** [MiCode/Xiaomi_Kernel_OpenSource#1106]
Please release the kernel sources based on Android P for Mi 6 (sagit)
Thanks you.

**Comment by liuguo09** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/sagit-p-oss

**Comment by wode2016501** [comment]
小米6 怎么选defconf   6+64
