### ISSUE TITLE
Mi 9T / K20 kernel and DTS are broken

### ISSUE THREAD

**Issue by MirkoCovizzi** [MiCode/Xiaomi_Kernel_OpenSource#1116]
Hi everyone!
I've successfully compiled the kernel, however I noticed that the samsung display device tree source is linked to nothing in the K20 source. This results in a compiled (through the official DTB tool mkdtboimg) dtbo.img that doesn't boot properly, lacking all the timings and informations of the samsung display.
There seems to be a profound issue in the kernel source, especially since there is a substantial difference in the commit concerning the Samsung display between the K20 Pro and the K20.

[dts.tar.gz](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/files/3429197/dts.tar.gz)

**Comment by MirkoCovizzi** [comment]
Made a breakthrough:
Unpacked dtbo.img from global firmware 10.3.6. Decoded the .dtb into .dts. Taken the 13 .dts relevant to the device (check Makefile). Re-encoded and repacked in a new, smaller dtbo.img.
I flashed this new dtbo.img through fastboot, booting successfully the device.
By taking the .dts provided by Xiaomi in the Mi 9T / K20 repo and compiling them, then packing them into a dtbo.img, and then flashing said .img through fastboot causes an unsuccessfull boot and a black screen.
So, I took the first .dts (from the source) and compared it to the correspondent .dts  (from the decoded global firmware) and got this interesting diff (green one is the one working, red one is from the source that doesn't work):

https://pastebin.com/wNu0mVy0

So, there is obviously something wrong going on, concerning the display commands.

**Comment by Zenderable** [comment]
I confirm that there is a problem.

**Comment by MirkoCovizzi** [comment]
Update:

The device tree clearly has some problems. However, the kernel is clearly broken too. Flashed over eu stable 10.3.12.0 without changing dtbo doesn't boot. Flashed over eu stable 10.3.12.0 together with the dtbo image obtained compiling the source device tree doesn't boot too (bootloop).

**Comment by PIPIPIG233666** [comment]
@ivan19871002

**Comment by PIPIPIG233666** [comment]
> Made a breakthrough:
> Unpacked dtbo.img from global firmware 10.3.6. Decoded the .dtb into .dts. Taken the 13 .dts relevant to the device (check Makefile). Re-encoded and repacked in a new, smaller dtbo.img.
> I flashed this new dtbo.img through fastboot, booting successfully the device.
> By taking the .dts provided by Xiaomi in the Mi 9T / K20 repo and compiling them, then packing them into a dtbo.img, and then flashing said .img through fastboot causes an unsuccessfull boot and a black screen.
> So, I took the first .dts (from the source) and compared it to the correspondent .dts (from the decoded global firmware) and got this interesting diff (green one is the one working, red one is from the source that doesn't work):
> 
> https://pastebin.com/wNu0mVy0
> 
> So, there is obviously something wrong going on, concerning the display commands.

It seems there are two different dts ,one is samsung ,another is ss.
[https://github.com/MiCode/Xiaomi_Kernel_OpenSource/blob/davinci-p-oss/arch/arm64/boot/dts/qcom/dsi-panel-samsung-fhd-ea8076-f3b-cmd.dtsi](url)
[https://github.com/MiCode/Xiaomi_Kernel_OpenSource/blob/davinci-p-oss/arch/arm64/boot/dts/qcom/dsi-panel-ss-fhd-ea-f10-cmd.dtsi](url)

**Comment by MirkoCovizzi** [comment]
> 
> 
> > Made a breakthrough:
> > Unpacked dtbo.img from global firmware 10.3.6. Decoded the .dtb into .dts. Taken the 13 .dts relevant to the device (check Makefile). Re-encoded and repacked in a new, smaller dtbo.img.
> > I flashed this new dtbo.img through fastboot, booting successfully the device.
> > By taking the .dts provided by Xiaomi in the Mi 9T / K20 repo and compiling them, then packing them into a dtbo.img, and then flashing said .img through fastboot causes an unsuccessfull boot and a black screen.
> > So, I took the first .dts (from the source) and compared it to the correspondent .dts (from the decoded global firmware) and got this interesting diff (green one is the one working, red one is from the source that doesn't work):
> > https://pastebin.com/wNu0mVy0
> > So, there is obviously something wrong going on, concerning the display commands.
> 
> It seems there are two different dts ,one is samsung ,another is ss.
> [https://github.com/MiCode/Xiaomi_Kernel_OpenSource/blob/davinci-p-oss/arch/arm64/boot/dts/qcom/dsi-panel-samsung-fhd-ea8076-f3b-cmd.dtsi](url)
> [https://github.com/MiCode/Xiaomi_Kernel_OpenSource/blob/davinci-p-oss/arch/arm64/boot/dts/qcom/dsi-panel-ss-fhd-ea-f10-cmd.dtsi](url)

It's the second one the one to consider (which is still a Samsung display, by the way). It is the one that gets compiled in the dtbo.

**Comment by MirkoCovizzi** [comment]
@PIPIPIG233666 I'm not completely sure adding the f3b-cmd.dtsi would solve the issues. In the first diff, some commands used by the stock kernel (based on miui.eu 10.3.12.0) are even different from the ones found in the f3b-cmd.dtsi.

**Comment by MirkoCovizzi** [comment]
Update: on the lineageos port I did a couple of days ago both kernel and dts work. No change needed. It appears it can't work on miui only for some reason.
