### ISSUE TITLE
64bit Update for Redmi 7A (pine)

### ISSUE THREAD

**Issue by cheemskek** [MiCode/Xiaomi_Kernel_OpenSource#1117]
Give 64bit update for Redmi 7A (pine) as soc is 64bit supported. Thanks!

**Comment by faprioryan** [comment]
Please.

**Comment by ramabondanp** [comment]
it will not happen.
see Redmi S2 / Y2

**Comment by cheemskek** [comment]
> it will not happen.
> see Redmi S2 / Y2

😂😂 ik

**Comment by faprioryan** [comment]
Sed ;_;
