### ISSUE TITLE
小白请教一个编译问题

### ISSUE THREAD

**Issue by Remember2018** [MiCode/Xiaomi_Kernel_OpenSource#1118]
大家好，请教大家一个问题：我有一个红米Note2的手机很久没用了。后来想着用来做开发。但是发现现有的rom 基本都是Android 5.0版本的。我在这个repo找到小米开源的也是Android L版本，也就是5.0版本。请问自己编译高版本的Android ROM可行吗？我的想法是，应该要从官方这个repo里面提取一些相关的文件，替换掉Android 9.0源码里的文件，然后是否新的ROM就能支持Redmi Note 2呢？

**Comment by PIPIPIG233666** [comment]
自己参考GuaiYiHu的

**Comment by Remember2018** [comment]
@PIPIPIG233666 谢谢大佬！看你们github和微博，都是大神啊！膜拜膜拜！
