### ISSUE TITLE
红米K20内核无法启动

### ISSUE THREAD

**Issue by PIPIPIG233666** [MiCode/Xiaomi_Kernel_OpenSource#1121]
@ivan19871002

**Comment by PIPIPIG233666** [comment]
必须用官方的dtbo
编译的卡米

**Comment by PIPIPIG233666** [comment]
编译dtbo过程中有报错，但编译不会停止，因此dts还是炸的

**Comment by PIPIPIG233666** [comment]
dtc问题，感谢秋大的指导

**Comment by ziyan901** [comment]
你好，能出个教程吗？

**Comment by PIPIPIG233666** [comment]
> 你好，能出个教程吗？
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/wiki/How-to-compile-kernel-standalone#noteif-your-compiled-kernel-cannot-boot-pls-use-clang--609
