### ISSUE TITLE
grus-p-oss is outdated and incompatible with newest MIUI (v9.8.8)

### ISSUE THREAD

**Issue by ghost** [MiCode/Xiaomi_Kernel_OpenSource#1123]
- broken audio-kernel on MIUI 9.8.8
- `drivers/video/backlight/backlight.c` can't properly store 2nd brightness for DC dimming (since MIUI 9.6.25)
- goodix `core_data->fod_status` is not properly initialized on boot (since MIUI 9.5.30).
- broken ion dts that required by the camera (since MIUI stable 10.2.5.0).
- outdated `dsi-panel-samsung-fhd-ea8076-cmd.dtsi`, doesn't have proper `qcom,disp-fod-off-dimming-delay` (since MIUI stable 10.2.5.0).

**Comment by Gah0** [comment]
请求源码能尽快更新，感谢..
ivan19871002

**Comment by atomsand** [comment]
@ivan19871002 秋大放一下sm8150的Q版kernel吧

**Comment by ghost** [comment]
nevermind, I'm gonna sell my device instead

**Comment by archfan** [comment]
Please fix.
