### ISSUE TITLE
cepheus-p-oss Base tag失效

### ISSUE THREAD

**Issue by shenzhenkevin** [MiCode/Xiaomi_Kernel_OpenSource#1140]
按照wiki指导下载高通project，提示tag不存在：
fatal: manifest 'LA.UM.7.1.r1-07600-sm8150.0.xml' not available
fatal: manifest LA.UM.7.1.r1-07600-sm8150.0.xml not found

**Comment by PIPIPIG233666** [comment]
这是私有tag，还有你编译内核下caf源码干啥

**Comment by DroidKali** [comment]
他可能是想要编译出wifi和audio能用的内核，小米官方开源的源码没有包含高通WLAN驱动，而wiki里面说要想wifi和audio能用就必须要下载QAEP

**Comment by shenzhenkevin** [comment]
wiki指导是按照下载高通工程，然后替换后进行编译。下载高通工程需要使用tag。

**Comment by PIPIPIG233666** [comment]
`liuguo09 edited this page on May 27, 2015 · 1 revision`
上次更改->四年前
自己体会

**Comment by PIPIPIG233666** [comment]
顺便给你附上[正确的教程](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/wiki/How-to-compile-kernel-standalone)
