### ISSUE TITLE
wiki指导太老了，根本没法指导现在的编译。比如现在kernel目录结构都变化了。

### ISSUE THREAD

**Issue by shenzhenkevin** [MiCode/Xiaomi_Kernel_OpenSource#1141]

**Comment by PIPIPIG233666** [comment]
比如？

**Comment by shenzhenkevin** [comment]
比如kernel顶层目录就变了，wiki中下面的操作就是错误的：
~/Qualcomm_Android$ rm -rf kernel/*
~/Qualcomm_Android$ cp -rf ~/Mi_Kernel/Xiaomi_Kernel_OpenSource/* kernel/
现在kernel顶层目录下是configs和 msm-4.14两个子文件夹

**Comment by PIPIPIG233666** [comment]
很抱歉，你看错教程了
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/issues/1140#issuecomment-544771890

**Comment by shenzhenkevin** [comment]
参照其它教程
