### ISSUE TITLE
[lavender-p-oss/tulip-p-oss] Camera issue with MIUI 11 Stable

### ISSUE THREAD

**Issue by ramabondanp** [MiCode/Xiaomi_Kernel_OpenSource#1142]
Camera is broken on latest MIUI 11 Stable (V11.0.2.0.PFGCNXM) using current kernel source on custom kernel, no issue with stock kernel from MIUI.

**Comment by ramabondanp** [comment]
Apparently this issue also happen on MIUI 11 update for tulip (Redmi Note 6 Pro) version V11.0.1.0.PEKMIXM

**Comment by Kugumin** [comment]
Whyred (Redmi Note 5) has absolutely the same issue on MIUI11!

**Comment by rama982** [comment]
This when

**Comment by ramabondanp** [comment]
Xiaomi update camera stack driver source please

**Comment by ivan19871002** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/commit/cf2a90f96348c6a3142d53ca209983da18c72410
