### ISSUE TITLE
crux编译到vmlinux.o的时候报错member techpack/audio/dsp/elliptic in archive is not an object

### ISSUE THREAD

**Issue by StorySea** [MiCode/Xiaomi_Kernel_OpenSource#1148]
加入techpack文件夹并配置好data-kernel和audio的一些文件后 编译报错
member techpack/audio/dsp/elliptic in archive is not an object。
已检查无文件缺失和报错

**Comment by StorySea** [comment]
编译器已尝试clang8和clang10结果全部一致

**Comment by StorySea** [comment]
built-in.o: member techpack/audio/dsp/elliptic in archive is not an object

**Comment by StorySea** [comment]
dsp已经包含了，取消audio下Makefile里的obj-y += dsp/elliptic/和obj-y += dsp/mius/后能编译通过但是无声音。编译里已经编译进去。。

**Comment by PIPIPIG233666** [comment]
切成builtin

**Comment by TwistedPrime** [comment]
How did you fix this?

**Comment by ZNZ930** [comment]
> 切成builtin

大佬，怎么切
