### ISSUE TITLE
Source code kernel  mi 9 android q

### ISSUE THREAD

**Issue by EviraKernel** [MiCode/Xiaomi_Kernel_OpenSource#1151]
pls when is relase it source code for kernel android q mi 9

**Comment by thune-xiaobai** [comment]
> pls when is relase it source code for kernel android q mi 9

After MIUI q stable version released.

**Comment by mrslezak** [comment]
So MIUI 11 Stable is fully released.  For Cepheus and Raphael.  Where is the Android 10 kernel source?  GPL requirement to post source when used by a company in their software.  What's the timeline?

**Comment by ai94iq** [comment]
> > pls when is relase it source code for kernel android q mi 9
> 
> After MIUI q stable version released.

It's already released in multiple regions 🤦‍♂️

Also beta/weekly based on Q has been going for +3 months now, and no signs of kernel source, GPL should apply to beta releases also

**Comment by mrslezak** [comment]
Well we have the GPL enforcement lawyers in Germany on standby just wanting an answer from Xiaomi on the release date.  Hopefully Xiaomi will just post Android 10 source on their own.

**Comment by ai94iq** [comment]
👏where👏is👏the👏 kernel👏source👏
👏 global👏 ROMs👏 already👏got👏 released👏

**Comment by RobMacGregor** [comment]
Looking forward to the kernel as well.

**Comment by ivan19871002** [comment]
this month .

**Comment by ritujb** [comment]
No more delays. Give kernel source ASAP!!

**Comment by PIPIPIG233666** [comment]
> No more delays. Give kernel source ASAP!!

this week afaik

**Comment by StorySea** [comment]
> this month .

This month is almost over.....Please keep your promise

**Comment by Kugumin** [comment]
The time will come soon, we are waiting for sources

**Comment by StorySea** [comment]
the last day..So it's really a monkey-playing company

**Comment by 1582130940** [comment]
Expected to be released on Monday, December 1st

**Comment by AndroMor** [comment]
This is my last Xiaomi phone. Why no kernel till now  Really slow Xiaomi 🤬
