### ISSUE TITLE
K20 Pro/Mi 9T Pro Q kernel sources

### ISSUE THREAD

**Issue by Kugumin** [MiCode/Xiaomi_Kernel_OpenSource#1155]
Since GS (MI) update channel got Android 10 all devs are expecting to see updated sources in near future!

**Comment by ai94iq** [comment]
this month .

_Originally posted by @ivan19871002 in https://github.com/MiCode/Xiaomi_Kernel_OpenSource/issues/1151#issuecomment-555961837_

**Comment by dcionline** [comment]
let them patching first issues, or want buggy sources instead? Damn all has to be fast ans after its bad if it doesnt work.

**Comment by ai94iq** [comment]
> let them patching first issues, or want buggy sources instead? Damn all has to be fast and after its bad if it doesnt work.

They have been releasing ten builds since early August with Miui weekly builds, I'm pretty sure they have done enough work on it already

**Comment by ghost** [comment]
> let them patching first issues, or want buggy sources instead? Damn all has to be fast and after its bad if it doesnt work.
the opened sources will never get patched, you have to fix yourself

**Comment by pappschlumpf** [comment]
I would be very pleased too if you would release the Mi9 MI9T source asap.

**Comment by AndroMor** [comment]
I can't wait longer for Raphael kernel sources I am moving to another phone other than Xiaomi 🤬 slow

**Comment by pappschlumpf** [comment]
Well Xiaomi, what's going on? Couldn't be that difficult to upload sources?!

**Comment by ai94iq** [comment]
Woah guys, wait for Monday to come at least

**Comment by Kugumin** [comment]
It's already 1st December in China 😁

**Comment by ai94iq** [comment]
> It's already 1st December in China

Don't expect anything on Sunday 🌚

**Comment by UtsavBalar1231** [comment]
> > It's already 1st December in China
> 
> Don't expect anything on Sunday

;_;

**Comment by ai94iq** [comment]
> > It's already 1st December in China
> 
> Don't expect anything on Sunday

oh boi, that didnt age well 


https://github.com/MiCode/Xiaomi_Kernel_OpenSource/commit/b9b846d10d9596dc58f7c6b61b86260876a99988

**Comment by Kugumin** [comment]
Sources are released. Closing issue 😁
