### ISSUE TITLE
Mi9 q source

### ISSUE THREAD

**Issue by EviraKernel** [MiCode/Xiaomi_Kernel_OpenSource#1159]
I Compile latest mi9 q source no audio audio driver missing on source maybe need enable some?

**Comment by bgcngm** [comment]
Dude, open your eyes: https://github.com/MiCode/vendor_qcom_opensource_audio-kernel

**Comment by StorySea** [comment]
need to import audio driver

**Comment by EviraKernel** [comment]
i import audio driver but have problem with fp still not recognize wifi e audio no problem stock defconfig

**Comment by StorySea** [comment]
> i import audio driver but have problem with fp still not recognize wifi e audio no problem stock defconfig

force load modules

**Comment by mrslezak** [comment]
He's saying the FP sensor isn't working after importing all the audio kernel and WiFi items.  Everything else is working now.  Force loading modules.  Anyone else had this issue or a resolution?  Cepheus...

**Comment by StorySea** [comment]
> He's saying the FP sensor isn't working after importing all the audio kernel and WiFi items. Everything else is working now. Force loading modules. Anyone else had this issue or a resolution? Cepheus...

it's stable miui 11 kernel source,not dev，so if use it in the newest dev miui version,fp doesn't work.....in the stable MIUI11 or lower than 9.10.10 dev MIUI chaina version fp works. need xiaomi to solve it

**Comment by dcionline** [comment]
take a log?

**Comment by ivan19871002** [comment]
Now ,  Only support stable ,  not dev.
