### ISSUE TITLE
 Could Xiaomi tell us what changed the fingerprint K20P and Mi 9 Q source in the dev (maybe future stable version)

### ISSUE THREAD

**Issue by StorySea** [MiCode/Xiaomi_Kernel_OpenSource#1164]
We know that the open source is based on the stable miui version, because the dev MIUI version is updated very quickly, and there are so many Xiaomi models. If the open source is based on the dev version, That would be a very onerous job。

But the current dev miui version is likely to be the future stable miui version, and the stable version will basically not be updated after the openning unless it is the next Android version 11 etc. 

So could Xiaomi tell us in the issues what changed in the fingerprint drivers K20P and Mi9 Q Sources in the dev (maybe future stable version)

Thanks a lot

**Comment by shandongtlb** [comment]
I understand your developers' hard work very much, but I'd like to tell us how to fix or patch it. Thank you

**Comment by RuyimgByCN** [comment]
miui11 dev指纹什么时候开放？

**Comment by Kugumin** [comment]
Xiaomi, gib working sources for FOD in Dev ROMs plox

**Comment by pikachukaki** [comment]
+1

**Comment by StorySea** [comment]
so didn't get any response?

**Comment by Kugumin** [comment]
Seems like Xiaomi doesn't care about that

**Comment by ivan19871002** [comment]
after other 8150 device release stable verion.  We will release next kernel

**Comment by shandongtlb** [comment]
> after other 8150 device release stable verion. We will release next kernel

thanks XD
