### ISSUE TITLE
mi9/k20pro  q-kernel-source

### ISSUE THREAD

**Issue by shandongtlb** [MiCode/Xiaomi_Kernel_OpenSource#1166]
Dear developers, I found that the Q-based kernel source code does not support the development version. I know you are very busy, but please tell us how to upgrade the source code to adapt the development version,thanks a lot!

**Comment by Kugumin** [comment]
Kernel sources will be updated when other devices on SM8150 (SDM855) will get Stable ROM as @ivan19871002 stated in #1164

**Comment by shandongtlb** [comment]
> Kernel sources will be updated when other devices on SM8150 (SDM855) will get Stable ROM as @ivan19871002 stated in #1164

Copy that

**Comment by Kugumin** [comment]
Close issue 😁
