### ISSUE TITLE
Is it possible to bring exFAT support to Xiaomi Phones

### ISSUE THREAD

**Issue by asypost** [MiCode/Xiaomi_Kernel_OpenSource#1167]
Linux kernel 5.4 has been released a couple of weeks ago.Since then Linux has exFAT support in the kernel([refer](https://itsfoss.com/linux-kernel-5-4/)),so I am wondering is it possible to integrate exFAT driver in Xiaomi Kernel?

**Comment by ivan19871002** [comment]
https://github.com/MiCode/exfat-nofuse
