### ISSUE TITLE
Update kernel for Xiaomi Mi Max 2 (oxygen) for oreo or pie

### ISSUE THREAD

**Issue by Scissordragonboy** [MiCode/Xiaomi_Kernel_OpenSource#1170]
Update kernel source for oreo or pie for Xiaomi Mi Max 2. If you can't then simply abondon development for xiaomi devices. If you don't care about old released devices.

**Comment by ivan19871002** [comment]
We dont have  Oreo or Pie for Max 2.

So  sorry.

**Comment by Scissordragonboy** [comment]
Its not the answer.

We have kernel for android-10 for xiaomi mi max 2. Then why can't you update it for Oreo? Lmao.
