### ISSUE TITLE
Request to update the existing stock kernel source code for Redmi Note 5, Redmi Note6 Pro, Mi 6X

### ISSUE THREAD

**Issue by Aquarius223** [MiCode/Xiaomi_Kernel_OpenSource#1176]
Starting from MIUI10 version 9.8.15, the camera on the kernel compiled based on the Xiaomi kernel does not work properly. Now we can only synchronize the old camera driver or transplant the camera driver of Xiaomi MAX 3 to temporarily solve the camera problem. In order to ensure the kernel and the system Stability, I hope Xiaomi will update the kernel source code of these models. Thank you

**Comment by ivan19871002** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/commit/cf2a90f96348c6a3142d53ca209983da18c72410
