### ISSUE TITLE
onc-p-oss

### ISSUE THREAD

**Issue by Zer0nite** [MiCode/Xiaomi_Kernel_OpenSource#1177]
I got this error when I try to build the Redmi 7 kernel

`DTC     arch/arm64/boot/dts/qcom/apq8053-lite-dragon-v1.0.dtb`
`ERROR (phandle_references): Reference to non-existent node or label "typec_ssmux_config"`

`ERROR: Input tree has errors, aborting (use -f to force output)`
`make[2]: *** [scripts/Makefile.lib:319: arch/arm64/boot/dts/qcom/apq8053-lite-dragon-v1.0.dtb] Error 2`
`make[1]: *** [scripts/Makefile.build:653: arch/arm64/boot/dts/qcom] Error 2`
`make: *** [arch/arm64/Makefile:161: dtbs] Error 2`

**Comment by wyourname** [comment]
我也想知道这个问题怎么解决·

**Comment by NCLnclNCL** [comment]
> 我也想知道这个问题怎么解决·

How to fix
