### ISSUE TITLE
dipper-q-oss break camera in stable miui 11.0.5

### ISSUE THREAD

**Issue by StorySea** [MiCode/Xiaomi_Kernel_OpenSource#1179]
camera cannt work in miui 11.0.5 android Q,so it's not stable source？camara not work in above 11.14 dev miui too...only work under 11.14 miui or lower dev

**Comment by shandongtlb** [comment]
活捉老大

**Comment by YumeMichi** [comment]
糟心啊

**Comment by ivan19871002** [comment]
I found the rootcasue,  test it .pls wait .

**Comment by ivan19871002** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/commit/dcfb1676925aec83b06ae04fd8ca989ced75067c#
