### ISSUE TITLE
红米note7 pro 支付宝指纹支付无法使用

### ISSUE THREAD

**Issue by ningsibuqu** [MiCode/Xiaomi_Kernel_OpenSource#1182]
当时这手机出厂就是一批能用支付宝，另一批不能用支付宝，后续红米官方是在软件打了hack才能在miui上使用支付宝指纹支付的。
总而言之，现在开源出来的代码是无法使用支付宝指纹支付的（有一批机器可以，但是没有关闭选项），红米官方人员能帮忙解决这个问题吗？

**Comment by ivan19871002** [comment]
所有支付相关代码，跟kernel代码无关
