### ISSUE TITLE
umi-q-oss source tree: make[3]: *** No rule to make target 'arch/arm64/boot/dts/qcom/apq8016-sbc.dtb', needed by '__build'.  Stop.

### ISSUE THREAD

**Issue by mrslezak** [MiCode/Xiaomi_Kernel_OpenSource#1201]
I believe there is incorrect source to build umi-q-oss.  First, all CONFIG_ARCH_QCOM in the Makefile /arch/arm64/boot/dts/qcom/ if not commented out, the build will fail. make[3]: *** No rule to make target 'arch/arm64/boot/dts/qcom/apq8016-sbc.dtb', needed by '__build'.  Stop.  This is even with the stock repo code unmodified.

After merging all portions of the Qualcomm source in properly (techpack audio, data_kernel, qcacld wlan, device_tree), the build error remains.  I used GCC and also Clang, same error.

Merged code is here: https://github.com/mrslezak/umi-q-oss,  A debug build log is there (kernel.log) and a build script "Build GCC10 Umi.sh."  I have consulted with several professional developers and they cannot resolve the issue.

All of these files (less the new one sdm845.dtsi) build properly in cepheus-q-oss, just not here.

Please review and remedy with commits.  Otherwise, this source is not useable for anyone.

**Comment by nakixii** [comment]
Have you solved this problem?

**Comment by mrslezak** [comment]
Yeah look in my GitHub repo mrslezak umi-q-oss

**Comment by zixijian** [comment]
我在红米note9pro gauguin 本机上编译内核遭遇了类似问题。
更换gcc4.8、7.3、8.0均不能成功，不知道内核代码还需要做什么操作。
