### ISSUE TITLE
Redmi 7/Y3 Android 10

### ISSUE THREAD

**Issue by mylove90** [MiCode/Xiaomi_Kernel_OpenSource#1210]
Dear Xiaomi,

Good day.

It has been long since Miui 11 released for our device onc/onclite but with Android 9.0....Will the device receive an update to Android 10 or not ????

We already got multiple custom roms for Android 10...So we are sure our device can handle it very well.

Thanks in advance
Best regards

**Comment by mylove90** [comment]
WOW....Xiaomi devs are so professionals that they didn't even look at that open issue !

**Comment by johnmart19** [comment]
Redmi 7 Needs Android 10 Update!

**Comment by Loco1911** [comment]
Update Redmi 7 to Android 10!!!

**Comment by uaaaaaaa** [comment]
UPDATE XIAXAXAXAXAXAXXIOMI REDMEME 7 TO ANDROID 10 OR I WILL CRI EVERTM

**Comment by uaaaaaaa** [comment]
THIS IS SERIUSLY IM NOT JOKEN SRY FOR BAD ENGLAND UWU

**Comment by Renshi15** [comment]
We love our Redmi 7 onclite, pls make an update for android 10

**Comment by Zelectic** [comment]
GIVE US THE UPDATE WTF? ANDROID 10 CMON

**Comment by junior0liveira** [comment]
Xiaomi where is the update for android 10 on Redmi 7 onclite !?

**Comment by ersascape** [comment]
Gib updoot for Xiaomi Redmi 7 phassssssttttttttttttt

**Comment by PapiLer** [comment]
Redmeme 7 android 10 when plxx

**Comment by SyncSilent** [comment]
We need Android 10 for REDMI 7!!

**Comment by Heyxtomas** [comment]
Dear Xiaomi, Please start working on Android 10, which you promised us. Don't forget us !!

**Comment by asnoman2** [comment]
Please Android 10 with miui 12

**Comment by ragy365** [comment]
Gib Redmi 7 Android 10 update , plox

**Comment by kairusds** [comment]
up

**Comment by PIPIPIG233666** [comment]
Down
This is not the right place...

**Comment by ragy365** [comment]
> Down
> This is not the right place...

Up
It is...

**Comment by hamohamo6** [comment]
Can we get android 10 already

**Comment by Renshi15** [comment]
Pls release android 10 for our redmi 7

**Comment by ersascape** [comment]
Android 10 China released. When releasing sources?!

**Comment by mylove90** [comment]
Thanks for releasing the sources :)
