### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by EduardoA-13** [MiCode/Xiaomi_Kernel_OpenSource#1216]
I have this error when compiling

`drivers/bluetooth/btfm_slim.c:26:23: error fatal: btfm_slim.h: No existe el archivo o el directorio
 #include <btfm_slim.h>
                       ^
compilación terminada.
scripts/Makefile.build:282: recipe for target 'drivers/bluetooth/btfm_slim.o' failed
make[2]: *** [drivers/bluetooth/btfm_slim.o] Error 1
scripts/Makefile.build:489: recipe for target 'drivers/bluetooth' failed
make[1]: *** [drivers/bluetooth] Error 2
Makefile:1024: recipe for target 'drivers' failed
make: *** [drivers] Error 2
`
`

**Comment by sekaiacg** [comment]
Wiki has instructions
[How-to-compile-kernel-standalone](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/wiki/How-to-compile-kernel-standalone)
```
maybe some of you face compile error like this error: msm_isp.h: No such file or directory

In android source code (caf), It is already setup environment. like O=out/target/product/{TARGET_PRODUCT}/obj/kernel/, toolchain= ARCH=arm64/arm/x86/mips

it's not a problem with kernel at all! This can be fixed by redirecting output to a out folder as done in steps above
```

Add output folder: make O=out
