### ISSUE TITLE
Kernel source for Android 10, sdm710 devices

### ISSUE THREAD

**Issue by ghost** [MiCode/Xiaomi_Kernel_OpenSource#1228]
When are you gonna release those damn kernel source ? sirius, grus, pyxis and vela users have enough to wait !

That's been already more 3 month since Android 10 MIUI 11 stable update was released for sirius and grus and mostly 2 month for pyxis and vela !

begonia users got android 10 MIUI 11 stable since 1 month and they have android 10 kernel source !

We want sdm710 android 10 kernel sources !

@ivan19871002 @mi-code

**Comment by EduardoSantinDev** [comment]
Where's the kernel source for pyxis and vela? We've been waiting for long enough! 
We want sdm710 android 10 kernel sources!
@mi-code

**Comment by WiZaRd981** [comment]
> When are you gonna release those damn kernel source ? sirius, grus, pyxis and vela users have enough to wait !
> 
> That's been already more 3 month since Android 10 MIUI 11 stable update was released for sirius and grus and mostly 2 month for pyxis and vela !
> 
> begonia users got android 10 MIUI 11 stable since 1 month and they have android 10 kernel source !
> 
> We want sdm710 android 10 kernel sources !
> 
> @ivan19871002 @mi-code

Sadly how we need to create issue to get through Xiaomi.. Unbelievable.

**Comment by czarsuperstar** [comment]
Please release the kernel source so we can maintain our device properly. Thank you Xiaomi

**Comment by mutlucakar** [comment]
Please release the kernel source so we can maintain our device properly. Thank you Xiaomi

**Comment by mutlucakar** [comment]
Where's the kernel source for pyxis and vela? We've been waiting for long enough!
We want sdm710 android 10 kernel sources!
@mi-code

**Comment by JaviLerma** [comment]
Release kernel source!

**Comment by 1lunzz** [comment]
Release kernel source!!!

**Comment by mizzerx** [comment]
Release Kernel Source

**Comment by Maxxtrof** [comment]
Xiaomi, you better release the source!

**Comment by qttc** [comment]
release kernel sources for sdm710 device!

**Comment by isnthzy** [comment]
Release kernel source!!!

**Comment by pokohontos** [comment]
Release kernel source!

**Comment by SergeNu** [comment]
We want sdm710 android 10 kernel sources for maintaining Mi 8 SE! Please!

**Comment by alanmk24** [comment]
We need the kernel, kernel, kernel,,,sir Xiaomi.there is a silly Bluetooth bug and its even on your fastboot global rom,if you release the kernel sources maybe someone could help solve this problem.they say change is inevitable Xiaomi, go with it,,, RELEASE THE HOUNDS SMITHERS..NO, I MEAN KERNEL, XIAOMI -MASTERS.Release the source

**Comment by vhtor** [comment]
Xiaomi, release kernel source for Pyxis!!!

**Comment by Punisher097** [comment]
Release Kernel source for Pyxis !

**Comment by zaiserr** [comment]
Pls release Android 10 kernel for any sdm710 devices (That's been already 3 month since update are stable for sdm710 Xiaomi devices) !

Redmi Note 8 Pro users got Android 10 stable update 1 month ago and they got Android 10 kernel sources 4 day ago !

**Comment by NaassomDourado** [comment]
Release Android 10 kernel for any sdm710 devices.

**Comment by cok3307788** [comment]
> When are you gonna release those damn kernel source ? sirius, grus, pyxis and vela users have enough to wait !
> 
> That's been already more 3 month since Android 10 MIUI 11 stable update was released for sirius and grus and mostly 2 month for pyxis and vela !
> 
> begonia users got android 10 MIUI 11 stable since 1 month and they have android 10 kernel source !
> 
> We want sdm710 android 10 kernel sources !
> 
> @ivan19871002 @mi-code

Are you serious?
when you try to build Android 10 kernel sources code of Begonia , you will got lots of errors that the compilation process has to be terminated.

**Comment by vd1719** [comment]
Please release Android 10 kernel source for sdm710 devices

**Comment by imansh50** [comment]
Please release Android 10 kernel source for sdm710 devices

**Comment by ha3ansol** [comment]
Please release Android 10 kernel source for sdm710 devices

**Comment by maziix72** [comment]
Please release Android 10 kernel source for sdm710 devices

**Comment by p6tr** [comment]
Please release Android 10 kernel source for sdm710 devices

**Comment by ghasem7704** [comment]
Please release Android 10 kernel source for sdm710 devices

**Comment by luk1337** [comment]
Please don't release Android 10 kernel source for sdm710 devices

**Comment by atomsand** [comment]
> Please don't release Android 10 kernel source for sdm710 devices

lol

**Comment by raphaeell** [comment]
Please release Android 10 kernel source for sdm710 devices! @mi-code

**Comment by NaassomDourado** [comment]
> Please don't release Android 10 kernel source for sdm710 devices

you ghey kkkkkkkkkkkkk

**Comment by NaassomDourado** [comment]
Please release Android 10 kernel source for sdm710 devices! @mi-code

**Comment by NaassomDourado** [comment]
@mi-code release this.

**Comment by maosilva** [comment]
Xiaomi Release the Pyxis kernel now! #ReleaseKernelPyxis #FredomForUsers

**Comment by NaassomDourado** [comment]
Xiaomi Release the Pyxis kernel now! #ReleaseKernelPyxis #FreedomForUsers

**Comment by NaassomDourado** [comment]
Pls release Android 10 kernel for any sdm710 devices (That's been already 3 month since update are stable for sdm710 Xiaomi devices) !

**Comment by alexmadureira** [comment]
Xiaomi pls release Pyxis Kernel!!! 
#ReleaseKernelPyxis #FreedomForUsers

**Comment by IsaccSaturno** [comment]
> When are you gonna release those damn kernel source ? sirius, grus, pyxis and vela users have enough to wait !
> 
> That's been already more 3 month since Android 10 MIUI 11 stable update was released for sirius and grus and mostly 2 month for pyxis and vela !
> 
> begonia users got android 10 MIUI 11 stable since 1 month and they have android 10 kernel source !
> 
> We want sdm710 android 10 kernel sources !
> 
> @ivan19871002 @mi-code

When are you going to release the damn pyxis kernel source? lack of respect with consumers, other brands make it available immediately after launch. Be careful not to lose more market for this #xiaomi

**Comment by IsaccSaturno** [comment]
When are you going to release the damn pyxis kernel source? lack of respect with consumers, other brands make it available immediately after launch. Be careful not to lose more market for this #xiaomi

**Comment by ghost** [comment]
Xiaomi, it's time to release this kernel for snap710 devices with Android 10. It's been over 3 months now and we urgently need the kernel. We can't wait any longer !!

@mi-code #ReleaseKernelPyxis

**Comment by wilson198918384** [comment]
Release kernel source!

**Comment by ELFrathos** [comment]
@mi-code Where's the kernel source for pyxis and vela? We've been waiting for long enough!
We want sdm710 android 10 kernel sources!

**Comment by alexandres-pyxis** [comment]
release kernel sources for sdm710 device!

**Comment by mathlourenco94** [comment]
Xiaomi Release the Pyxis kernel now! #ReleaseKernelPyxis #FreedomForUsers

**Comment by nullbytepl** [comment]
As if they care

**Comment by granitzheg** [comment]
Xiaomi Release the Pyxis kernel now! #ReleaseKernelPyxis #FreedomForUsers

**Comment by tauisilva** [comment]
Please release Android 10 kernel source for sdm710 devices

**Comment by tauisilva** [comment]
Xiaomi Release the Pyxis kernel now! #ReleaseKernelPyxis #FreedomForUsers

**Comment by pozhiloy-enotik** [comment]
Release kernel source!

**Comment by francixcopp30** [comment]
release the Pyxis kernel, please

**Comment by JimmyBondi** [comment]
time to release Pyxis kernel source, please

**Comment by Luigi89FG** [comment]
Please release Android 10 kernel for any sdm710 devices!

**Comment by alexamodei** [comment]
Please release android 10 kernel source for our smd710 devices @mi-code

**Comment by NaassomDourado** [comment]
Release pyxis kernel source @mi-code

**Comment by ELFrathos** [comment]
Release pyxis kernel source @mi-code

**Comment by bncassaro** [comment]
Release pyxis kernel source Snapdragon 710 and Android 10 @mi-code

**Comment by ELFrathos** [comment]
Release pyxis kernel source Snapdragon 710 and Android 10 @mi-code

**Comment by ELFrathos** [comment]
Release pyxis kernel source Snapdragon 710 and Android 10 @mi-code

**Comment by ELFrathos** [comment]
Release pyxis kernel source Snapdragon 710 and Android 10 @mi-code

**Comment by ELFrathos** [comment]
Release pyxis kernel source Snapdragon 710 and Android 10 @mi-code

**Comment by ELFrathos** [comment]
Release pyxis kernel source Snapdragon 710 and Android 10 @mi-code

**Comment by pozhiloy-enotik** [comment]
Could you please release kernel source for sirius, grus, pyxis and vela @mi-code

**Comment by bgcngm** [comment]
STOP!!!

**Comment by lapinpt** [comment]
Please unleash pyxis smd710 kernel source

**Comment by NaassomDourado** [comment]
Release @mi-code

**Comment by DobreDomitian** [comment]
Release kernel source pls @ivan19871002 @mi-code

**Comment by NaassomDourado** [comment]
Hello @mi-code ?

**Comment by pozhiloy-enotik** [comment]
@mi-code ?

**Comment by ghost** [comment]
You take your time for release our kernel source for Android 10 ;__;

kernel branch is sirius-q-oss
