### ISSUE TITLE
小米8ud 编译内核安装成功，但没声音了，wifi模块声卡模块都加载了，wifi能用，就没声音，android10的，怎么解决

### ISSUE THREAD

**Issue by xygituser** [MiCode/Xiaomi_Kernel_OpenSource#1247]
声卡驱动是android 9移植过去的，有能用的sdm845 android10 声卡驱动吗？或者说能够解决没声音的办法，

**Comment by shandongtlb** [comment]
你需要到CAF audio-kernel中导入sdm845的声音驱动并导入小米的驱动提交

**Comment by xygituser** [comment]
> 你需要到CAF audio-kernel中导入sdm845的声音驱动并导入小米的驱动提交

**Comment by xygituser** [comment]
> 你需要到CAF audio-kernel中导入sdm845的声音驱动并导入小米的驱动提交

能给个地址吗，具体怎么操作？

**Comment by shandongtlb** [comment]
https://source.codeaurora.org/quic/la/platform/vendor/opensource/audio-kernel/
找到sdm845 Android10的最新tag进行合并
