### ISSUE TITLE
Source for Redmi Note 9 Pro Global (joyeuse)

### ISSUE THREAD

**Issue by chjohn22** [MiCode/Xiaomi_Kernel_OpenSource#1265]
Could you add the kernel source code for the Redmi Note 9 Pro Global (joyeuse)?
https://www.gsmarena.com/xiaomi_redmi_note_9_pro-10217.php

**Comment by spikespaz** [comment]
According to the research that I have done the kernel for the Redmi Note 9 Pro Max should be compatible with the Redmi Note 9 Pro Global (Joyeuse). Could someone from the Xiaomi team confirm whether or not the Curtana kernel is compatible with Joyeuse?

**Comment by yudiwdynto** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/curtana-q-oss

curtana, excalibur, joyeuse, durandal & gram source kernel

**Comment by yudiwdynto** [comment]
custa_* -> curtana
custd_* -> durandal
custe_* -> excalibur
custg_* -> gram
custj_* -> joyeuse

**Comment by 1DeMaCr** [comment]
Not working on joyeuse, kernel can not start.

**Comment by xcjwq** [comment]
> custa_* -> curtana
> custd_* -> durandal
> custe_* -> excalibur
> custg_* -> gram
> custj_* -> joyeuse

how to specifically create it for Joyeuse? Is there any command?
