### ISSUE TITLE
the mi 10/10 pro  device tree is not full

### ISSUE THREAD

**Issue by cuijier** [MiCode/Xiaomi_Kernel_OpenSource#1266]
arm64/boot/dts/qcom下面只有一个kona-mtp. dts，其余相关dtsi都没有上传，项目不完整呀

**Comment by PIPIPIG233666** [comment]
https://github.com/MiCode/kernel_devicetree/blob/umi-q-oss/qcom/umi-sm8250.dtsi

**Comment by PIPIPIG233666** [comment]
这不是么

**Comment by cuijier** [comment]
> 这不是么

看到了，多谢～

**Comment by cuijier** [comment]
miss
