### ISSUE TITLE
cas-q-oss内核无法触控

### ISSUE THREAD

**Issue by nakixii** [MiCode/Xiaomi_Kernel_OpenSource#1289]
我修复了源码里的许多错误的地方，最终成功编译出了Image（抛弃了设备树）。然而，刷入设备后，即使成功启动了，但是屏幕无法响应触控。查看getevent，实际上输入触控事件的input device fts没有工作，我认为这是很严重的问题。虽然MiCode都懂，还是希望能看看issues？

**Comment by nakixii** [comment]
@ivan19871002

**Comment by 564450491** [comment]
我想问下，你是怎么绕过dtc编译的。能给个过程吗？
