### ISSUE TITLE
Begonia sources need updates, now more than ever.

### ISSUE THREAD

**Issue by sjlua** [MiCode/Xiaomi_Kernel_OpenSource#1307]
Why does...
> begonia sources need updates, now more than ever?

Well...
1. Current sources don't support the **new** front sensor, leading to irritating issues like **front cam compatibility** issues.
2. It's been a while.
3. Issues here and there.
4. Fix and release the **FULL sources** please.
5. We want **and** need them.
6. Don't hurt the community by not sharing something that could easily have been shared.
7. Why not bring back RAW for the new sensor anyways?

**Comment by bigrammy** [comment]
I will +1 this please update the source to support the newer devices that shipped with the different hardware.

**Comment by sjlua** [comment]
Ty for the r sources!
