### ISSUE TITLE
Please provide Q kernel source for Redmi Note 8/8T (ginkgo/willow)

### ISSUE THREAD

**Issue by Dialynx** [MiCode/Xiaomi_Kernel_OpenSource#1322]
Referring to the stable firmware release for these two devices, provide the Q kernel source code.

**Comment by johnmart19** [comment]
Provide Q sourses for Redmi Note 8 / 8T!

**Comment by Dialynx** [comment]
Moving to https://github.com/MiCode/Xiaomi_Kernel_OpenSource/issues/1332
