### ISSUE TITLE
Please release the kernel source code for Poco X3/NFC.

### ISSUE THREAD

**Issue by thorxone** [MiCode/Xiaomi_Kernel_OpenSource#1331]

**Comment by vsnthdev** [comment]
Also, allow unlocking the bootloader for Poco X3 "karna" as it is currently not working.

**Comment by UBREVO** [comment]
Please release the kernel source code already, you have stated that you would do so upon the launch of this device and failed to deliver your promise to the Poco X3 community. This device has a lot of potential, all we need now is the kernel source and we're good to go. Please make this happen, thank you.

**Comment by mosouab** [comment]
yeah, please release the kernel asap.

**Comment by marines** [comment]
It's not even `month one` anymore.

**Comment by vsnthdev** [comment]
will they even release it? 🤔

**Comment by deviant77** [comment]
From the official POCO X3 NFC Global Launch Event:
![image](https://user-images.githubusercontent.com/16081842/97779372-7dc33200-1b75-11eb-9681-4a3d4ea8addc.png)
![image](https://user-images.githubusercontent.com/16081842/97779375-8582d680-1b75-11eb-9b36-e0842573b5e9.png)

**Comment by UBREVO** [comment]
> From the official POCO X3 NFC Global Launch Event:
> ![image](https://user-images.githubusercontent.com/16081842/97779372-7dc33200-1b75-11eb-9681-4a3d4ea8addc.png)
> ![image](https://user-images.githubusercontent.com/16081842/97779375-8582d680-1b75-11eb-9b36-e0842573b5e9.png)

Xiaomi you posted these images, why state something you weren't going to do in the first place, unless your intentions were to post on launch date and something happened which prevented you guys to upload, then you can at least give the people who are waiting a heads up? This is unacceptable, what you're doing. You're toying with those who are waiting, all we want is a heads up, that you will deliver your promise.

**Comment by NotesOfReality** [comment]
**"Poco X3/NFC kernel sourcecode release"** waiting room
![image](https://user-images.githubusercontent.com/11523796/97906794-8ddd3c00-1d44-11eb-8536-0c2003444f4a.png)

**Comment by NotesOfReality** [comment]
It's not like we already haven't asked for the kernel sourcecode #1309 or we aren't still asking for it #1334 btw

**Comment by UBREVO** [comment]
> It's not like we already haven't asked for the kernel sourcecode #1309 or we aren't still asking for it #1334 btw

At least some of us are making the effort of requesting for the sources. I've looked around and you did not request or even bothered stating your reasons as to why they should release source code. Xiaomi stated they would release upon launch, they failed to deliver their promise. It's not like there's hundreds of issues being opened, there's only 3. If you look elsewhere, you'll see Mi 10 Lite kernel sources, there are more requests over there than here, so obviously our issues need to be above theirs. Just keep in mind that Xiaomi made a statement for Poco X3 and they need to deliver it. 

Edit: It's also one of the main reasons why I purchased this device, because they stated they would release kernel sources upon launch. What's not to love when they say that? Poco X3 has huge potential, it's already good as it is, but if we have the sources, just imagine how much of a beast this device can actually become.

**Comment by ZjemCiKolege** [comment]
maybe in the coming months we will see sources for the Mi10T apollo :) or poco x3

**Comment by UBREVO** [comment]
> maybe in the coming months we will see sources for the Mi10T apollo :) or poco x3

I hope so, going to start baking a kernel asap the moment it's released 💯

**Comment by vsnthdev** [comment]
Also, they still didn't release 🙄 the stock ROM for Poco X3 karna yet.

**Comment by NotesOfReality** [comment]
> 
> 
> > It's not like we already haven't asked for the kernel sourcecode #1309 or we aren't still asking for it #1334 btw
> 
> At least some of us are making the effort of requesting for the sources. I've looked around and you did not request or even bothered stating your reasons as to why they should release source code. Xiaomi stated they would release upon launch, they failed to deliver their promise. It's not like there's hundreds of issues being opened, there's only 3. If you look elsewhere, you'll see Mi 10 Lite kernel sources, there are more requests over there than here, so obviously our issues need to be above theirs. Just keep in mind that Xiaomi made a statement for Poco X3 and they need to deliver it.
> 
> Edit: It's also one of the main reasons why I purchased this device, because they stated they would release kernel sources upon launch. What's not to love when they say that? Poco X3 has huge potential, it's already good as it is, but if we have the sources, just imagine how much of a beast this device can actually become.

My bad @UBREVO  , i didn't mean to disincentivize anyone, it was a way to express my disappointment towards Poco/whoever manages this repo since they should have OSSed the kernel since almost 2 months ago according to their promises, and I think a month and a half is quite enough of a "tolerance" waiting time.
I never happened to bother with making issues in Xiaomi Kernel OSS repo cause everytime I unlocked a Xiaomi device the kernel already was OSSed, hence I didn't exactly know how to move.
I honestly think too Poco X3 has great potential btw.
I'll open an issue within the weekend.

**Comment by UBREVO** [comment]
> > > It's not like we already haven't asked for the kernel sourcecode #1309 or we aren't still asking for it #1334 btw
> > 
> > 
> > At least some of us are making the effort of requesting for the sources. I've looked around and you did not request or even bothered stating your reasons as to why they should release source code. Xiaomi stated they would release upon launch, they failed to deliver their promise. It's not like there's hundreds of issues being opened, there's only 3. If you look elsewhere, you'll see Mi 10 Lite kernel sources, there are more requests over there than here, so obviously our issues need to be above theirs. Just keep in mind that Xiaomi made a statement for Poco X3 and they need to deliver it.
> > Edit: It's also one of the main reasons why I purchased this device, because they stated they would release kernel sources upon launch. What's not to love when they say that? Poco X3 has huge potential, it's already good as it is, but if we have the sources, just imagine how much of a beast this device can actually become.
> 
> My bad @UBREVO , i didn't mean to disincentivize anyone, it was a way to express my disappointment towards Poco/whoever manages this repo since they should have OSSed the kernel since almost 2 months ago according to their promises, and I think a month and a half is quite enough of a "tolerance" waiting time.
> I never happened to bother with making issues in Xiaomi Kernel OSS repo cause everytime I unlocked a Xiaomi device the kernel already was OSSed, hence I didn't exactly know how to move.
> I honestly think too Poco X3 has great potential btw.
> I'll open an issue within the weekend.

Let's just pray that they release it this month, I'm more than willing to wait it out this month - just eager to make a custom kernel already. Honestly, the day they release the sources for this device, is the day I'll be excited 😂

**Comment by mizuhashikuniumi** [comment]
Up

**Comment by catfluoride** [comment]
As a new Poco X3 user, I'd love kernel source to be released.
Thanks!

**Comment by cientista** [comment]
Another user here who choose this phone over others not just because of the specs but, because of the promise of kernel sources at launch. I decided for this one when I watched the POCO presentation and saw the images posted above.

**Comment by vladi-it** [comment]
I m waiting for you :-)

**Comment by mizuhashikuniumi** [comment]
Up

**Comment by akash07k** [comment]
Just release the sources Xiaomi.
It's really strange and weird that you guys didn't bothered to release the kernel sources even after more than 2 months of device release.

**Comment by drumed** [comment]
Please release the kernel source code for Poco X3/NFC.

**Comment by drumed** [comment]
Pls Release the Kraken

**Comment by mizuhashikuniumi** [comment]
Yp

**Comment by mizuhashikuniumi** [comment]
Up

**Comment by mizuhashikuniumi** [comment]
Breake promise Will get karma

**Comment by akza07** [comment]
This is the Karma for getting POCO X3 and believing Xiaomi's words.

**Comment by drumed** [comment]
Xiaomi, keep your words

**Comment by mizuhashikuniumi** [comment]
Alr released lmao

**Comment by NotesOfReality** [comment]
> Alr released lmao

More like : "just" released

**Comment by drumed** [comment]
Yeahhhhhhhhh, Thanks Xiaomi/Poco

**Comment by thorxone** [comment]
Released
