### ISSUE TITLE
Poco X3 Kernel Source (Request)

### ISSUE THREAD

**Issue by UBREVO** [MiCode/Xiaomi_Kernel_OpenSource#1334]
Xiaomi, I understand that you're a very busy company, but who is in charge of viewing MiCode GitHub issues? You have stated that you would release kernel source code upon the launch of this device, yet you have failed to deliver that promise. It has been more than a month and we are patiently waiting. Whoever is in charge of viewing these issues and if you're looking at this issue, please just release the source code already. Thank you for your time.

**Comment by catfluoride** [comment]
+1
