### ISSUE TITLE
[REQUEST] Xiaomi Mi Note 10 Lite (Toco) Kernel Source Code

### ISSUE THREAD

**Issue by DQuest** [MiCode/Xiaomi_Kernel_OpenSource#1356]
And again... [GPLv2 and Its Infringement by Xiaomi](https://www.xda-developers.com/gplv2-and-its-infringement-by-xiaomi/)

**Comment by DQuest** [comment]
Devs can't fix FOD (Fingerprint On Display) because of you...

**Comment by yggdrasil31** [comment]
Devs really needs Xiaomi to release the kernel source code for mi note 10 lite
