### ISSUE TITLE
XIAOMI MI NOTE 10 LITE [TOCO] KERNEL CODES

### ISSUE THREAD

**Issue by iizmotabar** [MiCode/Xiaomi_Kernel_OpenSource#1365]
Hi Xiaomi Team,
 You have been doing a wonderful job with all your devices. Releasing Kernel Codes after the release but that didn't happen with the Mi Note 10 Lite (Toco). Kindly release the Mi Note 10 Lite Kernel Codes. We need those for further development! 

Hoping to get a positive response from you.

**Comment by Vadxa** [comment]
Да без полезно просить код,его не будет уже,эти падлы пропускают этот девайс.Я писал раз 10 уже и толку 0
