### ISSUE TITLE
需求Redmi note 9 PRO GAUGUIN 的内核源码。

### ISSUE THREAD

**Issue by zixijian** [MiCode/Xiaomi_Kernel_OpenSource#1366]
__以后系统没做好我觉得没必要发布了，  
源码跟手机发售最好同步开放。__

不知道能不能有小米的研发看不看得到，一个实时网速不准的bug半年了都不修复，别的也不能指望了。

**Comment by HyperLYP** [comment]
实时网速在连接VPN的时候会不准，貌似都是这样的。但是别的时候应该是准的。

**Comment by zixijian** [comment]
> 实时网速在连接VPN的时候会不准，貌似都是这样的。但是别的时候应该是准的。

半年以前就是正常的，更何况不仅是vpn，samba、otg好多场景都有速度异常。
