### ISSUE TITLE
[LEGAL][COPYRIGHT INFRINGEMENT] Comply to terms of GNU GPLv2 License, release Mi Pad's Linux© kernel source code!／遵从 GNU GPLv2 授权条款的规定，释出小米平板的 Linux© 作业系统内核来源代码！／遵從 GNU GPL 第 2 版授權條款的規定，釋出小米平板的 Linux© 作業系統核心來源程式碼！ #解放小米 #LibreXiaoMi

### ISSUE THREAD

**Issue by Vdragon** [MiCode/Xiaomi_Kernel_OpenSource#18]
### English version

Dear @MiCode, hehao hehao@xiaomi.com, Hugo Barra and XiaoMi corp., 

Linux© kernel is a copyrighted software written by Linus Torvalds(@torvalds) et al. and is released under the GNU GPLv2 license.  According to licensing terms distributor of derived work of Linux kernel must provide modified Linux© source code along with the distribution of the software.  Since "Mi Pad", your product uses Linux© kernel and is distributed to the public XiaoMi corp. must comply to requirement of GNU GPLv2 License and release Mi Pad's Linux© kernel source code.

**Not complying to the copyrighted property's license is COPYRIGHT INFRINGEMENT!**

Seriously, your Mi Pad customer.
### 简体中文（中国大陆地区）版本<br />Chinese(Simplified)(China) version

Linux© 作业系统内核是由 @torvalds 等人设计的一个享有智慧财产权的软件并其被已 GNU GPL 第 2 版授权条款释出。根据授权条款规定基于 Linux© 作业系统内核的衍伸作品的散布者必需伴随其散布的软件提供被修改的 Linux© 作业系统核心来源代码。既然小米平板使用了 Linux© 作业系统内核且已被散布至公开场合 @MiCode 必须尊从 GNU GPL 第 2 版授权条款的规定释出小米平板的 Linux© 作业系统核心来源代码。

**违反智慧财产授权条款即为侵权行为！**
### 正體中文（台灣地區）版本<br />Chinese(Traditional)(Taiwan) version

致 MiCode 社區（@MiCode 於 [GitHub](http://github.com)）、hehao <hehao@xiaomi.com>（有 [Xiaomi_Kernel_OpenSource 版本倉庫](https://github.com/MiCode/Xiaomi_Kernel_OpenSource)寫入權限的小米科技成員）、Hugo Barra（小米科技全球副總裁）、雷軍 &lt;http://www.leijun.com/ &gt;（小米科技創始人、董事長兼執行長）以及小米科技公司 &lt;http://www.xiaomi.cn/ &gt;：

[Linux© 作業系統核心](https://www.kernel.org/)是由 Linus Torvalds(@torvalds) 等人設計的，以 [GNU GPL 第 2 版授權條款](https://www.gnu.org/licenses/gpl-2.0.html)釋出的智慧財產。根據 [GNU GPL 第 2 版授權條款](https://www.gnu.org/licenses/gpl-2.0.html)要求基於 [Linux© 作業系統核心](https://www.kernel.org/)的衍伸作品的散佈者必需伴隨衍伸作品提供被修改的 [Linux© 作業系統核心](https://www.kernel.org/)來源程式碼。既然貴公司的產品「小米平板」使用了 [Linux© 作業系統核心](https://www.kernel.org/)且已被散佈至公開場合貴公司必須尊從 [GNU GPL 第 2 版授權條款](https://www.gnu.org/licenses/gpl-2.0.html)的要求釋出「小米平板」的 [Linux© 作業系統核心](https://www.kernel.org/)來源程式碼。

**違反智慧財產授權條款為侵權行為！**

嚴肅地，「小米平板」顧客敬上。

**Comment by Vdragon** [comment]
Hi everyone concerning with this issue, please contribute other languages title(& issue summary also) so we can get more attention from @MiCode ;)

**Comment by omarhasan95** [comment]
Provide us with mipad kernel sources

**Comment by vartom** [comment]
Agreed. Provide us with mipad kernel sources.

**Comment by mikoda** [comment]
totally agree

**Comment by TheShinobi** [comment]
Yes, release the kernel sources for the Xiaomi Mipad!

**Comment by omarhasan95** [comment]
Why there is no reply from mi???

**Comment by abhiyoyo** [comment]
Yes they must provide kernel sources of Mipad keeping in mind of customer interest if they can make only half baked miui ROM then give sources many talanted devs will make stable Roms . Keep your image clean your biggest con is closed source . that why you were denied place in Xda forum . Its good to see many Mi mobiles got sources in recent times . But why not Mipad . if its something nvidia does not want you to give or what ?? Please just be cleat why its not possible or when its possible . Your silence on this issue is hurting more than unavailability of sources . we are still not sure whether we are banging our head needlessly or at wrong place

**Comment by Doraha-Raman** [comment]
yes , they should have already released kernels

**Comment by KinG5Pac** [comment]
I don't think they will care about this. Same scenario was on mi3. And @Hugo again lied about kernel release , I'm about 3 month kernel release fro all devices.

**Comment by abhiyoyo** [comment]
but @KinG5Pac  but they released sources for mi3 eventually

**Comment by KinG5Pac** [comment]
@abhiyoyo 2-3 years old phone. And u say it released ?

**Comment by abhiyoyo** [comment]
Yes

**Comment by co11ider** [comment]
Yes. Dont make me regret buying a mipad and will never ever buy a Xiaomi product again. Also I'm suspecting you guys must have hidden some dirty secret inside it, like the Indian government warned.

**Comment by Juanmiwow** [comment]
We need kernel source! PLEASE, provide us the MiPad kernel source!

**Comment by sharifsonic** [comment]
YEAH GUYS, Dont defame your self.
I used to be a great MI fan..
I'm losing it now!!
Release the mipad kernel.

**Comment by ankurs** [comment]
+1

**Comment by liuguo09** [comment]
We will, but i can't give you an accurate time

**Comment by Vdragon** [comment]
@liuguo09 What about your _will_ on issue #4 ?

**Comment by abhiyoyo** [comment]
ok sir thanks for reply @liuguo09  sir atleast an eta ?? will we get within 1 month ??

**Comment by ghost** [comment]
He said that he can't give you a time.. If you work in software development you should understand how useless ETAs are

**Comment by abhiyoyo** [comment]
@stefant234 chill he said exact time not eta Sir !!!!!! I am not putting gun and asking forcibly he will reply if he wants you don't jump in between please

**Comment by omarhasan95** [comment]
Only sources matter to us please provide us asap we dont need eta

**Comment by abhiyoyo** [comment]
@omarhasan95 hope so but I know it takes lil time but don't know 1 month should be enough again I don't work in software development so no exact idea but redmi 1s and note 4g can get quick so hope Mipad will be quick

**Comment by ghost** [comment]
I am relaxed. Just out of curiosity, who of you do kernel development? Bombarding the poor man won't help anyone and won't change company policy. I'm also not saying that you force anyone, I just tell you that any ETA in software development is not to be trusted, because in 99.9% of the time, they can't be held. Thats what I meant. Since thus is public I can jump in as I please ;)

**Comment by abhiyoyo** [comment]
OK jump hehe but its not bombarding lol its user requests @stefant234 and poor man ?? Lol we just asking not throwing grenades haha

**Comment by ghost** [comment]
Imagine being in his position. Xiaomi sent him to maintain their Github and now a few doyen people see him as the personification of GPL violations :D Anyways, this sourcecode's state is why I abandoned Xiaomi and going to stick with Samsung for a while. At least they provide the sourcecode for every firmware update :)

**Comment by abhiyoyo** [comment]
Man @stefant234 people are not targeting him they target xiaomi only and yes its GPL violation and this is the page we really can ask about sources lol who even said he violated this post was about xiaomi :D users don't see who is maintaining the page they just see its kernel source page and ask their query :p  if anyone said tagging him that he violated anything that's dumbness bro :p

**Comment by ghost** [comment]
I think our problem is English, you apparently don't fully get me while I don't fully get you either :D

**Comment by abhiyoyo** [comment]
Ok hehe

**Comment by COI3RA** [comment]
Please release Mipad's Kernel Source code

**Comment by museroom** [comment]
A China style riot is required for a China company to listen to their customers.

**Comment by omarhasan95** [comment]
Release the sources asap its more than one year...... Before lauching new devices everymonth please take care of your pre released devices

**Comment by villarhdez** [comment]
Por favor, no hagan que me arrepienta de haber comprado mi primer dispositivo Xiaomi y liveren el kernel. No les cuesta nada, solo haganlo o al menos desarrollen una ROM lo suficientemente estable para la Mipad

**Comment by ghost** [comment]
I join the request, +1

**Comment by ghost** [comment]
I'm really disappointed. I don't think I'm gonna buy another Xiaomi device after I'm done with my Mi Pad. At least not until the kernel sources are released. So please release Mipad's Kernel Source code soon.

**Comment by TrickNL** [comment]
Xiaomi please release the kernel source files so we al can get creative and start creating roms to get the most out of our Mi pad. Thank you in advance 😁

Motivate you're customers so in the future they buy more Xiaomi devices. Surely you want this and not the other way around. The device is a year old now and we have been suffering with your unoptimized Mi ui rom.

**Comment by akb1** [comment]
Thats how they do it. Welcome to China brothers. If it is in their favour they will release it or you forget about it. They don't give a damn about copyright or anybody's rights. But then again, if they don't they underestimate its consequences for their company.  Release the Kernel.

**Comment by LordHexd** [comment]
This may be mainly for the MiPad but as a new Mi4i user who bought into the hype of a great device at great price, I too am eagerly waiting for the kernel release for the device. I just can not use MIUI for the bloat and only 16GB of storage available. Fix this and I may have reasons to buy more of Mi/Yu products. As of now I'm very happy with the MiBand and bought 7 for my friends and family as I wanted them to feel the joy of owning a product as well built and functional as it is. MiPowerBanks are just as good and the quality and function meets the standard I expect from the product. Unfortunately my latest purchase has me second guessing whether the Mi team thought through the full scope when designing the phone itself and the ever so bloated MIUI.

**Comment by doomboss** [comment]
I know the developer from Xiaomi are very busy, but please just release the kernel source! I really hope there will be more development and the Mipad definitely has more potential if you guys can let outside developers to work on their custom ROM with the kernel source!

**Comment by jockiller** [comment]
快来放源码吧…不开放你就给我们正了八经的开发MIUI

**Comment by attenzione** [comment]
+1

**Comment by gizeasy** [comment]
+1

**Comment by skr4tchGr3azyMonkiBallllllZzzz** [comment]
Lets get together and sue Xiaomi for violating GPL.

**Comment by skr4tchGr3azyMonkiBallllllZzzz** [comment]
MIUI on MIPAD SUCKS BALLz!!!

**Comment by skr4tchGr3azyMonkiBallllllZzzz** [comment]
Boycott MiPad NOW!

**Comment by pritm** [comment]
+1

**Comment by catinred2** [comment]
+1

**Comment by kirill0v** [comment]
Give us at least some decent reply with status or a legitimate reason for not releasing it! 

Guys sign this if you haven't already, a petition asking to release kernel source: https://goo.gl/6xbZoY

**Comment by rooque** [comment]
Support the cause here http://en.miui.com/forum.php?mod=viewthread&tid=136345

**Comment by d3m3vilurr** [comment]
@liuguo09 can you share any news?

**Comment by DGideas** [comment]
+1

**Comment by moonges** [comment]
Guys please! we need Mi Pad's Linux© kernel source code!

**Comment by raftaarsingh** [comment]
plz provide us with kernel source code of mi pad its enough time than expected

**Comment by abhiyoyo** [comment]
@liuguo09  please man its enough time please release sources for betterment of mipad itself

**Comment by Juanmiwow** [comment]
Xiaomi, release the kernel sourde now! We need it!

**Comment by jza70** [comment]
Release the sources and get rid of spyware. You are violating the license.

**Comment by Yrahate7** [comment]
Enough of this s###. Xiaomi isn't even updating the device to miui7 and neither are they releasing source codes... 
If this continues then I will shift over to the developer friendly nexus 9.
Expensive  yet worth it. 
Better release the codes for sake of 50000 MI pad users
Anyways you are violating gpl v2. 
Better to release source than getting into law suits

**Comment by sandipCS** [comment]
release the kernel source please...we need it.

**Comment by Ash-Drake** [comment]
please release the kernel sources xiaomi, we need it, we only get mostly unstable rom from mi, we users deserve better experience, and you know it, please don't make it harder for us to survive in this device. please release the sources soon for you to make it up for giving us such an incredible hardware

**Comment by Vdragon** [comment]
### UPDATE<br />更新
- Remove the politeness part from the title as this is not _just_ a friendly request.
- Add some tags that make the issue more **serious** and hopefully, alert someone that works in XiaoMi's LEGAL department(If there's really one, of course)

**Comment by skr4tchGr3azyMonkiBallllllZzzz** [comment]
I'm willing to fund a campaign to sue Xiaomi in China. What legal actions can be taken?

**Comment by abhiyoyo** [comment]
Thanks for effort @skr4tchGr3azyMonkiBallllllZzzz  they will learn a lesson

**Comment by Vdragon** [comment]
@skr4tchGr3azyMonkiBallllllZzzz You'll need to have someone holding Linux kernel's copyright to sue XiaoMi, this means someone that previously committed their code into Linux kernel before XiaoMi uses it as MiPad's kernel.

**Comment by tranphungan** [comment]
Still waiting for Kernel release, thank for releasing asap

**Comment by d3m3vilurr** [comment]
ok, few hours ago, armani-kk kernel pushed. (#10) but mipad and other devices's kernel still missing. boo....
@liuguo09 r u there?

**Comment by abhiyoyo** [comment]
Yes Mipad should also get it it has been long wait   @liuguo09  you told long ago sources for Mipad will be released I think time has come make Mipad users happy as you did for armani

**Comment by omarhasan95** [comment]
Its enough time you got more than a year have some sense now and release the sources if you dont want more trouble and i guess from the best it's will get worst (pun intended )

**Comment by git-rbanerjee** [comment]
#27

**Comment by niclimcy** [comment]
http://www.xda-developers.com/gplv2-and-its-infringement-by-xiaomi/

**Comment by vincevega** [comment]
give kernel source !!!!

**Comment by wonson** [comment]
Yes, please

**Comment by d3m3vilurr** [comment]
xiaomi's stance is very weird. they think `product's kernel source open make risk of next models`.
but, other device manufacturers like samsung and lge always open their device's kernel.
http://opensource.samsung.com
http://opensource.lge.com

**Comment by niclimcy** [comment]
@d3m3vilurr You have to take note that samsung deprecates their exynos processors kernel. Super brick :)

**Comment by d3m3vilurr** [comment]
@nick37332001 i don't know that, can share information? they still open [exynos kernel code](https://github.com/slayher/android_kernel_samsung_zerofltetmo/tree/master/arch/arm64/mach-exynos).
and /arch/arm/mach-exynos [still maintains](https://git.kernel.org/cgit/linux/kernel/git/kgene/linux-samsung.git/log/arch/arm/mach-exynos?h=for-next).

**Comment by niclimcy** [comment]
@d3m3vilurr http://www.xda-developers.com/samsung-exynos-and-aosp-explained-a-story-of-betrayal/
Luckily at that time I bought an ace 2 instead even though it had a novathor processor

**Comment by d3m3vilurr** [comment]
@nick37332001 ok. i readed that post. but just in my opinion, it is just risk about rooting. scene still can build and develop last android system. basically it need a kernel code.
GPL require responsibility about open GPL based code, not require care of code.

**Comment by niclimcy** [comment]
@d3m3vilurr both sides of it are needed in order to have a stable system. Why release a kernel when you have to do more work to fix it. Just saying that Xiaomi should make their development even more public/open for the devices that they release the kernel for and open up kernel for everything and not just hide everything from drivers to optimization configs on their system.

**Comment by d3m3vilurr** [comment]
@nick37332001 xiaomi must open source code. it is gpl problem. but they also cannot open non gpl codes(like non gpl device module). it's little difference. anyway, you are correct, stable system need both side and vendor can help to this. but sadly, opensource scene always problem fix themselves that case.
but, we cannot talk about this yet. because xiaomi not opened anything.

my comment about samsung and lte is just about why xiaomi is sh*t.
honestly, i don't know why we talk about samsung's problem on this place. :)
so, if you want talk about this. please send personal email to me. d3m3vilurr at gmail dot com :)

**Comment by niclimcy** [comment]
Almost all device modules for xiaomi phones are opensource and therefore we have a fully working unofficial kernel here https://github.com/zwliew/android_kernel_xiaomi_msm8916 and here https://github.com/kumajaya/android_kernel_cyanogen_msm8916 . Its about xiaomi not being ethical on releasing them. They should release mediatek sources too but then again they might want to keep the source close as money is needed to get mediatek's sources which is ridiculous in it self

**Comment by omarhasan95** [comment]
Then why don't they release tegra k1 sources i don't think it has got any
restrictions

**Comment by niclimcy** [comment]
@omarhasan95 that's my point. This shows xiaomi being unethical.

**Comment by omarhasan95** [comment]
Ya first of all they are not releasing the sources even on that they are
providing worst software support not even a proper lollipop update in the
generation or marshmallows we are living with kitkat......for me its like
they released a dragon with the heart of a mouse

**Comment by rtsui-harmonicinc** [comment]
What the fuck did I do to buy a mi phone

**Comment by omarhasan95** [comment]
@liuguo09  Where are the sources liuguo ???

**Comment by ghost** [comment]
Release the source code for Redmi 2

**Comment by yeokesh** [comment]
@liuguo09 it has been six months since u promised to release mipad kernel sources... Still nothing released. And u are too busy to give us a reply. Say whether u ppl can release or not. We are one step away from switching over to a costumer friendly oem.

**Comment by yeokesh** [comment]
@liuguo09 where s de mipad kernel man?

**Comment by yeokesh** [comment]
@liuguo09   can't u reply?

**Comment by yeokesh** [comment]
@abhiyoyo can't we do anything about mipad kernel ?

**Comment by abhiyoyo** [comment]
@yeokesh either we can drag them into cort or wait for mipad 2 release so that mipad sources are released

**Comment by cuteprince** [comment]
Is it possible to port nvidia shield tablet kernel source to mipad since they have the same SoC ?

**Comment by cuteprince** [comment]
Now that the Mi Pad 2 is released, Xiaomi please release the kernel source code of Mi Pad for God's sake.

**Comment by yeokesh** [comment]
Is @liuguo09 still the mi official here ? Bcoz he neither replies nor does wat he say... (Mipad kernel )

**Comment by yeokesh** [comment]
Atleast they should release the kernel now bcoz mipad2 is out. Miui stutters even with nvidia k1. Think of mipad2 condition with intel. Lol

**Comment by cuteprince** [comment]
^ it would be pathetic. the atom x5 z8500 is already known for overheating and thermal throttling

**Comment by yeokesh** [comment]
Only enjoyable thing with mipad is gaming. We got Atleast that. Mipad2 will surely lack that one too..

**Comment by omarhasan95** [comment]
Mipad 2 is a mere fail in harware except of light weight and metal design so now please provide  source code for mipad 1  and keep off with your crappy hardware

**Comment by virajmalia-zz** [comment]
Well, it was 28th May when we received a reply from Mi team member and that too with no useful information. It is time that Mi team release the kernel source. If not we users possess the power to restrict the sale of Mi devices or at least defame the brand for such copyright infringement so that buyers think twice before purchasing Mi products. With so many tech blogs out there, we can literally expose the truth and spread it like wild fire across the media. It is a shame that Xiaomi does not support development activities of its flagship tablet which is one of the best out there. It is a request to Xiaomi and Mi Pad developers team to release the sources as soon as possible. The next reply should contain a specific month of release or we users and developers will not hold back anymore.
Edit: #ReleaseMiPadKernel
I like that tag! @yeokesh

**Comment by yeokesh** [comment]
how easily can we make our request reach the mi officials ? 
those fellows(@hbarra, @manukumarjain) don't bother to reply in twitter.

**Comment by yeokesh** [comment]
something like trending help ? #ReleaseMiPadKernel

**Comment by antonkai2k** [comment]
+1
Already bought MiPad and Mi4c, but if Xiaomi won't release kernel, I'll never buy anything from them.
I only see reason like spyware or kind of that  :disappointed_relieved:

**Comment by yeokesh** [comment]
Time to dump mi products. I m gonna give mipad for free to my relative

**Comment by yeokesh** [comment]
These guys will neither release kernel nor give efficient miui rom.

**Comment by Neraeh** [comment]
If Xiaomi don't release their kernel sources, tribunals will do it. Yes, I'm serious.

**Comment by git-rbanerjee** [comment]
@ivan19871002 please release Redmi Note kernel sources, we are waiting for more than an year .

Anyone having Linux kernel commit, please Sue Xiaomi.

**Comment by s-prateek** [comment]
Please release mi pad kernel source immediately.

**Comment by mollywoodnini** [comment]
Please release the kernel sources asap!

**Comment by bijindas** [comment]
Please release kernel sources for the Xiaomi Mipad!

**Comment by aerfob70** [comment]
Xiaomi, release the kernel source for the Mipad please!!!!

**Comment by onestep** [comment]
Hello Xiaomi,

Could you please explain, what stops you from releasing MiPad kernel sources? At first I thought that there are some license reasons because of NVIDIA proprietary code, but as long as sources for NVIDIA Shield and Nexus 9 are released, this seems wrong.

Why don't you just upload the sources to GitHub, like you've done for Mi4 and others?
Please provide at least a reason and ETA.

Thanks.

**Comment by dramolprakash** [comment]
Dear Xiaomi , why are you not releasing the krenel source for Mi pad. Please release it soon. Your customers are running out of patience . if you don't release soon next time there is a release in India of you product outside of auditorium , we will be there with banners to protest against your attitude.

**Comment by geminikrishna** [comment]
XIAOMI PLEASE RELEASE KERNELS FOR MI PAD OR ELSE SAY WHETHER YOU WILL RELEASE IT OR NOT PLEASE RELEASE KERNELS FOR MI PAD OR UPDATE IT TO MARSHMALLOW

**Comment by omarhasan95** [comment]
Why the hell you are not releasing the sourcs code i think the soft ware devs at mipad sucks

**Comment by omarhasan95** [comment]
Jockey mokey lokey just give me sourcy

**Comment by pikoro113** [comment]
Please release kernel sources for the Xiaomi Mipad!!!!!!!!!!!!!!!!

**Comment by cthulhu1990** [comment]
Realy,there are many tallants in the world and Russia ,who can made perfect custom roms! Can you please tell us,what problem? We want kernel sources for our favouritr MIpad

**Comment by skrvil** [comment]
Why are there no millet note standard CM13 package? Does anyone make a?

**Comment by Nihhaar** [comment]
Fucking Xiaomi, release Mi Pad kernel Sources.

**Comment by tmaone** [comment]
http://gpl-violations.org/

**Comment by steom** [comment]
It' s time for MiPad kernel sources?

**Comment by MrIQZero** [comment]
cmon guys the device is already at its shelf life, Its downright stupid to not release the kernal source code  for people who wants better custom ROM for there tablet. You guys are just ruining a great piece of hardware for god knows what reason and the thing is no one wants to even acknowledge this shit. At least talk to your customers and try to sort this shit out.

**Comment by b3belov** [comment]
This kind relationship of Xiaomi to the users makes me sad.
For porting kernel from Shield Tablet we need next sources:
- Sound rt5671
- Touch Panel LQ079L1SX01(sharp) Controller nt35523 dualmipi

Give them to us please! I really expect You will hear me!

**Comment by ohjames** [comment]
I will never buy another Xiaomi product until they stop violating the GPL.

**Comment by gyuyeol** [comment]
Release kernel source code for mi pad. there is no reason to refuse this.

**Comment by z88a** [comment]
Dont make me regret buying a mipad and will never ever buy a Xiaomi product again.
请不要让我后悔购买小米平板，希望小米不要让我失望😞。

**Comment by gyuyeol** [comment]
Do what you had to long time ago.

**Comment by 389abhaysingh** [comment]
Xiaomi its high time , you are killing a device  , Mipad has the potential to beat any of tablets out there even nexus 9 and shield k1 but you people , m kinda sad  i bught my mipad with lots of hope and expectations but now its all over😢

**Comment by HoaLNB** [comment]
Xiaomi has just released the Mi Pad's source code. This time for real, finally!
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/mocha-kk-oss

**Comment by 389abhaysingh** [comment]
Thanks a lot it will help us in building more useful ROMs

**Comment by kdunning** [comment]
To add this this, @hehao, please can you provide details as to when the kernel will be available for the latest Xiaomi products, including the Mi Note 2 and the Mi 5s/Mi 5s Plus.

**Comment by insidewhy** [comment]
It's a shame Xiaomi are GPL violators. My next phone would be a Xiaomi phone if they would clean up their act. As things stand I won't buy a phone from people who steal IP.

**Comment by AntonyLeons** [comment]
They should release all kernel sources, this does not damage you operations! This helps your image.

**Comment by lzto** [comment]
guys, i am joining you requesting source code for mibox2.
it sucks that the source code is not released.

**Comment by ghost** [comment]
I'm joining this for Redmi 4X
Such as d*****s @hehao always delaying Kernel Source and never hear us. They always act like they don't care wtf. If you always act like this @hehao my next phone wouldn't be Xiaomi again. Waiting is hurts

**Comment by luk1337** [comment]
haha reeeeeeeeeeeeeeee

**Comment by julian-alarcon** [comment]
By the way, the are didn't release the kernel source for Xiami Mi A1 an Android One phone!
http://www.androidpolice.com/2018/01/16/xiaomi-still-hasnt-released-kernel-sources-mi-a1/
https://arstechnica.com/gadgets/2018/01/xiaomi-is-dragging-its-feet-on-the-gpl-again-this-time-with-the-mi-a1/

**Comment by ghost** [comment]
Spamming bish

**Comment by Vdragon** [comment]
Hello for everyone who have followed this issue, as the kernel source of Mi Pad(mocha) has been released by @hehao this issue will be closed by now.

Xiaomi, Inc. spent more than 16 months(calculated from this issue's creation date to the release commit, and even more since the product release date) to release the kernel source, which is far from acceptable from the expectation from the product users, third-party developers and the original kernel developers.  They can do better.

Lastly, thanks for everyone here fighting for the software freedom, hope you can have a much successful outcome than this one.

**Comment by dineshdb** [comment]
Hello everyone, I am Redme 4A user and would like kernel sources for it. Is it already released? Made a huge mistake buying a Xiaomi smartphone. Would start turning off other users off unless it gets released soon!

**Comment by dineshdb** [comment]
Found this issue #825

**Comment by denzuko** [comment]
http://gpl-violations.org/ gallor for this company. Hopefully anon doesn't get wind of this

**Comment by dineshdb** [comment]
@denzuko  Is there something we can do about GPL violations as a user? Like reporting to FSF or something similar? I don't like sitting here doing nothing. Petitions are good but there could be better options.

**Comment by Vdragon** [comment]
@dineshdb It should be possible to start a crowd-funding for the legal cost of GPL software copyright holders suing the violators.
