### ISSUE TITLE
Please release Redmi 2 HM2014811 and others kernel source

### ISSUE THREAD

**Issue by zwliew** [MiCode/Xiaomi_Kernel_OpenSource#21]

**Comment by zwliew** [comment]
Closing this since it is a duplicate of https://github.com/MiCode/Xiaomi_Kernel_OpenSource/issues/22.

Please release the kernel source code for Redmi 2, Xiaomi! Mi 4i had it released much earlier despite the phone being released much later than Redmi 2.

**Comment by yipperr** [comment]
+1

**Comment by yipperr** [comment]
Anyone knows if the wireless driver supports monitor mode ? Also anyone has info in the wlan chipset driver used
