### ISSUE TITLE
Mi note 10 lite. Users ask for your help.

### ISSUE THREAD

**Issue by leancelot** [MiCode/Xiaomi_Kernel_OpenSource#2166]
Hello, developers.

We have problems that hinder cell phone users in miui. 

For example:
- The screen does not respond well or freezes. Regardless of what they're doing. Especially when they are typing. It happens that the keys do not go according to what is being typed and, on top of that, triggers typing by gesture, but even turning off the keyboard gestures it is almost impossible to type;
- Proximity sensor does not work correctly.

_The cell phone is incredible, but as stated above, development is not going very well._

Many people don't like to be stuck in miui and  you know it very well. That said, I and other interested people ask that the company consider releasing the kernel code for the Xiaomi mi note 10 lite. We have people really interested in helping to develop.

**What's wrong with doing that? We consumers have been asking for corrections for a while and we don't have appropriate answers and much less corrections for everyone so why continue to neglect the situation?**

I hope you are safe from the covid 😎

**Comment by moblue289** [comment]
yes please. a really big number of people are waiting for the source code before buying this phone. because they are deciding between this and m51 and if this gets kernel source then there is no reason to think about m51
