### ISSUE TITLE
[REQUEST] Release Mi Note 10 Lite Kernel Code (TOCO)

### ISSUE THREAD

**Issue by ghost** [MiCode/Xiaomi_Kernel_OpenSource#2197]
**Hi, I just bought this device, it would be great if the code that is necessary for many developers to create amazing works for this device would be released. :)**

**Comment by EduardMcfly** [comment]
It was uploaded a few days ago https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/toco-q-oss

**Comment by ghost** [comment]
**That's good news :)**
