### ISSUE TITLE
dandelion: Missing Files

### ISSUE THREAD

**Issue by wulan17** [MiCode/Xiaomi_Kernel_OpenSource#2202]
I tried to build dandelion (Redmi 9A) kernel last night and got this logs
https://del.dog/utoxanomib.txt
Can you give us the missing files?

**Comment by ghost** [comment]
> I tried to build dandelion (Redmi 9A) kernel last night and got this logs
> https://del.dog/utoxanomib.txt
> Can you give us the missing files?

Remove this line https://github.com/MiCode/Xiaomi_Kernel_OpenSource/blob/dandelion-q-oss/.gitignore#L21

**Comment by wulan17** [comment]
still same

**Comment by wulan17** [comment]
there should be a folder named 'include' here https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/dandelion-q-oss/drivers/input/touchscreen/mediatek/ft8006s_spi

**Comment by ghost** [comment]
> there should be a folder named 'include' here https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/dandelion-q-oss/drivers/input/touchscreen/mediatek/ft8006s_spi

https://github.com/TheMalachite/MiCode_kernel/commit/43493126ef405a157b4965a5caf8e77b7faef9f3 this should fix your issue since Xiaomi didn't added those firmware files like begonia kernel

**Comment by wulan17** [comment]
Ok thanks
