### ISSUE TITLE
wifi not working

### ISSUE THREAD

**Issue by XayahSuSuSu** [MiCode/Xiaomi_Kernel_OpenSource#2209]
02-17 01:54:58.202   903   903 E android.hardware.wifi@1.0-service: Failed to access driver state control param No such file or directory, 2: No such file or directory
02-17 01:54:58.202   903   903 E android.hardware.wifi@1.0-service: Failed to load WiFi driver
02-17 01:54:58.202   903   903 E android.hardware.wifi@1.0-service: Failed to initialize firmware mode controller
02-17 01:54:58.202   903   903 E android.hardware.wifi@1.0-service: Wifi HAL start failed
02-17 01:54:58.203  1682  1888 E HalDevMgr: Cannot start IWifi: 9 ()
02-17 01:54:58.203  1682  1888 E WifiVendorHal: Failed to start vendor HAL
02-17 01:54:58.203  1682  1888 E WifiNative: Failed to start vendor HAL
02-17 01:54:58.203  1682  1888 E WifiNative: Failed to start Hal
02-17 01:54:58.203  1682  1888 E WifiClientModeManager: Failed to create ClientInterface. Sit in Idle
02-17 01:54:58.204  1682  1888 D WifiScanRequestProxy: Sending scan available broadcast: false
02-17 01:54:58.204  1682  1891 I WifiScanningService: Received a request to disable scanning, UID = 1000
02-17 01:54:58.205  1682  1888 I WifiScanRequestProxy: Scanning is disabled
02-17 01:54:58.205  1682  1891 I WifiScanningService: wifi driver unloaded
02-17 01:54:58.206  1682  1888 D WifiClientModeManager: received an invalid message: { when=-1s6ms what=1 target=com.android.wifi.x.com.android.internal.util.StateMachine$SmHandler }
02-17 01:54:58.206  1682  1888 D WifiActiveModeWarden: Shutting down all softap mode managers in mode 1
02-17 01:54:58.206  1682  1888 D WifiController: STA disabled, return to DisabledState.
02-17 01:54:58.207  1682  1888 D WifiController: EnabledState.exit()
02-17 01:54:58.207  1682  1888 D WifiController: DisabledState.enter()
02-17 01:54:58.207  1682  1888 D WifiActiveModeWarden: Starting SoftApModeManager config = null
02-17 01:54:58.222  1682  1888 D WifiController: DisabledState.exit()
02-17 01:54:58.222  1682  1888 D WifiController: EnabledState.enter()

here is the log
how to fix it?

**Comment by michelangelo404** [comment]
> here is the log how to fix it?

how did you fix it?
