### ISSUE TITLE
小米爱你不容易，mi8SE 音频驱动如何编译到内核

### ISSUE THREAD

**Issue by han1985** [MiCode/Xiaomi_Kernel_OpenSource#2233]
audio kerel 拷贝到 techpack 编译后 手机无法启动，反复重启 折腾死了

**Comment by YumeMichi** [comment]
开源的代码是基于caf的编译系统的 你单独编译除了拷贝到指定目录还需要做一些makefile修改

**Comment by han1985** [comment]
兄弟能具体指点一下吗 小米8SE ,谢谢

**Comment by han1985** [comment]
能否留个qq 联系，可以有偿

**Comment by YumeMichi** [comment]
https://github.com/SDM710-Development/android_kernel_xiaomi_sdm710/commits/10.0-caf?after=33d49d1e75e932bb3317b857d8b76807b0de3ea1+69&branch=10.0-caf&path%5B%5D=drivers&path%5B%5D=staging
https://github.com/SDM710-Development/android_kernel_xiaomi_sdm710/commits/10.0-caf/techpack
