### ISSUE TITLE
Please release laurel-r-oss

### ISSUE THREAD

**Issue by ashu00** [MiCode/Xiaomi_Kernel_OpenSource#2249]
Please release the latest sources for laurel_sprout (mi A3)

**Comment by ashu00** [comment]
Sources released https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/laurel-r-oss

**Comment by selurvedu** [comment]
You may be also interested in my comment here: https://github.com/MiCode/Xiaomi_Kernel_OpenSource/issues/2161#issuecomment-882030712
