### ISSUE TITLE
[REQUEST] Kernel source for Mi 10T (apollo) Android 11

### ISSUE THREAD

**Issue by ghost** [MiCode/Xiaomi_Kernel_OpenSource#2250]
Hi! Please release the Mi 10T kernel source for Android 11 (R). There's now only Android 10 source.

Thanks!

**Comment by Aquarius223** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/cmi-r-oss

**Comment by ghost** [comment]
Woops, I mean Mi 10T

**Comment by Aquarius223** [comment]
Kernel: https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/cmi-r-oss
audio-kernel: https://github.com/MiCode/vendor_qcom_opensource_audio-kernel/tree/cmi-r-oss
data-kernel: https://github.com/MiCode/vendor_qcom_opensource_data-kernel/tree/cmi-r-oss
wlan: https://github.com/MiCode/vendor_qcom_opensource_wlan/tree/cmi-r-oss

defconfig: apollo_user_defconfig

**Comment by ghost** [comment]
Woaah, thank you so much! Don't know about that. Closing it
