### ISSUE TITLE
Release kernel source for begonia-r-oss

### ISSUE THREAD

**Issue by SahilSonar** [MiCode/Xiaomi_Kernel_OpenSource#2263]
We want kernel source for begonia-r-oss

**Comment by sjlua** [comment]
Yeah, do it and comply with GPL V3 pls.

**Comment by manojpudasaini** [comment]
We want **Kernel Source** for begonia-r-oss

**Comment by Dipanshu6** [comment]
yes please, fast af

**Comment by harshitv54** [comment]
Release Kernel Source for begonia-r-oss

**Comment by BitsAndBytes-dev** [comment]
We want kernel source for begonia-r-oss

**Comment by Jithin564** [comment]
Please release kernal source for begonia-r-oss as soon as possible.

**Comment by ghost** [comment]
Need sauce :v

**Comment by santoshhh000** [comment]
New kernel source when ...

**Comment by abhixv** [comment]
We want begonia-r-oss kernel source

**Comment by Droid-USSR** [comment]
We want kernel source for begonia-r-oss

**Comment by ghost** [comment]
all pro here , except me :D

**Comment by DrtSinX98** [comment]
Give kernel source for begonia-r-oss ;-;

**Comment by naveeneppalapally** [comment]
We want kernel source for begonia-r-oss

**Comment by HyperNotAryanX97** [comment]
We want kernel source for begonia-r-oss

**Comment by jojoethan** [comment]
We need kernel source for begonia-r-oss

**Comment by Flashokilleralt** [comment]
We want Kernel Source for begonia-r-oss

**Comment by Flashokilleralt** [comment]
We want Kernel Source for begonia-r-oss

**Comment by Flashokilleralt** [comment]
#We want Kernel Source for begonia-r-oss give plox don't violate GPL

**Comment by FLAMEPOSEIDON** [comment]
give begonia r-oss kernel Xiaomi 🙏

**Comment by BastianDeux** [comment]
Please give begonia-r-oss kernel sources we deserve and need them 🥺🥺🥺

**Comment by Hanan3000** [comment]
We want kernel source for begonia-r-oss

**Comment by Talhac21** [comment]
We want kernel source for begonia-r-oss please

**Comment by BitsAndBytes-dev** [comment]
Madarchod kernel source de...

**Comment by ios7jbpro** [comment]
yea we do want it

**Comment by TheFormidable** [comment]
We need kernel source for begonia-r-oss (don't forget the new camera sensors)

**Comment by Kardch** [comment]
We want kernel source for begonia-r-oss please

**Comment by Myehia201** [comment]
We want kernel source for begonia-r-oss

**Comment by XDinisev** [comment]
We want kernel source for begonia-r-oss 😐

**Comment by themirvel** [comment]
We want kernel source for begonia-r-oss  🥺

**Comment by XDinisev** [comment]
We want kernel source for begonia-r-oss

**Comment by Dv1101** [comment]
Give Begonia-r-oss kernel source

**Comment by HyperNotShroudX97** [comment]
Meowdharchomd Xioameme Kernel Sauces Dedo Bhosdiwalo

**Comment by ghost** [comment]
Give us begonia-r-oss source please :")

**Comment by HyperNotAryanX97** [comment]
Madharboard Kernel Source dede

**Comment by HyperNotAryanX97** [comment]
Fuck You Xiaomeme Give Source.
![500138100468_57018](https://user-images.githubusercontent.com/66762638/124065696-e93b0780-da54-11eb-9b59-ff709e90361b.jpg)

**Comment by XDinisev** [comment]
We need kernel source for begonia-r-oss

**Comment by itsmeyukiedcqii** [comment]
We want Kernel Source for begonia-r-oss

**Comment by leyash143** [comment]
We want the kernel source for begonia-r-oss, we need it badly! 😭🥺

**Comment by compassnet** [comment]
Please release the kernel source code for begonia-r-oss. Thank you!

**Comment by grimanos1** [comment]
Please release the kernel source code for begonia-r-oss

**Comment by 7Soldier** [comment]
RELEASE F*CKIN BEGONIA-R-OSS. XIAOMI PEACE OF SHIT. WHERE THE OUR SOURCES?!

**Comment by SahilSonar** [comment]
Thank you Xiaomi for releasing begonia-r-oss
