### ISSUE TITLE
redmi note8没有biloba_user_defconfig，是漏传了吗

### ISSUE THREAD

**Issue by huangzongwang** [MiCode/Xiaomi_Kernel_OpenSource#2269]
redmi note8没有biloba_user_defconfig，是漏传了吗 @micode

**Comment by stic-server-open** [comment]
这个就是: https://github.com/MiCode/Xiaomi_Kernel_OpenSource/blob/biloba-r-oss/arch/arm64/configs/biloba_defconfig
