### ISSUE TITLE
Makefile:146: recipe for target 'sub-make' failed

### ISSUE THREAD

**Issue by flben233** [MiCode/Xiaomi_Kernel_OpenSource#2289]
I tried to compile a cezanne kernel,but received the error.

  AR      fs/built-in.o
make[1]: Leaving directory '/home/Xiaomi_Kernel_OpenSource-cezanne-r-oss/out'
Makefile:146: recipe for target 'sub-make' failed
make: *** [sub-make] Error 2

Ubuntu 16.04

**Comment by Jon7s** [comment]
I have the same issue
