### ISSUE TITLE
There is no "DC Dimming" support in the current kernel sources of Xiaomi Mi 8 (dipper) 

### ISSUE THREAD

**Issue by ghost** [MiCode/Xiaomi_Kernel_OpenSource#2319]
Hello dear developers.
Are there any plans for source updates for Xiaomi Mi 8 (dipper)?
The fact is that the current version of the kernel lacks support for some functions, for example "DC Dimming", which is very important.
Thank you for your reply, it is very important and valuable for users of this device.

**Comment by Aquarius223** [comment]
There is dc dimming support in dipper-q-oss

**Comment by altirtix** [comment]
> There is dc dimming support in dipper-q-oss

Hello. Can I ask you to remove this issue? The fact is that it is indexed by the search engine when someone tries to find me by nickname. This spoils my privacy. Thanks in advance.

**Comment by Ki10V01T** [comment]
> There is dc dimming support in dipper-q-oss

Tell me please: how do I enable this feature in lineage os 22?
