### ISSUE TITLE
dandelion-q-oss: Missing many camera imgsensor and lcm drivers

### ISSUE THREAD

**Issue by ramabondanp** [MiCode/Xiaomi_Kernel_OpenSource#2325]
Missing camera / imgsensor :
```
- hynix_hi1337_iiii 
- gc_gc5035_iiii
- hynix_hi556_i
- hynix_hi556_ii
- ov_ov02b_ii
- ov_ov02b_iiii
- ov_ov02b_v
- ov_ov02b10_iv
- gc_gc02m10_ii
- hynix_hi259_iv
```

Missing lcm : 
```
- ft8006s_ab_vdo_hdp_boe_helitai
- ft8006s_ac_vdo_hdp_boe_helitai
- ili9882n_vdo_hdp_xinli
- nt36525b_vdo_hdp_boe_xinli
- icnl9911c_vdo_hdp_boe_xinli
- icnl9911c_vdo_hdp_boe_tianma
```

**Comment by ramabondanp** [comment]
@ivan19871002  @liuguo09 @mi-code

**Comment by ramabondanp** [comment]
![image](https://user-images.githubusercontent.com/14274061/136994263-8c0b751a-3da5-4bcf-9e38-447fe27ef2df.png)
img is the result of missing camera imgsensor drivers.
black and white color and flashlight is also broken.

**Comment by rolaylay** [comment]
plz

**Comment by ghost** [comment]
plz fix

**Comment by techyminati** [comment]
@mi-code Please look into it & fix kernel code

**Comment by ghost** [comment]
> Missing camera / imgsensor :
> 
> ```
> - hynix_hi1337_iiii 
> - gc_gc5035_iiii
> - hynix_hi556_i
> - hynix_hi556_ii
> - ov_ov02b_ii
> - ov_ov02b_iiii
> - ov_ov02b_v
> - ov_ov02b10_iv
> - gc_gc02m10_ii
> - hynix_hi259_iv
> ```
> 
> Missing lcm :
> 
> ```
> - ft8006s_ab_vdo_hdp_boe_helitai
> - ft8006s_ac_vdo_hdp_boe_helitai
> - ili9882n_vdo_hdp_xinli
> - nt36525b_vdo_hdp_boe_xinli
> - icnl9911c_vdo_hdp_boe_xinli
> - icnl9911c_vdo_hdp_boe_tianma
> ```

These sensors are found in the stock defconfig and no driver source is provided

**Comment by ghost** [comment]
### Stock

- [imgsensor support list in defconfig](https://github.com/Xenon-s-Workshop/redmi_dandelion_dump/blob/dandelion-user-10-QP1A.190711.020-V12.5.1.0.QCDCNXM-release-keys/ikconfig#L1333)
- [lcm support list in defconfig](https://github.com/Xenon-s-Workshop/redmi_dandelion_dump/blob/dandelion-user-10-QP1A.190711.020-V12.5.1.0.QCDCNXM-release-keys/ikconfig#L1368)

### MiCode opensource kernel

- [imgsensor support list in defconfig](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/blob/dandelion-q-oss/arch/arm64/configs/dandelion_defconfig#L121)
- [lcm support list in defconfig](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/blob/dandelion-q-oss/arch/arm64/configs/dandelion_defconfig#L136)

- [imgsensor_sensor_list.h](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/blob/dandelion-q-oss/drivers/misc/mediatek/imgsensor/src/common/v1/imgsensor_sensor_list.h)
- [mt65xx_lcm_list.h](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/blob/dandelion-q-oss/drivers/misc/mediatek/lcm/mt65xx_lcm_list.h)

**Comment by ghost** [comment]
So @mi-code pls add these missing things under [drivers/misc/mediatek/imgsensor/src/common/v1](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/dandelion-q-oss/drivers/misc/mediatek/imgsensor/src/common/v1) or [drivers/misc/mediatek/imgsensor/src/common/v1_1](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/dandelion-q-oss/drivers/misc/mediatek/imgsensor/src/common/v1_1):
- ~~hynix_hi1337_iiii~~
- ~~gc_gc5035_iiii~~
- hynix_hi556_i
- hynix_hi556_ii
- ov_ov02b_ii
- ov_ov02b_iiii
- ov_ov02b_v
- ov_ov02b10_iv
- gc_gc02m10_ii
- ~~hynix_hi259_iv~~

and following missing things under [drivers/misc/mediatek/lcm](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/dandelion-q-oss/drivers/misc/mediatek/lcm):
- ft8006s_ab_vdo_hdp_boe_helitai
- ft8006s_ac_vdo_hdp_boe_helitai
- ili9882n_vdo_hdp_xinli
- nt36525b_vdo_hdp_boe_xinli
- icnl9911c_vdo_hdp_boe_xinli
- icnl9911c_vdo_hdp_boe_tianma

**Comment by ghost** [comment]
### Update
I tried to create some missing imgsensor drivers and I got the rear camera (Hynix hi1337_iiii) working on dandelion (Redmi 9A), but the front camera still doesn't work on angelica (Redmi 9C) ......

The following missing imgsensor driver source code can be found [here](https://github.com/dandelion64-dev/android_kernel_xiaomi_opensource/tree/dev/drivers/misc/mediatek/imgsensor/src/common/v1).
* Hynix hi1337_iiii (hynix_hi1337_iiii)
* Hynix hi259_iv (hynix_hi259_iv)
* GalaxyCore gc5035_iiii (gc_gc5035_iiii)

Since this issue is already solved on dandelion (and it's the only device I have), I'm not going to create any other missing drivers, so please don't ask me for more xddd

### Note: use them only at your own risk

**Comment by Madara225** [comment]
> ### Обновлять
> 
> Я попытался создать некоторые отсутствующие драйверы imgensor, и у меня задняя камера (Hynix hi1337_iiii) работает на одуванчике (Redmi 9A), но передняя камера по-прежнему не работает на angelica (Redmi 9C)......
> 
> Следующий отсутствующий исходный код драйвера imgensor можно найти [здесь ](https://github.com/dandelion64-dev/android_kernel_xiaomi_opensource/tree/dev/drivers/misc/mediatek/imgsensor/src/common/v1).
> 
>     * Хайникс hi1337_iiii (hynix_hi1337_iiii)
> 
>     * Хайникс hi259_iv (hynix_hi259_iv)
> 
>     * GalaxyCore gc5035_iiii (gc_gc5035_iiii)
> 
> 
> Поскольку эта проблема уже решена на одуванчике (и это единственное устройство, которое у меня есть), я не собираюсь создавать другие отсутствующие драйверы, поэтому, пожалуйста, не просите меня о дополнительных xddd
> ### Примечание: используйте их только на свой страх и риск

no more links, right?(

**Comment by hendramanudinata03** [comment]
My friend found required camera drivers (not LCM) related to this Kernel. Here's the commit:

https://github.com/onettboots/Bool-X-dandelion/commit/56267bb743b34c0364e6ac69ebf91f7b43df16cb

I don't know where he got that, but worth a try!

**Comment by onettboots** [comment]
thanks @hendramanudinata03 moved here [aec3d84](https://github.com/onettboots/Bool-X-dandelion/commit/aec3d84a3d24009ed8a537f516c9774ac9df8a02)
