### ISSUE TITLE
[REQUEST] Please release Kernel source for Xiaomi 11 Lite 5G NE

### ISSUE THREAD

**Issue by vijayphule** [MiCode/Xiaomi_Kernel_OpenSource#2336]
It's being one month passed since the kernel sourse of Lisa (Xiaomi 11 Lite %G NE) haven't released  but within one month kernel source for Redmi note 11 has been released its really disappointing to see this we bought this device only because we think there are so many kernel and roms will available for Lisa
Now I think I should Sell this phone

**Comment by raulci** [comment]
We could use that kernel source to create the KernelSU for lisa. I don't have the knowledge to do it myself, but it will help the community to do it if we had this kernel.

Currently, it's only available for AOSP, but not for MIUI. I wish I could use KernelSU in MIUI.
