### ISSUE TITLE
Hi,When will release mi PAD 5 kernel source code?

### ISSUE THREAD

**Issue by greylink** [MiCode/Xiaomi_Kernel_OpenSource#2343]
PAD 5/PAD 5 PRO

**Comment by timtangdev** [comment]
I'm sorry, I just found the link.
You can close the issue,thx.


`<html>
<body>


elish-r-oss | Xiaomi Pad 5 Pro, Xiaomi Pad 5 Pro 5G | Android R | LA.UM.9.12.r1-08000-SMxx50.0 | elish-r-oss


-- | -- | -- | -- | --



</body>
</html>`

**Comment by wmxzrs** [comment]
what be they used for?

**Comment by timtangdev** [comment]
close
