### ISSUE TITLE
XiaoMi 11 lite 5G NE ( Lisa ) kernel source incomplete

### ISSUE THREAD

**Issue by Divyanshu-Modi** [MiCode/Xiaomi_Kernel_OpenSource#2365]
Respected,
Xiaomi, the kernel source for xiaomi 11 lite 5G NE (lisa) is missing alot of stuff 
which includes dts changes for camera and display, audio kernel changes, data-kernel changes ( if applicable).

I request you to go through the releases and rectify this issue.

Regards,
Divyanshu Modi

**Comment by tattwamashi** [comment]
+1

**Comment by Tashar02** [comment]
+69

**Comment by tattwamashi** [comment]
> +69

Lmao

**Comment by ryan-andri** [comment]
> +69

kek

**Comment by kardebayan** [comment]
+1

**Comment by suyashdahale** [comment]
Xiaomi you already took enough time to release kernel source and it is still incomplete , we ( lisa users ) request you to please update kernel source properly , so we can enjoy our device more with custome roms & kernels.
Thanks

**Comment by Vipxpert** [comment]
Bruh someone blows this up. There's no way Xiaomi accidentally did this on such a good phone. This's probably to keep people from enhancing their phone
