### ISSUE TITLE
(violet-q-oss)编译报错

### ISSUE THREAD

**Issue by zgangguoguo** [MiCode/Xiaomi_Kernel_OpenSource#2368]
手机：`redmi note 7 pro`

电脑：ubuntu 18.04.6
``Linux ubuntu 5.4.0-84-generic #94~18.04.1-Ubuntu SMP Thu Aug 26 23:17:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
``

按照[How to compile kernel standalone](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/wiki/How-to-compile-kernel-standalone)进行配置。
环境：`https://github.com/akhilnarang/scripts/blob/master/setup/android_build_env.sh`

``make O=out REAL_CC=${PWD}/toolchains/llvm-Snapdragon_LLVM_for_Android_6.0/prebuilt/linux-x86_64/bin/clang CLANG_TRIPLE=aarch64-linux-gnu- violet-perf_defconfig``

`make -j$(nproc) O=out REAL_CC=${PWD}/toolchains/llvm-Snapdragon_LLVM_for_Android_6.0/prebuilt/linux-x86_64/bin/clang CLANG_TRIPLE=aarch64-linux-gnu- 2>&1 | tee kernel.log`
输出：
>make[1]: Entering directory '/home/gynl/Desktop/kernel/Xiaomi/out'
arch/arm64/Makefile:57: Detected assembler with broken .inst; disassembly will be unreliable
  GEN     ./Makefile
scripts/kconfig/conf  --silentoldconfig Kconfig
arch/arm64/Makefile:57: Detected assembler with broken .inst; disassembly will be unreliable
  CHK     include/config/kernel.release
  GEN     ./Makefile
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  Using .. as source for kernel
  CHK     scripts/mod/devicetable-offsets.h
  CHK     include/generated/timeconst.h
  CHK     include/generated/bounds.h
  CHK     include/generated/asm-offsets.h
  CALL    ../scripts/checksyscalls.sh
  VDSOA   arch/arm64/kernel/vdso/gettimeofday.o
../arch/arm64/kernel/vdso/gettimeofday.S: Assembler messages:
../arch/arm64/kernel/vdso/gettimeofday.S:28: Error: no such instruction: `vdso_data .req x6'
../arch/arm64/kernel/vdso/gettimeofday.S:29: Error: no such instruction: `seqcnt .req w7'
../arch/arm64/kernel/vdso/gettimeofday.S:30: Error: no such instruction: `w_tmp .req w8'
../arch/arm64/kernel/vdso/gettimeofday.S:31: Error: no such instruction: `x_tmp .req x8'
../arch/arm64/kernel/vdso/gettimeofday.S:139: Error: no such instruction: `adr vdso_data,_vdso_data'
../arch/arm64/kernel/vdso/gettimeofday.S:141: Error: no such instruction: `cbz x0,2f'
../arch/arm64/kernel/vdso/gettimeofday.S:144: Error: no such instruction: `ldr seqcnt,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:144: Error: no such instruction: `tbnz seqcnt,'
../arch/arm64/kernel/vdso/gettimeofday.S:144: Error: no such instruction: `dmb ishld'
../arch/arm64/kernel/vdso/gettimeofday.S:145: Error: no such instruction: `ldr w_tmp,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:145: Error: no such instruction: `cbnz w_tmp,4f'
../arch/arm64/kernel/vdso/gettimeofday.S:146: Error: no such instruction: `ldr x10,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:148: Error: no such instruction: `ldp w11,w12,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:149: Error: no such instruction: `ldp x13,x14,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:150: Error: no such instruction: `dmb ishld'
../arch/arm64/kernel/vdso/gettimeofday.S:150: Error: no such instruction: `ldr w_tmp,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:150: Error: too many memory references for `cmp'
../arch/arm64/kernel/vdso/gettimeofday.S:150: Error: no such instruction: `b.ne 1b'
../arch/arm64/kernel/vdso/gettimeofday.S:152: Error: expecting operand after ','; got nothing
../arch/arm64/kernel/vdso/gettimeofday.S:152: Error: no such instruction: `movk x9,'
../arch/arm64/kernel/vdso/gettimeofday.S:153: Error: too many memory references for `lsl'
../arch/arm64/kernel/vdso/gettimeofday.S:155: Error: no such instruction: `isb'
../arch/arm64/kernel/vdso/gettimeofday.S:155: Error: no such instruction: `mrs x_tmp,cntvct_el0'
../arch/arm64/kernel/vdso/gettimeofday.S:155: Error: too many memory references for `sub'
../arch/arm64/kernel/vdso/gettimeofday.S:155: Error: no such instruction: `movn x_tmp,'
../arch/arm64/kernel/vdso/gettimeofday.S:155: Error: too many memory references for `and'
../arch/arm64/kernel/vdso/gettimeofday.S:155: Error: too many memory references for `mul'
../arch/arm64/kernel/vdso/gettimeofday.S:156: Error: too many memory references for `add'
../arch/arm64/kernel/vdso/gettimeofday.S:156: Error: no such instruction: `udiv x_tmp,x11,x9'
../arch/arm64/kernel/vdso/gettimeofday.S:156: Error: too many memory references for `add'
../arch/arm64/kernel/vdso/gettimeofday.S:156: Error: no such instruction: `msub x11,x_tmp,x9,x11'
../arch/arm64/kernel/vdso/gettimeofday.S:160: Error: expecting operand after ','; got nothing
../arch/arm64/kernel/vdso/gettimeofday.S:161: Error: too many memory references for `lsl'
../arch/arm64/kernel/vdso/gettimeofday.S:162: Error: no such instruction: `udiv x11,x11,x13'
../arch/arm64/kernel/vdso/gettimeofday.S:163: Error: no such instruction: `stp x10,x11,[x0,'
../arch/arm64/kernel/vdso/gettimeofday.S:166: Error: no such instruction: `cbz x1,3f'
../arch/arm64/kernel/vdso/gettimeofday.S:167: Error: no such instruction: `ldp w4,w5,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:168: Error: no such instruction: `stp w4,w5,[x1,'
../arch/arm64/kernel/vdso/gettimeofday.S:170: Error: too many memory references for `mov'
../arch/arm64/kernel/vdso/gettimeofday.S:174: Error: expecting operand after ','; got nothing
../arch/arm64/kernel/vdso/gettimeofday.S:175: Error: no such instruction: `svc '
../arch/arm64/kernel/vdso/gettimeofday.S:185: Error: expecting operand after ','; got nothing
../arch/arm64/kernel/vdso/gettimeofday.S:186: Error: no such instruction: `b.hi syscall'
../arch/arm64/kernel/vdso/gettimeofday.S:187: Error: no such instruction: `adr vdso_data,_vdso_data'
../arch/arm64/kernel/vdso/gettimeofday.S:188: Error: no such instruction: `adr x_tmp,jumptable'
../arch/arm64/kernel/vdso/gettimeofday.S:189: Error: too many memory references for `add'
../arch/arm64/kernel/vdso/gettimeofday.S:190: Error: no such instruction: `br x_tmp'
../arch/arm64/kernel/vdso/gettimeofday.S:194: Error: no such instruction: `b realtime'
../arch/arm64/kernel/vdso/gettimeofday.S:195: Error: Jump slot index mismatch
../arch/arm64/kernel/vdso/gettimeofday.S:195: Error: no such instruction: `b monotonic'
../arch/arm64/kernel/vdso/gettimeofday.S:196: Error: no such instruction: `b syscall'
../arch/arm64/kernel/vdso/gettimeofday.S:197: Error: no such instruction: `b syscall'
../arch/arm64/kernel/vdso/gettimeofday.S:198: Error: Jump slot index mismatch
../arch/arm64/kernel/vdso/gettimeofday.S:198: Error: no such instruction: `b monotonic_raw'
../arch/arm64/kernel/vdso/gettimeofday.S:199: Error: Jump slot index mismatch
../arch/arm64/kernel/vdso/gettimeofday.S:199: Error: no such instruction: `b realtime_coarse'
../arch/arm64/kernel/vdso/gettimeofday.S:200: Error: Jump slot index mismatch
../arch/arm64/kernel/vdso/gettimeofday.S:200: Error: no such instruction: `b monotonic_coarse'
../arch/arm64/kernel/vdso/gettimeofday.S:203: Error: Wrong jumptable size
../arch/arm64/kernel/vdso/gettimeofday.S:208: Error: no such instruction: `ldr seqcnt,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:208: Error: no such instruction: `tbnz seqcnt,'
../arch/arm64/kernel/vdso/gettimeofday.S:208: Error: no such instruction: `dmb ishld'
../arch/arm64/kernel/vdso/gettimeofday.S:209: Error: no such instruction: `ldr w_tmp,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:209: Error: no such instruction: `cbnz w_tmp,syscall'
../arch/arm64/kernel/vdso/gettimeofday.S:210: Error: no such instruction: `ldr x10,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:212: Error: no such instruction: `ldp w11,w12,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:213: Error: no such instruction: `ldp x13,x14,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:214: Error: no such instruction: `dmb ishld'
../arch/arm64/kernel/vdso/gettimeofday.S:214: Error: no such instruction: `ldr w_tmp,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:214: Error: too many memory references for `cmp'
../arch/arm64/kernel/vdso/gettimeofday.S:214: Error: no such instruction: `b.ne realtime'
../arch/arm64/kernel/vdso/gettimeofday.S:217: Error: expecting operand after ','; got nothing
../arch/arm64/kernel/vdso/gettimeofday.S:217: Error: no such instruction: `movk x9,'
../arch/arm64/kernel/vdso/gettimeofday.S:218: Error: too many memory references for `lsl'
../arch/arm64/kernel/vdso/gettimeofday.S:220: Error: no such instruction: `isb'
../arch/arm64/kernel/vdso/gettimeofday.S:220: Error: no such instruction: `mrs x_tmp,cntvct_el0'
../arch/arm64/kernel/vdso/gettimeofday.S:220: Error: too many memory references for `sub'
../arch/arm64/kernel/vdso/gettimeofday.S:220: Error: no such instruction: `movn x_tmp,'
../arch/arm64/kernel/vdso/gettimeofday.S:220: Error: too many memory references for `and'
../arch/arm64/kernel/vdso/gettimeofday.S:220: Error: too many memory references for `mul'
../arch/arm64/kernel/vdso/gettimeofday.S:221: Error: too many memory references for `add'
../arch/arm64/kernel/vdso/gettimeofday.S:221: Error: no such instruction: `udiv x_tmp,x11,x9'
../arch/arm64/kernel/vdso/gettimeofday.S:221: Error: too many memory references for `add'
../arch/arm64/kernel/vdso/gettimeofday.S:221: Error: no such instruction: `msub x11,x_tmp,x9,x11'
../arch/arm64/kernel/vdso/gettimeofday.S:223: Error: no such instruction: `lsr x11,x11,x12'
../arch/arm64/kernel/vdso/gettimeofday.S:223: Error: no such instruction: `stp x10,x11,[x1,'
../arch/arm64/kernel/vdso/gettimeofday.S:223: Error: too many memory references for `mov'
../arch/arm64/kernel/vdso/gettimeofday.S:227: Error: no such instruction: `ldr seqcnt,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:227: Error: no such instruction: `tbnz seqcnt,'
../arch/arm64/kernel/vdso/gettimeofday.S:227: Error: no such instruction: `dmb ishld'
../arch/arm64/kernel/vdso/gettimeofday.S:228: Error: no such instruction: `ldr w_tmp,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:228: Error: no such instruction: `cbnz w_tmp,syscall'
../arch/arm64/kernel/vdso/gettimeofday.S:229: Error: no such instruction: `ldr x10,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:231: Error: no such instruction: `ldp w11,w12,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:232: Error: no such instruction: `ldp x13,x14,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:233: Error: no such instruction: `ldp x3,x4,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:234: Error: no such instruction: `dmb ishld'
../arch/arm64/kernel/vdso/gettimeofday.S:234: Error: no such instruction: `ldr w_tmp,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:234: Error: too many memory references for `cmp'
../arch/arm64/kernel/vdso/gettimeofday.S:234: Error: no such instruction: `b.ne monotonic'
../arch/arm64/kernel/vdso/gettimeofday.S:237: Error: too many memory references for `lsl'
../arch/arm64/kernel/vdso/gettimeofday.S:238: Error: expecting operand after ','; got nothing
../arch/arm64/kernel/vdso/gettimeofday.S:238: Error: no such instruction: `movk x9,'
../arch/arm64/kernel/vdso/gettimeofday.S:239: Error: too many memory references for `lsl'
../arch/arm64/kernel/vdso/gettimeofday.S:241: Error: no such instruction: `isb'
../arch/arm64/kernel/vdso/gettimeofday.S:241: Error: no such instruction: `mrs x_tmp,cntvct_el0'
../arch/arm64/kernel/vdso/gettimeofday.S:241: Error: too many memory references for `sub'
../arch/arm64/kernel/vdso/gettimeofday.S:241: Error: no such instruction: `movn x_tmp,'
../arch/arm64/kernel/vdso/gettimeofday.S:241: Error: too many memory references for `and'
../arch/arm64/kernel/vdso/gettimeofday.S:241: Error: too many memory references for `mul'
../arch/arm64/kernel/vdso/gettimeofday.S:242: Error: too many memory references for `add'
../arch/arm64/kernel/vdso/gettimeofday.S:242: Error: no such instruction: `udiv x_tmp,x11,x9'
../arch/arm64/kernel/vdso/gettimeofday.S:242: Error: too many memory references for `add'
../arch/arm64/kernel/vdso/gettimeofday.S:242: Error: no such instruction: `msub x11,x_tmp,x9,x11'
../arch/arm64/kernel/vdso/gettimeofday.S:245: Error: too many memory references for `add'
../arch/arm64/kernel/vdso/gettimeofday.S:245: Error: too many memory references for `add'
../arch/arm64/kernel/vdso/gettimeofday.S:245: Error: too many memory references for `cmp'
../arch/arm64/kernel/vdso/gettimeofday.S:245: Error: no such instruction: `b.lt 9999f'
../arch/arm64/kernel/vdso/gettimeofday.S:245: Error: too many memory references for `sub'
../arch/arm64/kernel/vdso/gettimeofday.S:245: Error: too many memory references for `add'
../arch/arm64/kernel/vdso/gettimeofday.S:245: Error: expecting operand after ','; got nothing
../arch/arm64/kernel/vdso/gettimeofday.S:245: Error: no such instruction: `b.ge 9998f'
../arch/arm64/kernel/vdso/gettimeofday.S:245: Error: too many memory references for `add'
../arch/arm64/kernel/vdso/gettimeofday.S:245: Error: too many memory references for `sub'
../arch/arm64/kernel/vdso/gettimeofday.S:246: Error: no such instruction: `lsr x11,x11,x12'
../arch/arm64/kernel/vdso/gettimeofday.S:246: Error: no such instruction: `stp x10,x11,[x1,'
../arch/arm64/kernel/vdso/gettimeofday.S:246: Error: too many memory references for `mov'
../arch/arm64/kernel/vdso/gettimeofday.S:250: Error: no such instruction: `ldr seqcnt,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:250: Error: no such instruction: `tbnz seqcnt,'
../arch/arm64/kernel/vdso/gettimeofday.S:250: Error: no such instruction: `dmb ishld'
../arch/arm64/kernel/vdso/gettimeofday.S:251: Error: no such instruction: `ldr w_tmp,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:251: Error: no such instruction: `cbnz w_tmp,syscall'
../arch/arm64/kernel/vdso/gettimeofday.S:252: Error: no such instruction: `ldr x10,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:254: Error: no such instruction: `ldp w12,w11,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:255: Error: no such instruction: `ldp x13,x14,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:256: Error: no such instruction: `dmb ishld'
../arch/arm64/kernel/vdso/gettimeofday.S:256: Error: no such instruction: `ldr w_tmp,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:256: Error: too many memory references for `cmp'
../arch/arm64/kernel/vdso/gettimeofday.S:256: Error: no such instruction: `b.ne monotonic_raw'
../arch/arm64/kernel/vdso/gettimeofday.S:259: Error: expecting operand after ','; got nothing
../arch/arm64/kernel/vdso/gettimeofday.S:259: Error: no such instruction: `movk x9,'
../arch/arm64/kernel/vdso/gettimeofday.S:260: Error: too many memory references for `lsl'
../arch/arm64/kernel/vdso/gettimeofday.S:262: Error: no such instruction: `isb'
../arch/arm64/kernel/vdso/gettimeofday.S:262: Error: no such instruction: `mrs x_tmp,cntvct_el0'
../arch/arm64/kernel/vdso/gettimeofday.S:262: Error: too many memory references for `sub'
../arch/arm64/kernel/vdso/gettimeofday.S:262: Error: no such instruction: `movn x_tmp,'
../arch/arm64/kernel/vdso/gettimeofday.S:262: Error: too many memory references for `and'
../arch/arm64/kernel/vdso/gettimeofday.S:262: Error: too many memory references for `mul'
../arch/arm64/kernel/vdso/gettimeofday.S:263: Error: no such instruction: `udiv x10,x15,x9'
../arch/arm64/kernel/vdso/gettimeofday.S:263: Error: no such instruction: `msub x11,x10,x9,x15'
../arch/arm64/kernel/vdso/gettimeofday.S:266: Error: too many memory references for `add'
../arch/arm64/kernel/vdso/gettimeofday.S:266: Error: too many memory references for `add'
../arch/arm64/kernel/vdso/gettimeofday.S:266: Error: too many memory references for `cmp'
../arch/arm64/kernel/vdso/gettimeofday.S:266: Error: no such instruction: `b.lt 9999f'
../arch/arm64/kernel/vdso/gettimeofday.S:266: Error: too many memory references for `sub'
../arch/arm64/kernel/vdso/gettimeofday.S:266: Error: too many memory references for `add'
../arch/arm64/kernel/vdso/gettimeofday.S:266: Error: expecting operand after ','; got nothing
../arch/arm64/kernel/vdso/gettimeofday.S:266: Error: no such instruction: `b.ge 9998f'
../arch/arm64/kernel/vdso/gettimeofday.S:266: Error: too many memory references for `add'
../arch/arm64/kernel/vdso/gettimeofday.S:266: Error: too many memory references for `sub'
../arch/arm64/kernel/vdso/gettimeofday.S:267: Error: no such instruction: `lsr x11,x11,x12'
../arch/arm64/kernel/vdso/gettimeofday.S:267: Error: no such instruction: `stp x10,x11,[x1,'
../arch/arm64/kernel/vdso/gettimeofday.S:267: Error: too many memory references for `mov'
../arch/arm64/kernel/vdso/gettimeofday.S:271: Error: no such instruction: `ldr seqcnt,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:271: Error: no such instruction: `tbnz seqcnt,'
../arch/arm64/kernel/vdso/gettimeofday.S:271: Error: no such instruction: `dmb ishld'
../arch/arm64/kernel/vdso/gettimeofday.S:272: Error: no such instruction: `ldp x10,x11,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:273: Error: no such instruction: `dmb ishld'
../arch/arm64/kernel/vdso/gettimeofday.S:273: Error: no such instruction: `ldr w_tmp,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:273: Error: too many memory references for `cmp'
../arch/arm64/kernel/vdso/gettimeofday.S:273: Error: no such instruction: `b.ne realtime_coarse'
../arch/arm64/kernel/vdso/gettimeofday.S:274: Error: no such instruction: `stp x10,x11,[x1,'
../arch/arm64/kernel/vdso/gettimeofday.S:274: Error: too many memory references for `mov'
../arch/arm64/kernel/vdso/gettimeofday.S:278: Error: no such instruction: `ldr seqcnt,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:278: Error: no such instruction: `tbnz seqcnt,'
../arch/arm64/kernel/vdso/gettimeofday.S:278: Error: no such instruction: `dmb ishld'
../arch/arm64/kernel/vdso/gettimeofday.S:279: Error: no such instruction: `ldp x10,x11,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:280: Error: no such instruction: `ldp x13,x14,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:281: Error: no such instruction: `dmb ishld'
../arch/arm64/kernel/vdso/gettimeofday.S:281: Error: no such instruction: `ldr w_tmp,[vdso_data,'
../arch/arm64/kernel/vdso/gettimeofday.S:281: Error: too many memory references for `cmp'
../arch/arm64/kernel/vdso/gettimeofday.S:281: Error: no such instruction: `b.ne monotonic_coarse'
../arch/arm64/kernel/vdso/gettimeofday.S:284: Error: expecting operand after ','; got nothing
../arch/arm64/kernel/vdso/gettimeofday.S:284: Error: no such instruction: `movk x9,'
../arch/arm64/kernel/vdso/gettimeofday.S:285: Error: too many memory references for `add'
../arch/arm64/kernel/vdso/gettimeofday.S:285: Error: too many memory references for `add'
../arch/arm64/kernel/vdso/gettimeofday.S:285: Error: too many memory references for `cmp'
../arch/arm64/kernel/vdso/gettimeofday.S:285: Error: no such instruction: `b.lt 9999f'
../arch/arm64/kernel/vdso/gettimeofday.S:285: Error: too many memory references for `sub'
../arch/arm64/kernel/vdso/gettimeofday.S:285: Error: too many memory references for `add'
../arch/arm64/kernel/vdso/gettimeofday.S:285: Error: expecting operand after ','; got nothing
../arch/arm64/kernel/vdso/gettimeofday.S:285: Error: no such instruction: `b.ge 9998f'
../arch/arm64/kernel/vdso/gettimeofday.S:285: Error: too many memory references for `add'
../arch/arm64/kernel/vdso/gettimeofday.S:285: Error: too many memory references for `sub'
../arch/arm64/kernel/vdso/gettimeofday.S:286: Error: no such instruction: `stp x10,x11,[x1,'
../arch/arm64/kernel/vdso/gettimeofday.S:286: Error: too many memory references for `mov'
../arch/arm64/kernel/vdso/gettimeofday.S:290: Error: expecting operand after ','; got nothing
../arch/arm64/kernel/vdso/gettimeofday.S:291: Error: no such instruction: `svc '
../arch/arm64/kernel/vdso/gettimeofday.S:299: Error: expecting operand after ','; got nothing
../arch/arm64/kernel/vdso/gettimeofday.S:300: Error: no such instruction: `ccmp w0,'
../arch/arm64/kernel/vdso/gettimeofday.S:301: Error: no such instruction: `ccmp w0,'
../arch/arm64/kernel/vdso/gettimeofday.S:302: Error: no such instruction: `b.ne 1f'
../arch/arm64/kernel/vdso/gettimeofday.S:304: Error: no such instruction: `ldr x2,5f'
../arch/arm64/kernel/vdso/gettimeofday.S:305: Error: no such instruction: `b 2f'
../arch/arm64/kernel/vdso/gettimeofday.S:307: Error: expecting operand after ','; got nothing
../arch/arm64/kernel/vdso/gettimeofday.S:308: Error: no such instruction: `ccmp w0,'
../arch/arm64/kernel/vdso/gettimeofday.S:309: Error: no such instruction: `b.ne 4f'
../arch/arm64/kernel/vdso/gettimeofday.S:310: Error: no such instruction: `ldr x2,6f'
../arch/arm64/kernel/vdso/gettimeofday.S:312: Error: no such instruction: `cbz x1,3f'
../arch/arm64/kernel/vdso/gettimeofday.S:313: Error: no such instruction: `stp xzr,x2,[x1]'
../arch/arm64/kernel/vdso/gettimeofday.S:316: Error: too many memory references for `mov'
../arch/arm64/kernel/vdso/gettimeofday.S:320: Error: expecting operand after ','; got nothing
../arch/arm64/kernel/vdso/gettimeofday.S:321: Error: no such instruction: `svc '
clang-6.0: error: assembler command failed with exit code 1 (use -v to see invocation)
../arch/arm64/kernel/vdso/Makefile:55: recipe for target 'arch/arm64/kernel/vdso/gettimeofday.o' failed
make[2]: *** [arch/arm64/kernel/vdso/gettimeofday.o] Error 1
arch/arm64/Makefile:215: recipe for target 'vdso_prepare' failed
make[1]: *** [vdso_prepare] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/gynl/Desktop/kernel/Xiaomi/out'
Makefile:146: recipe for target 'sub-make' failed
make: *** [sub-make] Error 2

小白一个，请求帮助。

**Comment by Angel0726** [comment]
https://www.google.com/url?sa=t&source=web&rct=j&url=https://github.com/MiCode/Xiaomi_Kernel_OpenSource/issues/957&ved=2ahUKEwj95eToh9f1AhVxJUQIHXTqD1sQFnoECAUQAQ&usg=AOvVaw0Be3wSTCPIqXgioJUA5o2I
简单来说不容易
