### ISSUE TITLE
Release kernel source for Redmi K20Pro(Mi 9T Pro)/K40S/K50/K50Pro

### ISSUE THREAD

**Issue by kaffuchino233** [MiCode/Xiaomi_Kernel_OpenSource#2514]

**Comment by willzyx-hub** [comment]
> Please release kernel source for Redmi K20Pro(Mi 9T Pro)/40S/K50/K50Pro,FUCK XIAOMI.

It will not be released

**Comment by ajaikumarnadar** [comment]
It would be good if you guys complained about this GPLv2 violation here. 
https://www.gnu.org/licenses/gpl-violation.en.html

**Comment by QKIvan** [comment]
LET'S OPEN AGAIN,PLS OPEN SOURCE
