### ISSUE TITLE
Request open source kernel for POCO F4&K40s(munch)

### ISSUE THREAD

**Issue by ghost** [MiCode/Xiaomi_Kernel_OpenSource#2583]
I bought POCO phone for flash other system. But I find that Xiaomi doesn't support for kernel open source these days. So I request for open source for munch on Github. If the team can see that, please open source! Many users hope that !

**Comment by Cleveland996** [comment]
Agree with you！！

**Comment by VaibhavTakVT** [comment]
@mi-code please release source code for poco f4

**Comment by craftogrammer** [comment]
@mi-code please release source code for poco f4

**Comment by psklf** [comment]
please release source code for poco f4

**Comment by Aquarius223** [comment]
Redmi K40S Android S kernel Source:
* Note, the techpack lacks display and camera.
kernel: https://github.com/MiCode/Xiaomi_Kernel_OpenSource/commit/3d665367f026a
audio-kernel: https://github.com/MiCode/vendor_qcom_opensource_audio-kernel/tree/munch-s-oss

**Comment by craftogrammer** [comment]
> Redmi K40S Android S kernel Source:
> 
> * Note, the techpack lacks display and camera.
>   kernel: [3d665367f026a](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/commit/3d665367f026a)
>   audio-kernel: https://github.com/MiCode/vendor_qcom_opensource_audio-kernel/tree/munch-s-oss

Can we use the source of alioth?

**Comment by PaiJi** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/munch-s-oss
