### ISSUE TITLE
Device Xaga/Redminote11tpro/X4GT/K50i /Request/Open source "Kernel"/ForMtkD8100

### ISSUE THREAD

**Issue by AnyOne06** [MiCode/Xiaomi_Kernel_OpenSource#2616]
As for this device development and more and more users that wishes to get an open source device I'm begging for your support and I'm hopefully requesting this device kernel source for better customization.Plss don't leave mtk behind of beauty and passion on custom roms.
I'm gay don't be racist!

**Comment by AnyOne06** [comment]
Ty xioami

**Comment by AnyOne06** [comment]
Ty

**Comment by ParampreetR** [comment]
@AnyOne06 you seem professional, they released kernel source for `xaga`. So will it be enough to develop custom roms for Redmi k50i/note 11T pro? Coz I have heard that we can't expect to see custom roms for devices with mediatek chipset. In short, can we expect to see custom roms for these devices? Noob here

**Comment by AnyOne06** [comment]
> @AnyOne06 you seem professional, they released kernel source for `xaga`. So will it be enough to develop custom roms for Redmi k50i/note 11T pro? Coz I have heard that we can't expect to see custom roms for devices with mediatek chipset. In short, can we expect to see custom roms for these devices? Noob here 

Yes very soon ☺️ something is coming

**Comment by ParampreetR** [comment]
> Yes very soon ☺️ something is coming

I'll be waiting 😃 and thanks for quick reply

**Comment by 404b** [comment]
> > @AnyOne06 you seem professional, they released kernel source for `xaga`. So will it be enough to develop custom roms for Redmi k50i/note 11T pro? Coz I have heard that we can't expect to see custom roms for devices with mediatek chipset. In short, can we expect to see custom roms for these devices? Noob here
> 
> Yes very soon ☺️ something is coming

Are you working on xaga/xagain soon?

**Comment by Samandar02** [comment]
@AnyOne06 Hi bro,
Have you done that?
What PC req are needed to get started and what is the roadmap for it?

**Comment by Samandar02** [comment]
@ParampreetR
What I heard is it is possible to build a custom ROM, but the problem is on availability of community (supportive) for MTK devices in case something goes wrong, but there are MIUI EU 13 and 14 ROMs available to download.
In my experience, MTK has always been the most likely to be unbrickable compared to Snapdragon chipset devices which ended up being a trash.
