### ISSUE TITLE
[REQUEST] Release xiaomi 12 (cupid) bootloader

### ISSUE THREAD

**Issue by frickypickle** [MiCode/Xiaomi_Kernel_OpenSource#2617]
As stated in the title releasing the bootloader would be very nice

**Comment by HyperN00B** [comment]
And you really think Xiaomi will just release the code of the bootloader like that?

**Comment by frickypickle** [comment]
> And you really think Xiaomi will just release the code of the bootloader like that?

Well it's better to have hope than to not have hope.

**Comment by xenxynon** [comment]
He has a point

**Comment by Sushrut1101** [comment]
> > And you really think Xiaomi will just release the code of the bootloader like that?
> 
> Well it's better to have hope than to not have hope.

Lmao
Spam Xiaomi to release the entire vendor/qcom 😂

**Comment by beakthoven** [comment]
> > > And you really think Xiaomi will just release the code of the bootloader like that?
> > 
> > 
> > Well it's better to have hope than to not have hope.
> 
> Lmao Spam Xiaomi to release the entire vendor/qcom 😂

if going till that extent, why left mtk behind... Release that also.

**Comment by NotEclypse** [comment]
> He has a point

yeah hes got a point there

**Comment by HyperN00B** [comment]
Why not just release the code for every blob in every Xiaomi device and a bootloader code that doesn't verify the boot process and lets you load custom stuff with locked BL?

**Comment by HyperN00B** [comment]
> > And you really think Xiaomi will just release the code of the bootloader like that?
> 
> Well it's better to have hope than to not have hope.

You have a point. But i don't think Xiaomi (or any OEM for that matter) will even consider releasing their proprietary stuff as OpenSource.
Otherwise how would stock ROMs be ANY better than custom ROMs if custom can build stuff like MiuiCamera and RealmeCamera and Fastcharge compatible kernels.

**Comment by takumi021** [comment]
> As stated in the title releasing the bootloader would be very nice

Woaaahhhhhh

**Comment by itsurboimasarou** [comment]
release bootloader?? really??

**Comment by frickypickle** [comment]
> release bootloader?? really??

I've just realized that I said bootloader instead of Kernal out of tiredness

**Comment by Divyanshu-Modi** [comment]
They are not releasing oss kernel sources and you expected them to release the proprietary bootloader sources👍

**Comment by sonic011gamer** [comment]
Well, you can always get ABL but don't expect XBL, unless it leaks somehow
