### ISSUE TITLE
vayu-s-oss release

### ISSUE THREAD

**Issue by acastillorobles77** [MiCode/Xiaomi_Kernel_OpenSource#2649]
Hello, please release Poco X3 Pro Android 12 (vayu-s-oss) kernel sources, no major development can be done without android 12 kernel sources...

**Comment by feiplane** [comment]
> Hello, please release Poco X3 Pro Android 12 (vayu-s-oss) kernel sources, no major development can be done without android 12 kernel sources...

U mean current one cannot work on the miui 13 + android 12 stock rom?

**Comment by feiplane** [comment]
> Hello, please release Poco X3 Pro Android 12 (vayu-s-oss) kernel sources, no major development can be done without android 12 kernel sources...

Alright, u dont need newer kernel for android s, current kernel source is enough already to boot miui 13 android 12
