### ISSUE TITLE
[GPL] [REQUEST] Kernel Source Release for Redmi 10C (fog,wing,rain)

### ISSUE THREAD

**Issue by Notkerd69** [MiCode/Xiaomi_Kernel_OpenSource#2860]
Hi, please release the Kernel source as soon as possible.... For to the development within the Redmi 10C community, to get better experiences out of our devices

您好，请尽快发布内核源码。...为了Redmi 10C社区内的开发，让我们的设备获得更好的体验

**Comment by Viper-droid** [comment]
When release kernel source for Redmi 10C?

**Comment by DenHafiz69** [comment]
Please release the code Xiaomi. We need custom rom for this phone.

**Comment by awkitsune** [comment]
Xiaomi, please release kernel sources, it's GPL violation afaik
