### ISSUE TITLE
[QUESTION] I need contacts of the kernel dev of the kernel "sweet"

### ISSUE THREAD

**Issue by Lsc0x80** [MiCode/Xiaomi_Kernel_OpenSource#3100]
Hello, please give me the contacts of the author of the kernel "sweet" after 2022.10. I need drivers, because the touchscreen fts_ts does not work on custom firmware, to be more precise on custom kernels.

**Comment by Lsc0x80** [comment]
Translate with baidu 
我需要Sweet内核作者的联系人，我需要FTS_TS触摸屏驱动程序，因为触摸屏在自定义内核上不起作用。

**Comment by Ronald826** [comment]
Hello @RUqwe, I recommend you base your kernel off of other sources as other sources may have that problems fixed. Try to search for your codename at Yukina-Supreme. Xiaomi is really shitty when it comes to releasing source codes.

**Comment by Lsc0x80** [comment]
> Hello @RUqwe, I recommend you base your kernel off of other sources as other sources may have that problems fixed. Try to search for your codename at Yukina-Supreme. Xiaomi is really shitty when it comes to releasing source codes.

what is "Yukina-Supreme"?

**Comment by Ronald826** [comment]
Yukina-supreme is a custom kernel. They release the devices sources too in github.

**Comment by 3291823** [comment]
Hi @Ronald826 , unfortunately they do not have device for sweet. Thanks for suggestion.
