### ISSUE TITLE
Oh fuck you Xiaomi Release the fuckin camellia-s-oss

### ISSUE THREAD

**Issue by willzyx-hub** [MiCode/Xiaomi_Kernel_OpenSource#3105]
We need this !

**Comment by Ronald826** [comment]
oh my god are you serious? you can still use the old version for future android versions plus you can always patch the linux kernel code

**Comment by willzyx-hub** [comment]
> oh my god are you serious? you can still use the old version for future android versions plus you can always patch the linux kernel code

If Xiaomi could release `camellia-s-oss` then it would make it easier

**Comment by Ronald826** [comment]
just git fetch linux tree and git merge it. it's that simple

**Comment by willzyx-hub** [comment]
> just git fetch linux tree and git merge it. it's that simple

By Linux you mean the Linux Kernel provided by Linus Torvalds ?

**Comment by Ronald826** [comment]
yeah or merge the latest android kernel tree

**Comment by willzyx-hub** [comment]
> yeah or merge the latest android kernel tree

so i just need to download Linux tree then copy `camellia-r-oss` sources over it ?

**Comment by brian0309** [comment]
how's the progress bro? 😂😂
development of this device is dead 😂

**Comment by AbzRaider** [comment]
@willzyx-hub do you have any major issues on r oss just upstream it search on google there are easy guides

**Comment by bogati2000** [comment]
There are missing drivers in old Camelia kernal source

**Comment by rudywasfound** [comment]
i guess i really have to work now.

**Comment by bogati2000** [comment]
> i guess i really have to work now.

Good luck buddy

**Comment by gartriss** [comment]
FIX ALREADY!! fix camellia-r-oss and release camellia-t-oss | 修复camellia-r-oss并发布camellia-t-oss!!!

**Comment by rudywasfound** [comment]
doing it gartriss

**Comment by AbzRaider** [comment]
> doing it gartriss

I saw your xiaomi-alps repo
Bro that's not how it works importing driver from Selene won't work you're not even using the proper driver ig
You need to modify the driver to load the correct lcm 
Import LCM LK changes as did in MIUI Kernel
Import DRM changes ( which u can't kang from other sources).
Extract DTS Changes from Prebuilt Kernel

**Comment by rudywasfound** [comment]
well honestly yeah i am a bit of a new guy to the arm section would take time i am still learning how to do stuff on the android kernel out there
