### ISSUE TITLE
source code of mi note pro

### ISSUE THREAD

**Issue by Mjollnirs** [MiCode/Xiaomi_Kernel_OpenSource#32]
where is the source code of mi note pro

**Comment by pouyab** [comment]
Please someone contact Xiaomi about this issue, did my best but no success contacting officials of the company

**Comment by sarvesvara** [comment]
As far the latest (last week) update on 2-Mar-2016... it will be released next. I don't know the meaning of 'next'.

Link: http://en.miui.com/thread-235127-1-1.html

**Comment by sarvesvara** [comment]
It is released NOW

**Comment by bgcngm** [comment]
It has been released (under [libra-l-oss branch](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/libra-l-oss)). You can close this now.
