### ISSUE TITLE
Please release the kernel source of mi4c

### ISSUE THREAD

**Issue by FoeniX233** [MiCode/Xiaomi_Kernel_OpenSource#34]
We need more choice ! Please hear the sound of mi fans !!!

**Comment by talpachen** [comment]
We need more choice ! Please hear the sound of mi fans !!!

**Comment by sarvesvara** [comment]
As far the latest (last week) update on 2-Mar-2016... it will be released next. I don't know the meaning of 'next'.

Link: http://en.miui.com/thread-235127-1-1.html

**Comment by bgcngm** [comment]
It has been released (under [libra-l-oss branch](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/libra-l-oss)). You can close this now.
