### ISSUE TITLE
Source request for gemini (Xiaomi Mi5) Kernel

### ISSUE THREAD

**Issue by h2o64** [MiCode/Xiaomi_Kernel_OpenSource#38]
Hello,
the Xiaomi mi5 device is out since a month (http://en.miui.com/thread-230807-1-1.html)
This build is available from xiaomi servers themselves (http://en.miui.com/download-299.html) :

```
ro.build.id=MRA58K
ro.build.display.id=MRA58K
ro.build.version.incremental=V7.2.8.0.MAACNDB
ro.build.date=Tue Mar 22 18:36:59 CST 2016
ro.product.model=MI 5
ro.product.brand=Xiaomi
ro.build.product=gemini
ro.build.description=gemini-user 6.0 MRA58K V7.2.8.0.MAACNDB release-keys
ro.build.fingerprint=Xiaomi/gemini/gemini:6.0/MRA58K/V7.2.8.0.MAACNDB:user/release-keys
```

According to GPL 3.0 agreements (http://www.gnu.org/licenses/gpl-3.0.en.html), could Xiaomi release the kernel sources quickly ?

**Comment by anarkia1976** [comment]
This is true, we need source! please.

**Comment by teknoraver** [comment]
sources, please

a mi 5 owner

**Comment by scafroglia93** [comment]
Source Source Source Source

**Comment by anarkia1976** [comment]
Source is necessary, otherwise you loose xiami! thanks.

**Comment by arter97** [comment]
Source Source Source Source(2)

**Comment by teknoraver** [comment]
`**********************************************************
**   NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE   **
**                                                      **
** trace_printk() being used. Allocating extra memory.  **
**                                                      **
** This means that this is a DEBUG kernel and it is     **
** unsafe for produciton use.                           **
**                                                      **
** If you see this message and you are not debugging    **
** the kernel, report this immediately to your vendor!  **
**                                                      **
**   NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE   **
**********************************************************`

**Comment by teknoraver** [comment]
Source please, even to remove this big fat warning:

`**********************************************************
**   NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE   **
**                                                      **
** trace_printk() being used. Allocating extra memory.  **
**                                                      **
** This means that this is a DEBUG kernel and it is     **
** unsafe for produciton use.                           **
**                                                      **
** If you see this message and you are not debugging    **
** the kernel, report this immediately to your vendor!  **
**                                                      **
**   NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE   **
**********************************************************`

**Comment by teknoraver** [comment]
Source please, even to remove this big fat warning:

`````` **********************************************************
**   NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE   **
**                                                      **
** trace_printk() being used. Allocating extra memory.  **
**                                                      **
** This means that this is a DEBUG kernel and it is     **
** unsafe for produciton use.                           **
**                                                      **
** If you see this message and you are not debugging    **
** the kernel, report this immediately to your vendor!  **
**                                                      **
**   NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE   **
**********************************************************```
``````

**Comment by blues-man** [comment]
How could we trust you if we can't see what you do? We love MIUI, and we trusted Lei Jun's words about it was worth to wait so long to get Mi5, but now that we finally hold it, we have a black box device since we can't look at the Android kernel, thus we cannot have the same freedom that let you give us a great Android device.

**Comment by Fabio-San** [comment]
Come on, xiaomi, do this right favour to the devs ;)

**Comment by anarkia1976** [comment]
Public pool? :100:

**Comment by scafroglia93** [comment]
Sure ... Because of Xiaomi i bricked the phone. Stupid bootloader policy

**Comment by proagg** [comment]
Come on Xiaomi, you have to release the kernel sources.

**Comment by ghost** [comment]
We all need kernel sources!

**Comment by AayushRd7** [comment]
Kernel Sources!...cmon it's a snap device :-1:

**Comment by anthyava** [comment]
Come on Xiaomi release  the kernel source

**Comment by blues-man** [comment]
I don't think they'll ever read/care about this post, the only thing is vote massively on miui forum poll about releasing kernel source for mi5:
http://en.miui.com/forum.php?mod=viewthread&tid=277143

**Comment by arter97** [comment]
Congratulations Xiaomi, you guys just made me to forcefully switch to OnePlus :D

**Comment by anarkia1976** [comment]
The same, for this reason i have switched to wileyfox. ;)

**Comment by Nimrodsv** [comment]
I was ---><--- close to buy MI5, saw no kernel source until now -> will buy other device

**Comment by faust93** [comment]
Heh.. Have stepped into this shit once with buying "mipad one".. Xiaomi? Never again!

**Comment by ghost** [comment]
Xiaomi, please release the kernel sources as required by law.

**Comment by teknoraver** [comment]
release the sources NOW

**Comment by BhSourav** [comment]
Source

**Comment by Termynat0r** [comment]
I can't believe that this doesn't get prosecuted...

**Comment by faust93** [comment]
Community should find out license advocates and sue xiaomi for GPL violations

**Comment by teknoraver** [comment]
In China? lol

**Comment by cmantas** [comment]
:+1

**Comment by h2o64** [comment]
Xiaomi kept their engagement 5 months later.

**Comment by akca** [comment]
Please update the kernel sources regularly. You just released once, but never updated. Please update the sources, respect your users Xiaomi! We want sources for Nougat!
