### ISSUE TITLE
----

### ISSUE THREAD

**Issue by matahbey** [MiCode/Xiaomi_Kernel_OpenSource#3961]
----

**Comment by qwertyuiii-code** [comment]
Tree make other devs)

**Comment by qwertyuiii-code** [comment]
Tree make other devs)

**Comment by imb-work** [comment]
Please release the kernel source code for our device, respect the GPL license.

**Comment by cies** [comment]
There are more issues like this here: https://github.com/MiCode/Xiaomi_Kernel_OpenSource/issues/4024
