### ISSUE TITLE
编译小米 9Pro 5G [crux] 内核 出错，总是提示这个文件有语法错误

### ISSUE THREAD

**Issue by coachpo** [MiCode/Xiaomi_Kernel_OpenSource#4034]

**Comment by dajumaomao** [comment]
![image](https://user-images.githubusercontent.com/12790403/226169602-c647a98d-4d44-49aa-a1bc-8fefe1a83b4e.png)
换虚拟机也不成，彻底失望 😭😭😭😭

**Comment by lateautumn233** [comment]
dts/vendor/qcom
不是dts/qcom










lateautumn
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月19日(周日) 晚上6:34
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [MiCode/Xiaomi_Kernel_OpenSource] 编译小米 9Pro 5G [crux] 内核 出错，总是提示这个文件有语法错误 (Issue #4034)




 

 换虚拟机也不成，彻底失望 😭😭😭😭

**Comment by dajumaomao** [comment]
> dts/vendor/qcom 不是dts/qcom lateautumn ***@***.***
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年3月19日(周日) 晚上6:34 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [MiCode/Xiaomi_Kernel_OpenSource] 编译小米 9Pro 5G [crux] 内核 出错，总是提示这个文件有语法错误 (Issue #4034) 换虚拟机也不成，彻底失望 😭😭😭😭 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

呃，我是按照wiki操作的，请问这个路径在哪里配置

**Comment by dajumaomao** [comment]
![image](https://user-images.githubusercontent.com/12790403/226174773-ed77819a-9be4-4aab-8dce-4eeb62071ea1.png)
用mi9  cepheus-p-oss  测试了一下 同样的错误。
烦请大佬指正。。

**Comment by Gah0** [comment]
https://github.com/MiCode/kernel_devicetree
不知道你想解决什么问题，syntax error说明是语法问题，可以自己改改再次make，可以看看crux相关开源上是如何链接dtbo。

**Comment by dajumaomao** [comment]
> https://github.com/MiCode/kernel_devicetree

我看了这个链接，里面没有小米的 crux-p-oss，能否提供更多帮助？，谢谢！
