### ISSUE TITLE
Please release Kernel source code for Redmi K60/K50U

### ISSUE THREAD

**Issue by dacancc** [MiCode/Xiaomi_Kernel_OpenSource#4037]
So long time, Please release Kernel source code for Redmi K60/K50U, thanks.

**Comment by mbahakeskin** [comment]
Agreed, please release it. This phone definitely needs kernel source.

**Comment by ghost** [comment]
Meh it should have been released already nvm. Please release it

**Comment by Theregularninja1** [comment]
Please release k50 ultra source code I'm going to buy the phone soon

**Comment by dacancc** [comment]
guys，poco f5 pro（k60） will be release in India 
the kernel will be release，together，maybe

**Comment by Rockybroo** [comment]
> guys，poco f5 pro（k60） will be release in India the kernel will be release，together，maybe

Do you have any idea when it could be released? Poco F5 has been released for a while in India
