### ISSUE TITLE
[Resolved] redmi note 4 Pro (mido) kernel source

### ISSUE THREAD

**Issue by DroidThug** [MiCode/Xiaomi_Kernel_OpenSource#422]
Mind releasing the sources for mido? @hehao

**Comment by soubhik-khan** [comment]
+1

**Comment by SwapnilSoni1999** [comment]
please provide kernel sources as soon as possible xiaomi...

**Comment by ghost** [comment]
+1

**Comment by Jhyrachy** [comment]
+1

**Comment by luk1337** [comment]
@Jhyrachy leaving +1 here does nothing. Also nice to see you on the Mi side :3

**Comment by Jhyrachy** [comment]
oh, hi @luk1337 !
i know it's worth nothing to +1, but it's not like it hurts to try

Thanks for the welcome :3

**Comment by SenseiTalking** [comment]
+

**Comment by ghost** [comment]
WHERES THE SAUCE

**Comment by DroidThug** [comment]
In PIZZA HUT!

**Comment by ghost** [comment]
Xiaomi alr performs well on the sd625...but with some kernel tweaks/updates and some optimisations this device is __BEAST__

**Comment by ksaha82** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/mido-m-oss

**Comment by DroidThug** [comment]
Thanks @hehao
