### ISSUE TITLE
Errors while compiling spes-r-oss branch

### ISSUE THREAD

**Issue by PavelAtr** [MiCode/Xiaomi_Kernel_OpenSource#4236]
Please help me get rid of compilation errors at the final stage of spes-r-oss branch.

WARNING: EXPORT symbol "gsi_write_channel_scratch" [vmlinux] version generation failed, symbol will not be versioned.

drivers/gpu/drm/drm_sysfs.o: In function `doze_backlight_store':
/home/pavel/xiaomi-spesn/kernels/linux-source-4.19.157-tiny/drivers/gpu/drm/drm_sysfs.c:350: undefined reference to `dsi_bridge_disp_set_doze_backlight'

drivers/gpu/drm/drm_sysfs.o: In function `doze_backlight_show':
/home/pavel/xiaomi-spesn/kernels/linux-source-4.19.157-tiny/drivers/gpu/drm/drm_sysfs.c:359: undefined reference to `dsi_bridge_disp_get_doze_backlight'

drivers/gpu/drm/drm_sysfs.o: In function `mipi_reg_store':
/home/pavel/xiaomi-spesn/kernels/linux-source-4.19.157-tiny/drivers/gpu/drm/drm_sysfs.c:318: undefined reference to `dsi_display_mipi_reg_write'

drivers/gpu/drm/drm_sysfs.o: In function `mipi_reg_show':
/home/pavel/xiaomi-spesn/kernels/linux-source-4.19.157-tiny/drivers/gpu/drm/drm_sysfs.c:310: undefined reference to `dsi_display_mipi_reg_read'

drivers/input/touchscreen/nt36525b_spi/nt36xxx.o: In function `lct_nvt_tp_gesture_callback':
/home/pavel/xiaomi-spesn/kernels/linux-source-4.19.157-tiny/drivers/input/touchscreen/nt36525b_spi/nt36xxx.c:2918: undefined reference to `set_lcd_reset_gpio_keep_high'

/home/pavel/xiaomi-spesn/kernels/linux-source-4.19.157-tiny/drivers/input/touchscreen/nt36525b_spi/nt36xxx.c:2912: undefined reference to `set_lcd_reset_gpio_keep_high'

drivers/thermal/thermal_core.o: In function `thermal_exit':
/home/pavel/xiaomi-spesn/kernels/linux-source-4.19.157-tiny/drivers/thermal/thermal_core.c:1997: undefined reference to `drm_unregister_client'

drivers/thermal/thermal_core.o: In function `thermal_init':
/home/pavel/xiaomi-spesn/kernels/linux-source-4.19.157-tiny/drivers/thermal/thermal_core.c:1972: undefined reference to `drm_register_client'

**Comment by Guilher89** [comment]
where did you find the build guide for spes-r-oss? i need it, please help me

**Comment by PavelAtr** [comment]
I copy /techpack directory from
https://github.com/PixelExperience-Devices/kernel_xiaomi_sm6225.git
repository. And then build kernel.

вс, 20 авг. 2023 г. в 18:23, Guilher89 ***@***.***>:

**Comment by Guilher89** [comment]
thank you so much, i'm using pixel experience too

Em dom., 20 de ago. de 2023 13:13, Pavel Samsonov ***@***.***>
escreveu:

**Comment by Guilher89** [comment]
did you manage to compile?, I need your knowledge could you tell me which configuration you used and which tool you used?

**Comment by PavelAtr** [comment]
Email me pvsamsonov76@gmail.com
