### ISSUE TITLE
Touch Panel not working on Redmi 3 (ido)

### ISSUE THREAD

**Issue by Anik1199** [MiCode/Xiaomi_Kernel_OpenSource#45]
With given defconfig if i compile kernel it boots but TouchPanel isn't working for ido. I compared dtbs with stock and it seems fine. I think the problem is in FocalTech Touch Panel driver. By watching dmesg it seems ft5x06 driver isn't initializing properly. Sensor too i guess? Did you guys checked source that it is working or not before pushing?

**Comment by jawircodes** [comment]
touch screen  not work using wt88047-perf_defconfig

**Comment by Anik1199** [comment]
Its fixed now :) Pull latest changes and try to rebuild.

**Comment by jawircodes** [comment]
not workong for redmi2

**Comment by jawircodes** [comment]
not work for redmi2
