### ISSUE TITLE
Please open Redmi note 12 5G Device trees and Kernel sources

### ISSUE THREAD

**Issue by ykla** [MiCode/Xiaomi_Kernel_OpenSource#4679]
Redmi note 12 5G Device trees and Kernel sources

sunstone

**Comment by vitivattXD** [comment]
> Redmi note 12 5G Device trees and Kernel sources
> 
> sunstone

Please release kernel source for sunstone

**Comment by chengnan049** [comment]
Please release kernel source for sunstone

**Comment by magnet1215** [comment]
强烈要求开源sunstone
