### ISSUE TITLE
关于 Redmi Note 12T Pro (pearl) 的开源请求

### ISSUE THREAD

**Issue by ChenDaojun** [MiCode/Xiaomi_Kernel_OpenSource#4761]
请开放此设备的内核源码，谢谢

**Comment by ChenDaojun** [comment]
感谢小米开放此设备的内核源码， 十分感谢😘😘😘

**Comment by fswy600** [comment]
你编译成功了吗，有没有编译成功的，我编译各种错误，我感觉pearl_defconfig有问题

**Comment by lcd-Cota** [comment]
即便是编译成功了，刷入有办法正常开机吗，我已将 redmi note 12t pro 解锁，刷入 magisk patch 过的 boot.img，之后便是bootloop，刷入 vbmeta.img 有加参数 --disable-verity 跟 --disable-verification，但它似乎仍然会做 AVB，有没有大神知道怎么将它的 AVB 关闭的，感激不尽!

**Comment by RamSong** [comment]
开放了吗

**Comment by reigadegr** [comment]
小米的avb不校验boot，不然刷个magisk也会boot loop
