### ISSUE TITLE
redmi 3s (land) kernel source

### ISSUE THREAD

**Issue by zwliew** [MiCode/Xiaomi_Kernel_OpenSource#54]
nice device; mind uploading the kernel source asap? thanks :)

**Comment by sachinssaxena** [comment]
+1

**Comment by hewz** [comment]
+10000

**Comment by ghost** [comment]
Yes
It's necessary.

**Comment by LKseven** [comment]
source source source

**Comment by bullik01** [comment]
Yes. We need kernel sources 4 land.

**Comment by jesuscea** [comment]
I agree too, we need kernel sources for Redmi 3S please :+1:

**Comment by hewz** [comment]
miui sucks.. we need kernel files for land

**Comment by LiberteCzech** [comment]
Please observe the conditions of the GPL and release resources.
There will also be a greater chance for the customer buys.

**Comment by Whatitat1930** [comment]
This needs to happen, come on Xiaomi! If this kernel sources, it will be flying off the shelves

**Comment by sheshuv** [comment]
Kernel source please?

**Comment by Fairsti** [comment]
Plz release kernel sources!

**Comment by zetrozky** [comment]
Kernel sources so that we can build CM and aospa for Land/3S Prime please!

**Comment by Arun19** [comment]
+1

**Comment by IITiti92II** [comment]
Xiaomi please release kernel source!

**Comment by rigaz29** [comment]
https://wiki.codeaurora.org/xwiki/bin/QAEP/release msm8937_64

**Comment by Panyoujies** [comment]
+n+1

**Comment by Panyoujies** [comment]
https://github.com/Silentlys/android_device_xiaomi_land

**Comment by zxc135781** [comment]
+1

**Comment by ghost** [comment]
Yes... We need the source

**Comment by rodsayd** [comment]
Please the sourcee

**Comment by denysyankiv** [comment]
+1

**Comment by adityathakur-ast** [comment]
+1

**Comment by pavelsr** [comment]
+1

**Comment by dan-man** [comment]
need this

**Comment by niki-timofe** [comment]
+1

**Comment by skrz23** [comment]
the sources

**Comment by xdarknet** [comment]
Hope the kernel source release this month

**Comment by zetrozky** [comment]
I think cm is starting to build for this device,,, They're waiting for the kernel sources... Found this on CodeAurora: https://wiki.codeaurora.org/xwiki/bin/QAEP/release

Search msm8937_64 on the page.

**Comment by HridayHS** [comment]
+1

**Comment by busote** [comment]
Yes. We need kernel sources 4 land.

**Comment by crissdua** [comment]
We need kernel please

**Comment by develmusa** [comment]
+1

**Comment by one-2-z** [comment]
+1

**Comment by gangadharKorrapati** [comment]
+1

**Comment by boudle** [comment]
+1

**Comment by ttkea** [comment]
请开源，谢谢

**Comment by supercairos** [comment]
I tried to do my own, but I seams to have some minor issues. 
https://github.com/supercairos/android_kernel_xiaomi_msm8937/

**Comment by np20feb** [comment]
+1 ...asap

**Comment by ashishmalgawa** [comment]
+1

**Comment by ferybiersack** [comment]
+1

**Comment by wangyangdahai** [comment]
**redmi 3X** kernel source **!!!!!**

**Comment by anomalchik** [comment]
+1

**Comment by Lautta17** [comment]
+1... Please

**Comment by diparthshah** [comment]
+∞

**Comment by rjody** [comment]
please release it ASAP so we can have further development of this lovely device

**Comment by LiberteCzech** [comment]
Xiaomi observe the open GPL license!

**Comment by m0eter** [comment]
Yep, about time to release the sources already. C'mon, do it.

**Comment by ttkea** [comment]
pls

**Comment by 0PED1A** [comment]
Nothing yet...!! :-(

**Comment by charansai612** [comment]
Release It AsAp :)

**Comment by DroidThug** [comment]
LA Xiaomi! Do it fast, ya Thug!

Or do you wanta formal GPL Notice now?

**Comment by ptmaroct** [comment]
Do it boi

**Comment by mkreja** [comment]
+1
yes!

**Comment by SayanAcharya** [comment]
Pls release the sources for further development purposes...

**Comment by phoenixprojects** [comment]
Xiaomi pls release the kernel sources. Enough already

**Comment by DroidThug** [comment]
Anyone who'd like to help me in achieving an EFF backing?

**Comment by LiberteCzech** [comment]
_https://www.change.org/p/publish-the-kernel-source-for-the-xiaomi-redmi-3s-prime-3x?recruiter=601727891&utm_source=share_petition&utm_medium=copylink_
**Petition for the release of the kernel source of the Redmi 3S/Prime/3X**
Please sign it

**Comment by harrzz** [comment]
Yes, please release the kernel sources for the Redmi 3s

**Comment by imamnrchls** [comment]
We need the kernel source for the Redmi 3s,please release it!

**Comment by mohdmujahidansari526** [comment]
please release the Kernel Source for Redmi 3S Prime.

**Comment by sandsbit** [comment]
We need source pls!!!

**Comment by k3a** [comment]
Yes, I like the device but won't buy it until kernel sources are released!

**Comment by DenHafiz69** [comment]
Please release it so developers can build CM rom :+1:

**Comment by k3a** [comment]
He Hao (何浩) who manages this repo said by e-mail it has been included in the plan, and plan to open Redmi 3S kernel source is next month. Fingers crossed. :)

**Comment by ghost** [comment]
wow
that's great.

2016年11月18日 下午4:31于 K3A notifications@github.com写道：

He Hao (何浩) said it has been included in the plan, and plan to open Redmi 3S kernel source in next month. Fingers crossed. :)

**Comment by np20feb** [comment]
@k3a...hope they hold true to their words !!

**Comment by adil5233** [comment]
@k3a 
from  where you got the info?
source? :p

**Comment by k3a** [comment]
Source: I asked him by email and he responded, so I shared it with others.

**Comment by jagdishphadke** [comment]
Lets hope that xiaomi will do it soon

**Comment by legion111** [comment]
3s

**Comment by legion111** [comment]
Hope they will release kernel source of redmi 3s prime soon

**Comment by ghost** [comment]
I think miui won't let us down.

2016年11月19日 下午2:42，"Tanmay (Legion)" notifications@github.com写道：

Hope they will release kernel source of redmi 3s prime soon

**Comment by DroidThug** [comment]
Nice news! Would be great!

**Comment by legion111** [comment]
Any Proof k3a ?? How Can We Believe That They Are Releasing Source Next Month

**Comment by legion111** [comment]
Please send mail screenshot For The Satisfaction Of Redmi 3s Prime Owners :) waiting for your reply thanks....

**Comment by adil5233** [comment]
Ya scrnsht will be nice for satisfaction :D

**Comment by k3a** [comment]
![screenshot 2016-11-20 11 23 24](https://cloud.githubusercontent.com/assets/966992/20462120/16cff58c-af14-11e6-9b24-0ba7532bca1d.png)

Here are full email headers :) http://pastebin.com/S6zmFVAa

Hopefully he will fulfill his promise!

**Comment by imamnrchls** [comment]
@k3a seems to be good

**Comment by ashishmalgawa** [comment]
Let's hope for the best

**Comment by DroidThug** [comment]
nice @k3a

**Comment by legion111** [comment]
Thanks k3a :)

**Comment by DeckardShaw** [comment]
![Uploading Screenshot_2016-11-21-12-38-06-660_com.google.android.gm.png…]()
one more proof 😁 i also got the same reply from hehao.

**Comment by DeckardShaw** [comment]
here's one more proof i also got the same reply from hehao

**Comment by ashishmalgawa** [comment]
I also got the same reply

**Comment by adil5233** [comment]
same here 😁

**Comment by k3a** [comment]
F*ck people, the reason I shared it is so that you won't bother him too and let him work so that he can manage to release it. If everyone writes to him he will be busy responding, not having time for the actual work! So please sit tight and be patient. Let's complain again one month from now :P

**Comment by ashishmalgawa** [comment]
I don't understand...all he needs to do is upload the already completed
code..why does he need 1 month to do that

**Comment by k3a** [comment]
Good question. I've read somewhere that they had some code for furure devices in some kernel source and they had to remove it in order not to reveal more details about those devices. I don't know if that applies to this case too. 

Something like polishing / cleaning the code may be the reason. But it's my guess.

**Comment by legion111** [comment]
All the people's are requested to not to mail he hao many times

**Comment by legion111** [comment]
Let's wait 
Cm14.1 Device Tree By Zweliew Thanks To him may be within some days we Will get cm14.1 😍😍

https://github.com/zwliew/android_device_xiaomi_land/tree/cm-14.1?files=1

**Comment by ghost** [comment]
wow
You guys are so cute.

$B:_(B 2016$BG/(B11$B7n(B21$BF|(B $B2<8a(B5:51$B!$(B"Tanmay (Legion)" <notifications@github.com>$B<LF;!'(B

Let's wait
Cm14.1 Device Tree By Zweliew Thanks To him may be within some days we Will get cm14.1 ????

https://github.com/zwliew/android_device_xiaomi_land/tree/cm-14.1?files=1

##

**Comment by legion111** [comment]
Waiting......

**Comment by frapeti** [comment]
The release of the kernel source is so relevant at the time of choosing a new phone, if I had to say anything negative about Xiaomi may be this waiting time and this makes me think twice before buying a Xiaomi phone again.

**Comment by ljmf00** [comment]
+10000

**Comment by legion111** [comment]
Yup @frapeti you're right

**Comment by legion111** [comment]
@k3a any news about Kernel Source ??

**Comment by legion111** [comment]
@zwliew you build cm14.1 device tree fir Redmi 3s prime when you're compiling rom ??

**Comment by pavan3999** [comment]
any news about kernel

**Comment by legion111** [comment]
@pavan3999 no may be we will get this month

**Comment by WtfJoke** [comment]
Please dont use this issue thread as a forum. Only write something if you have something to contribute.
Instead of posting +1 or something like that, use the "Add your reaction" button to give the person a thumbs up.

I struggled with posting this, because my comment is useless in the same way, but this issue turned more into spam than something else.

**Comment by adil5233** [comment]
#RIP_GPL

**Comment by legion111** [comment]
RIP Xiaomi #RIP_GPL

**Comment by DroidThug** [comment]
Lol. CAF is all we have then

**Comment by eebssk1** [comment]
+1什么的。。。。都是中国人吧。。。
内核源码Codeaurora上有啊。。。。。。。。。。。。

**Comment by legion111** [comment]
release source @hehao

**Comment by eebssk1** [comment]
The hehao you are always @ is not a member of MIUI team.And he's not working for Xiaomi.
it's better for you to send email to the real "hehao".

/*Sorry for my bad English.*/

**Comment by eebssk1** [comment]
@eebssk1
hehao@xiaomi.com

**Comment by legion111** [comment]
@eebsskk1 im sending to hehao@xiaomi.com -___- i know so please dont tell

**Comment by hellripper545** [comment]
+n^n^n=n 
please upload the **kernel sources** of **land**. 
Development is lacking due to this issue.
Thank you.

**Comment by anubis5555** [comment]
I hope release kernel source soon if not my redmi 3s will be sold. Waiting and waiting so fustrating havent stable cm roms. Phone is good but rom most important for me, next I will buy phone with lot of custom roms opportunity!

**Comment by arguser** [comment]
It has been published by Xiaomi that it would be released this month, as 31/12/2016 we see no changes! It could happen on January 2017, if not we should make another formal petition.

**Comment by zwliew** [comment]
Thanks for the release, hehao! It wasn't my intention to cause a huge amount of spam on you and your work email, so hopefully it'll all stop now :)

Link to kernel source:
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/land-m-oss
