### ISSUE TITLE
need help 

### ISSUE THREAD

**Issue by Hamood111** [MiCode/Xiaomi_Kernel_OpenSource#5903]
I'm using mi 11 ultra and I want to flash custom kernel so I can use kernelsu app but Idn how to download or how to flash it I have TWRP I just need guidance thanks

**Comment by i1l8h0a2m** [comment]
> I'm using mi 11 ultra and I want to flash custom kernel so I can use kernelsu app but Idn how to download or how to flash it I have TWRP I just need guidance thanks

Why you ask here? Go to the devices spesific forum
