### ISSUE TITLE
[APPEAL] Release FULL KERNEL SOURCE FOR MARBLE (POCO F5 / REDMI NOTE 12 TURBO)

### ISSUE THREAD

**Issue by pikawee** [MiCode/Xiaomi_Kernel_OpenSource#5915]
Dear Xiaomi Officials,

We, the users and custom ROM community, express our concerns regarding the incomplete (half-baked) June release by @Jshengyin (marble-s-oss). We believe this release does not meet essential requirements for effective device development.

As open source enthusiasts, we believe in upholding GPL rules. We appreciate Xiaomi's commitment to open source development and request your support in releasing complete sources as per the GPL rules. Open source thrives on collaboration, accountability, and transparency. Complete sources empower developers, foster innovation, and enhance user experiences.

We understand the challenges in managing and releasing source codes, but comprehensive and accurate availability is crucial for developer and user satisfaction. Please prioritize the release of complete sources to enable remarkable custom ROMs.

By adhering to open source principles, Xiaomi can strengthen its reputation and user trust. We await a positive response and hope Xiaomi sets a benchmark for other manufacturers.

Thank you for your commitment to open source development. We eagerly anticipate your response and look forward to collaboration.

Sincerely,
POCO F5 / REDMI NOTE 12 TURBO COMMUNITY
Official Telegram Chat: t.me/POCOF5_official

![image](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/assets/90617898/3627f03e-e24b-4c7d-9c9f-8597b5586870)

**Comment by 2036648790** [comment]
请发布完整源代码

**Comment by freeslam** [comment]
How can we hope for good customs roms and our Poco F5 to last longer if you don't give a us a proper kernel source and vendor ! I know you can do better !

**Comment by Sabbir2k15** [comment]
Please Release ASAP

**Comment by hibreck** [comment]
Please

**Comment by imsahilansarii** [comment]
Please release

**Comment by thanveeralisayed** [comment]
Yes. Please release the full kernel sources for poco f5 / Redmi note 12 turbo. (Marble)

**Comment by keijiyuy** [comment]
Please release the full kernel sources for poco f5 (Marble), everybody wait for this.

**Comment by BeancurdDrifter** [comment]
I've been waiting for an official LineageOS for the F5 before I upgraded from my F3
Please release the full kernel sources so the can be a chance for an official LineageOS release.

**Comment by luoxuxi** [comment]
full kernel sources plz

**Comment by UnFunnyGuy** [comment]
Please Release Kernel Source ffs

**Comment by Sudeepxl20** [comment]
Release the source

**Comment by t01h01** [comment]
Release source plz

**Comment by 2907727365** [comment]
发放完整的源码

**Comment by Mustafarexdo** [comment]
Please Release the full source

**Comment by Mohitshakya81** [comment]
Please Release full kernel source

**Comment by Chizkayk** [comment]
Full kernel source?🥺

**Comment by nimbold** [comment]
Any news?

**Comment by freeslam** [comment]
Nothing yet ? Common guys we want full support for this device !

**Comment by Satyam709** [comment]
Release full kernel source
