### ISSUE TITLE
Please Update Mi5 kernel source code

### ISSUE THREAD

**Issue by sobuj53** [MiCode/Xiaomi_Kernel_OpenSource#648]
I humbly request the developer of xaiomi to update the Mi5 kernel source. Mi5 is an awesome device and with updated kernel source user can do much more with it.

**Comment by GuaiYiHu** [comment]
So is xiaomi note lte.

**Comment by lkthomas** [comment]
correct me if I am wrong, but Kernel isn't something you want to update everyday, it's basically the interface between software and hardware, if hardware don't change, why kernel need to change?

**Comment by Coioidea** [comment]
@lkthomas but it's necessery to update if the sources isn't perfect now.And it must follow the latest Android feature.In my opinion the best example for phone company is Google Nexus5.Its kernel update continued for sever years!!!
