### ISSUE TITLE
Mido Kernel Sources

### ISSUE THREAD

**Issue by ghost** [MiCode/Xiaomi_Kernel_OpenSource#660]
你们要等多久才要巴小米n4的 kernel source公开？你们用了linux kernel source, 无论如何都应该早日公开，不公开是在在违反gpl规则。这个source code是大家的权利，你们要等到几时才会配合？

**Comment by ghost** [comment]
每次都 “你们等多几天”
大家已经等了半年了你们可以醒醒吗？

**Comment by ghost** [comment]
for those who dont understand wtf i just typed use the translator or your inference skillz plox

**Comment by ghost** [comment]
"the terms of the adhered GPLv2 license call for immediate distribution of the sources"
we waited for half a year

**Comment by isjerryxiao** [comment]
+1, but I don't think shouting here has a great effect.

**Comment by sanghyangsahal** [comment]
My eyes 😵😵😵😄

**Comment by isjerryxiao** [comment]
@alamo18 Close this issue since kernel source has been out.
