### ISSUE TITLE
psyche-r-oss OIS (optical image stabilization) not working, push changes for camera tech-pack.

### ISSUE THREAD

**Issue by Moonlight4004** [MiCode/Xiaomi_Kernel_OpenSource#6600]
-Missing camera changes for OIS specific to Xiaomi 12x and 4.19 kernel

**Comment by Hunte060708** [comment]
I really hope they fix this

**Comment by Hunte060708** [comment]
Why did you close the post? is the problem solved?

**Comment by Moonlight4004** [comment]
> Why did you close the post? is the problem solved?

Yes partially, OIS is fixed but EIS remain still broken.
