### ISSUE TITLE
dtc必须来自aosp源码（pie-release） 这个是什么意思呢 

### ISSUE THREAD

**Issue by liumengdeqq** [MiCode/Xiaomi_Kernel_OpenSource#6607]
dtc必须来自aosp源码（pie-release）

**Comment by liumengdeqq** [comment]
aosp [pie-release）分支 arch/arm64/boot/dts下面文件替换小米对应的目录？

**Comment by dirt2022** [comment]
> aosp [pie-release）分支 arch/arm64/boot/dts下面文件替换小米对应的目录？



> aosp [pie-release）分支 arch/arm64/boot/dts下面文件替换小米对应的目录？

In fact , apt install device-tree-compiler -y.
Then export DTC_EXT=/usr/bin/dtc
It will also work correctly
