### ISSUE TITLE
Release kernel source for mido.

### ISSUE THREAD

**Issue by RaviKumawat** [MiCode/Xiaomi_Kernel_OpenSource#664]
Maa ke lodo, behen ke taka, madarchodo batao kernel source kab release kar rhe ho.

Releasethe kernel source asap and providean ETa of the releasr you fucking lazy assholes and cunts. You and your fucking lazy team of devs who does nothing except for writingwriting changelogs, at lealeast you can release the kernel source so wwe can do something by ourseleves. Stop fucking your mother and do some work.

**Comment by luk1337** [comment]
ayyyyyyyyyyyyyyyyyyyy lmao~

**Comment by TheScarastic** [comment]
wtf....
