### ISSUE TITLE
But my make failed

### ISSUE THREAD

**Issue by dksslq** [MiCode/Xiaomi_Kernel_OpenSource#667]
kernel/sysctl_binary.c:140:13: error: ‘KERN_BOOT_REASON’ undeclared here (not in a function)
  { CTL_INT, KERN_BOOT_REASON,  "boot_reason" },
             ^~~~~~~~~~~~~~~~
kernel/sysctl_binary.c:527:13: error: ‘NET_IPV6_ACCEPT_RA_PREFIX_ROUTE’ undeclared here (not in a function)
  { CTL_INT, NET_IPV6_ACCEPT_RA_PREFIX_ROUTE, "accept_ra_prefix_route" },
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Is that my problem of operation？？How can I compile successfully?

**Comment by dksslq** [comment]
the error is in scorpio-m-o

**Comment by GuaiYiHu** [comment]
which device

**Comment by dksslq** [comment]
xiaomi 5s plus

**Comment by harrynowl** [comment]
What toolchain?

**Comment by dksslq** [comment]
this
http://releases.linaro.org/components/toolchain/binaries/6.3-2017.02/aarch64-linux-gnu/gcc-linaro-6.3.1-2017.02-x86_64_aarch64-linux-gnu.tar.xz

**Comment by dksslq** [comment]
I also failed to compile the code on https://github.com/LineageOS/android_kernel_xiaomi_msm8996

There may be a problem with the source's configuration

**Comment by dksslq** [comment]
how shuld I configuration it?

**Comment by GuaiYiHu** [comment]
Good luck.

**Comment by harrynowl** [comment]
Use the 4.9 toolchain from google, I bet  it works. Alternatively you probably need to look at something like: https://github.com/Gateworks/linux-imx6/commit/b2d3c9bd93962b8c7cf69387fbaadc2909ec1787

**Comment by dksslq** [comment]
thank you~I am going to try again。
