### ISSUE TITLE
Release MI 6 [sagit] kernel sources

### ISSUE THREAD

**Issue by AntonyLeons** [MiCode/Xiaomi_Kernel_OpenSource#672]
by modifying and distributing GPL software, this has to comply with the GPL terms, in this case GPLv2. And therefore this I kindly request you release kernel sources otherwise this would be copyright infringement.

**Comment by rancidfrog** [comment]
Shame,
Phone not released yet, but they have repo prepared: https://github.com/OnePlusOSS/android_kernel_oneplus_msm8998

Maybe Xiaomi should follow example
