### ISSUE TITLE
release mi6(sagit) kernel source!!!

### ISSUE THREAD

**Issue by notly** [MiCode/Xiaomi_Kernel_OpenSource#693]
For GPL (2017/8/2)

**Comment by Verevka** [comment]
Are there any known approximate dates?

**Comment by luk1337** [comment]
@Verevka something between 2017-2099.

**Comment by marines** [comment]
@luk1337 asks for your useless comment.

**Comment by notly** [comment]
@Verevka  I think Xiaomi will release the kernel source after the device was out about six months later;
So if it's something is not wrong, about 2017/10/1 -31, maybe early

**Comment by ivanhtp** [comment]
There is a new branch for sagit...
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/sagit-n-oss 
does this mean something?

**Comment by marines** [comment]
Those are the sources, @ivanhtp

**Comment by ivanhtp** [comment]
That's cool right? Closed issue?

**Comment by notly** [comment]
@Verevka kernel source finally opened.
Have fun with Xiaomi6
