### ISSUE TITLE
Asshole, My Xiaomi

### ISSUE THREAD

**Issue by notly** [MiCode/Xiaomi_Kernel_OpenSource#695]
GPL or Go to hell

**Comment by luca020400** [comment]
So you have a Xiaomi in your asshole? Better go and check with a doctor in this case

**Comment by luk1337** [comment]
These GPL cultists are funny.

**Comment by mr-cn** [comment]
就服你

**Comment by notly** [comment]
@mr-cn  舅服你好吧
