### ISSUE TITLE
Release the Kernel Source for Xiaomi Redmi 4X (Santoni)

### ISSUE THREAD

**Issue by ghost** [MiCode/Xiaomi_Kernel_OpenSource#698]
Hi, please hear us, we need Kernel Source for Santoni and i want to do a development for this device. Redmi 4X is a great phone now and so many people using and loving it! Redmi Note 4X has 4 months for waiting the Kernel Source and you released the Kernel Source for it. And for Redmi 3 too. Then, why you must delayed Kernel Source for Xiaomi Redmi 4X? Its been 5 months we've been waiting for Kernel Source release! Please hear us Xiaomi! You are the best!

Thank you!

**Comment by luca020400** [comment]
Tip: Xiaomi is not the best, just because you're here asking for the release.

**Comment by luk1337** [comment]
5 months? As a Xiaomi fan you can wait up to 18 months ^.^

**Comment by luca020400** [comment]
Best i can do is 6 months.

**Comment by notly** [comment]
Make it be never!!!

**Comment by ghost** [comment]
I want to make Custom Kernel!!!!!

**Comment by luca020400** [comment]
Add one more ! and the genius of the kernel will appear.

**Comment by ghost** [comment]
SHAME XIAOMI IF THEY DIDN'T RELEASE REDMI 4X KERNEL SOURCE!!!

**Comment by luk1337** [comment]
!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by luca020400** [comment]
Now you have 3 wishes, do wise choices.

**Comment by insidewhy** [comment]
You shouldn't have bought a phone made by the IP thieves at Xiaomi.

**Comment by ghost** [comment]
I don't need you here, so GTFO ,,

**Comment by luk1337** [comment]
lmao~

**Comment by ghost** [comment]
I've made this issues for Xiaomi, not for you James ,,

**Comment by luk1337** [comment]
@jawaadsaeed why do you always put space and two commas at the end of your sentences? What's the point of it?

**Comment by insidewhy** [comment]
You've kinda missed my point: Xiaomi have been violating the GPL for years, they are criminals who don't care about international copyright law. Your github issue is insignificant to them, pissing in the wind. The only way to get corporate monsters to change is to hit them in their wallets i.e. research your products and don't buy from criminals. Xiaomi are as likely to listen to you after you've been conned by them as a fake dealer is gonna give someone their money back after conning them. I know, getting hit by a criminal is not a nice feeling, but you gotta learn from it and get a bit more cynical.

**Comment by insidewhy** [comment]
There's a reason you had to buy your phone from some shitty internet third party reseller or the criminal's own "official" website.

The same way there's a reason why the dealer is yelling out "hot bud" next to a crowded train station and selling you "ganja" in a black bag (that's really parsley) for 20 dollars.

**Comment by ghost** [comment]
Thanks for that @ohjames
I understand now ,,

**Comment by insidewhy** [comment]
What is it with the " ,, "... maybe you enjoy looking like a 5 year old who just learned both internet and punctuation or something? Is that really gonna help Xiaomi take you seriously (or anyone else for that matter). Lol.

**Comment by ghost** [comment]
Don't take it too seriously lmao

**Comment by insidewhy** [comment]
We put up with your pointless insults and whining, we deserve to know.

**Comment by ghost** [comment]
Lmao xD

**Comment by SwapnilSoni1999** [comment]
we are here to hope that xiaomi 'may' release kernel source ...


and xiaomi be like: lmao dude ... what are you talking about...

**Comment by Lanados** [comment]
I understand it will not open the source for redmi 4x

**Comment by ghost** [comment]
Yeaa

**Comment by Lanados** [comment]
Bad

**Comment by Lanados** [comment]
whence such information

**Comment by Lanados** [comment]
Please, xiaomi, open kernel sources😭😭😭😭😭😭😭😭😭

**Comment by ghost** [comment]
Don't take too much hope on Xiaomi

**Comment by shatanid** [comment]
please Release source for redmi 4x

**Comment by M9k** [comment]
Still no source code, it's a GPLv2 violation.

**Comment by shatanid** [comment]
huh -_-

**Comment by julian-alarcon** [comment]
The new MIUI v9 is near to be released, and still no Source Code of Kernel. If they begin to sell Redmi 4X phones in Spain they should respect the GPLv2 license and release the code.

**Comment by notly** [comment]
XiaoMi: GPL? No Way!!!

**Comment by ghost** [comment]
Xiaomi is an esshole lol

**Comment by Riora** [comment]
HEY XIAOMI! it's a GPLv2 violation!!!

**Comment by luk1337** [comment]
cool

**Comment by Lanados** [comment]
I will never again buy a smartphone xiaomi with such an irresponsible developer, you are a fagot, burn in hell small Chinese with small members

**Comment by luk1337** [comment]
lmao

**Comment by ghost** [comment]
Hehehe

**Comment by ryan-andri** [comment]
lul

**Comment by ghost** [comment]
@ryan-andri im testing your kernel with unofficial source bro

**Comment by ryan-andri** [comment]
@jawaadsaeed sure, good luck mate :+1:

**Comment by julian-alarcon** [comment]
Related bugs:
- https://github.com/MiCode/Xiaomi_Kernel_OpenSource/issues/787
- https://github.com/MiCode/Xiaomi_Kernel_OpenSource/issues/767

Somebody should merge them. I guest main is 698 (older and more comments).

**Comment by julian-alarcon** [comment]
By the way, the are didn't release the kernel source for Xiami Mi A1 an Android One phone!
http://www.androidpolice.com/2018/01/16/xiaomi-still-hasnt-released-kernel-sources-mi-a1/
https://arstechnica.com/gadgets/2018/01/xiaomi-is-dragging-its-feet-on-the-gpl-again-this-time-with-the-mi-a1/

**Comment by luca020400** [comment]
Say hello to the new kernel issues sheriff: sir @julian-alarcon.

**Comment by ghost** [comment]
Issues closed! Source already released today!

**Comment by julian-alarcon** [comment]
Source code finally released:
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/commit/09baf1a3dd0e13a81e484035f0be71dcb2ecc723
