### ISSUE TITLE
please release kernel source code redmi 4a

### ISSUE THREAD

**Issue by muralivijay** [MiCode/Xiaomi_Kernel_OpenSource#779]
this device now have many users also 1 year old .. but still running marshmallow no nougat update ...so plaese release kernel source code  redmi 4A (ROLEX0. too build  rom as stable ....

**Comment by darshan1205** [comment]
sad

**Comment by kiodo1981** [comment]
I hope and soon release source for Redmi 4A (rolex)
https://www.change.org/p/xiaomi-inc-publish-the-kernel-source-for-the-xiaomi-redmi-4a-4-4pro

**Comment by Nibi-git** [comment]
I am also awaiting!
