### ISSUE TITLE
Release Kernel Source code for Xiaomi Redmi 4X

### ISSUE THREAD

**Issue by ghost** [MiCode/Xiaomi_Kernel_OpenSource#787]
Please Xiaomi release Kernel Source for Redmi 4X

**Comment by bugerxXx** [comment]
Yes Pleasee...

**Comment by peterius** [comment]
Still in progress but it's getting to init:
https://github.com/peterius/Xiaomi_Kernel_OpenSource_fbcon/tree/mido_fbcon

This is for the Note 4X though, but maybe it works as well?  There's all kinds of errors, even in the kernel provided with the phone.

**Comment by ghost** [comment]
@hehao

**Comment by ryan-andri** [comment]
so xiaomi not gentle as big company !

**Comment by bitrvmpd** [comment]
Hey, this one is based on CAF sources https://github.com/bitrvmpd/msm-3.18 =)

**Comment by ghost** [comment]
@bitrvmpd Yes bro we actually use your source for now on ❤ you are amazing

**Comment by peterius** [comment]
What's working with the bitrvmpd CAF kernel?  Am I duplicating his efforts?  Will it work on a Redmi Note 4X, radio, etc.?

**Comment by bitrvmpd** [comment]
@peterius everything is working (maybe for some people IR blaster won't work, but I need logs to fix that). And it's only for Redmi 4X (santoni)

**Comment by sahroni28** [comment]
Just wait long

**Comment by arizaini** [comment]
Goto https://forum.xda-developers.com/xiaomi-redmi-4x and u will find what u want

**Comment by ghost** [comment]
@arizaini We need official source to fix bugs on Oreo

**Comment by arizaini** [comment]
What kind of bug?

**Comment by semkir216** [comment]
NitrogenOS Oreo Stable released go to MIUI Forum visit my thread

**Comment by luk1337** [comment]
fuck off

**Comment by julian-alarcon** [comment]
Related bugs:
- https://github.com/MiCode/Xiaomi_Kernel_OpenSource/issues/698
- https://github.com/MiCode/Xiaomi_Kernel_OpenSource/issues/767

Somebody should merge them. I guest main is 698 (older and more comments).

**Comment by julian-alarcon** [comment]
By the way, the are didn't release the kernel source for Xiami Mi A1 an Android One phone!
http://www.androidpolice.com/2018/01/16/xiaomi-still-hasnt-released-kernel-sources-mi-a1/
https://arstechnica.com/gadgets/2018/01/xiaomi-is-dragging-its-feet-on-the-gpl-again-this-time-with-the-mi-a1/

**Comment by ghost** [comment]
Issues closed! Source already released today!

**Comment by julian-alarcon** [comment]
Source code finally released: 09baf1a
