### ISSUE TITLE
 Release kernel sources for Chiron

### ISSUE THREAD

**Issue by pdigennaro** [MiCode/Xiaomi_Kernel_OpenSource#804]
Please release kernel sources for the Chiron device (MIX 2).
GPL

**Comment by luca020400** [comment]
Just check if the fucking kernel has been already released.
Hint: IT IS.
Damnit

**Comment by aholstenson** [comment]
@luca020400 No need for swearing and being an asshole. If the sources are available it would be very helpful to provide a reference to where they can be found as there is no branch in this repository for `chiron`. That way requests for this device won't pop up again.

**Comment by pdigennaro** [comment]
@luca020400 I can only see some pieces of code in the sagit branch regarding MIX 2, but they are only hints... there's no defconfig for chiron. Maybe you can point the full chiron kernel code to us?

**Comment by TheStrix** [comment]
@pdigennaro It is full.. Use the same defconfig.

**Comment by pdigennaro** [comment]
@TheStrix this is a nice news! So I think I can close the issue then.
