### ISSUE TITLE
Please release kernel for Xiaomi Mi Max 2 (oxygen)

### ISSUE THREAD

**Issue by DustPanic** [MiCode/Xiaomi_Kernel_OpenSource#805]
Many peoples want to install custom firmware!
Please release kernel for mi max 2.
Thanks!

**Comment by toxavrn** [comment]
Please release kernel for Xiaomi Mi Max 2 (oxygen) +

**Comment by ghost** [comment]
Well then, fuck Xiaomi

**Comment by ryan-andri** [comment]
don't put your hope into xiaomi, just bought their device and then sell it for lower price.

**Comment by 123oleg1977** [comment]
ryan-andri
Unfortunately. I did the same, I sold my device and my wife and daughter also left, but I will also look for another brand after the new year, I know for sure that I will not return to this firm, I'm very sorry that they have such an attitude towards their customers, It's time to gain a reputation, but you can lose it in a moment ...

**Comment by luk1337** [comment]
My dog also left Xiaomi :^)

**Comment by DrWssn** [comment]
Plz realase the kernal

**Comment by rupansh** [comment]
Publish kernel source for 5a

**Comment by luk1337** [comment]
can you stop?

**Comment by DustPanic** [comment]
luk1337
No

**Comment by DustPanic** [comment]
Thank you Xiaomi! Published kernel!!!
