### ISSUE TITLE
Request for the release of the kernel source for the Mi Mix 2 (Chiron)

### ISSUE THREAD

**Issue by zoemaestra** [MiCode/Xiaomi_Kernel_OpenSource#812]
It's been several months since the announcement and release, which was the same time as the Mi Note 3 which has had its sources released. I'd say it's time for the Mix 2 to have its kernel source released.

**Comment by bgcngm** [comment]
Don't tell anyone, they already released it. See sagit branch.

**Comment by ryan-andri** [comment]
@benjimaestro you should look into sagit branch.

**Comment by zoemaestra** [comment]
I'm an idiot
