### ISSUE TITLE
incompleted kernel released by xiaomi (gucci)

### ISSUE THREAD

**Issue by pradeepvarma22** [MiCode/Xiaomi_Kernel_OpenSource#819]
xiaomi redmi note prime gucci 
kernel released in 2015 
but having many bugs and it is inclompleted as soon as possible take it serious and recompile or 

complete the kernel and need to get working drivers 
drivers are not working

**Comment by ghost** [comment]
what the point of spamming over and over, u got autism? it's probably why u got issues with the kernel

**Comment by pradeepvarma22** [comment]
while compiling the custom kernel its stoppped at target make drivers and so many bugs in this kernel

**Comment by pradeepvarma22** [comment]
this is the issue 


https://hastebin.com/avisorekih.rb

**Comment by adekmaulana** [comment]
that is your derp issues what the fuck, next time learn some C lang before you put issues lol
