### ISSUE TITLE
Please Release Kernel Source For Redmi 4A (rolex)

### ISSUE THREAD

**Issue by muralivijay** [MiCode/Xiaomi_Kernel_OpenSource#825]
How much days We are waiting for kernel source ? 1 year old device Redmi 4A stil Not released any Marshmallow or nougat Kernel source .. but you release kernel source for mi max 2 faster . what a cheating level Xiaomi. are you planing to broke GPLV2 ?

**Comment by Nibi-git** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by krasCGQ** [comment]
Code-Review-2
Verified-1

**Comment by ryan-andri** [comment]
lul

**Comment by dedejamaludin** [comment]
I believe @xiaomi will follow GPL rules. But why so long ago ? Its been  one year but kernel source still not release yet. What the LOL ???

**Comment by muralivijay** [comment]
@dedejamaludin beacause they forsing users keep stay with #shitmiui rom . now days miui rom not good for msm8917 chips. very laggy when, also poor ram managemant, ads coming from some mi apps like mi expolerer. according mi forum moderator says very redmi devices kernel source will be released after 1 Year. but actually redmi 4A lunched in nov 2016 . till they not relaesed

**Comment by MacTavishAO** [comment]
Release kernel source for Redmi 4A rolex. Xiaomi shouldn't keep rolex users away from developing.

**Comment by JNYCLVS** [comment]
Release the Kernel Source for Redmi 4A (Rolex), for further development and support for our device

**Comment by abdullatifreal** [comment]
Please release kernel source for Redmi 4A! We need it immediately! More than 1 year passed since the release of this device but still no kernel source!

**Comment by jnkcode** [comment]
already more than a year has not been released yet?

**Comment by dedejamaludin** [comment]
@muralivijay : i gave my $100 dollars to buy this device, why @xiaomi force me to lost more ???
Now i also gave my time at least one year without kernel source in my rolex, is there another shit ???

**Comment by krasCGQ** [comment]
Because it's Xiaom~~i~~eme

**Comment by sagwascript** [comment]
Is it takes time to publish kernel source ? Ok then give us a release date, we will wait for it. So that means you plan to publish it, but if you don't, it means you're never plan it to be published, and that's a problem.
So gives us the release date, a serious one, or if you have something to be discussed, we can discuss it here, be informative, we are good users :)

**Comment by ryan-andri** [comment]
ahh come on -__- dont cry please :(

**Comment by krasCGQ** [comment]
~~lol~~

**Comment by solocco** [comment]
Release kernel source for Redmi 4A rolex, for development our devices.

**Comment by raphielscape** [comment]
K nice meme

> Everyday we rant to Xiaomeme about Rolex, we want ETA Sauce, Sauce when, but Xiaomeme will be Xiaomeme, Xiaomeme is memelord, coz Xiaomeme is meme

So summary : No ketchup, Just sauce, Raw Sauce

**Comment by raphielscape** [comment]
K nice meme

> Everyday we rant to Xiaomeme about Rolex, we want ETA Sauce, Sauce when, but Xiaomeme will be Xiaomeme, Xiaomeme is memelord, coz Xiaomeme is meme

So summary : No ketchup, Just sauce, Raw Sauce

**Comment by krasCGQ** [comment]
~~lmfao~~

**Comment by sayan-tan** [comment]
Again the shit Xiaomi is violating gpl rules. Release kernel source for Rolex aka Redmi 4A now. Why you people don't understand that MIUI is not good for low RAM phones. We need further development.

**Comment by ghost** [comment]
Xiaomi should release their kernel source as soon as possible why they are doing I don't understand.

**Comment by tejasurya03** [comment]
Release kernel sourcefor redmi 4a xiaomi.Plz allow redmi 4a users for custom rom development

**Comment by rasyaadd** [comment]
Ctrl C + Ctrl V. Is that hard?

**Comment by krasCGQ** [comment]
^ ROFLMFAO

**Comment by tremores** [comment]
Xiaomi please stop violation of gpl rules and release kernels for Redmi 4a ASAP.

**Comment by avirk** [comment]
Xiaomi is keeping away rolex and santoni users from develop by not giving kernel sources and continue to violate linux kernel gpl. Don't know if there is anything we can do more than else to report here. There must be a legal action from Google against these kind if companies if they don't release sources after a time of of releasing device.

**Comment by muralivijay** [comment]
@krasCGQ then why xiaomi only released mi max 2 and m1 A1 faster ?. they stil ignoring redmi 4A/4X

**Comment by aaamirsingh** [comment]
It's a humble request to @XiaomiIndia and @Xiaomi to release the kernel source for Redmi 4a . It's been 1.5 year passed and kernel source is not released yet.
You should better follow your own rules.
Think about releasing kernel source before releasing your device whose kernel is licensed under GPLv2.

**Comment by ghost** [comment]
Also, don't forget Prada. They forgetting it too

**Comment by muralivijay** [comment]
@jawaadsaeed why u asking kernel source ? try to port any CAF kernel source for prada beacuse chipset msm8937 based . it can boot caf redmi 3s team already do this before releasing kernel source

**Comment by muralivijay** [comment]
but MSM8917 to hard Not booting with caf source blank screen and no usb always .. @xiaomi please release kernel source for rolex . we need drivers for boot

**Comment by ghost** [comment]
Release the kernel source for all Rolex users plz

We want kernel source for Redmi 4A Right now!
@xiaomi @XiaomiUSA
@XiaomiIndia @XiaomiIndia @Android @AndroidAuth @Google @Android 
#Redmi4A
#wewantkernelsource
#ReleaseKernelSources
#opensourcebreakerxiaomi #Gplv2violation

**Comment by duhjent** [comment]
Please release it.

**Comment by krasCGQ** [comment]
@muralivijay bcs Xiaomi only cares about some of their phones... 🤔

**Comment by krasCGQ** [comment]
Also Mi A1 kernel source was released under demand of users

**Comment by luk1337** [comment]
no

**Comment by muralivijay** [comment]
@krasCGQ . I think xiaomi still not responding ..So iam going to register complaint to GNU xiaomi violating GPL. Let see

**Comment by ghost** [comment]
Xiaomi have been violating the GPL for years, they are criminals who don't care about international copyright law. Your github issue is insignificant to them, pissing in the wind. The only way to get corporate monsters to change is to hit them in their wallets i.e. research your products and don't buy from criminals. Xiaomi are as likely to listen to you after you've been conned by them as a fake dealer is gonna give someone their money back after conning them. I know, getting hit by a criminal is not a nice feeling, but you gotta learn from it and get a bit more cynical.

**Comment by ghost** [comment]
There's a reason you had to buy your phone from some shitty internet third party reseller or the criminal's own "official" website.

The same way there's a reason why the dealer is yelling out "hot bud" next to a crowded train station and selling you "ganja" in a black bag (that's really parsley) for 20 dollars.

**Comment by krasCGQ** [comment]
`¯\_(ツ)_/¯ `

**Comment by dedejamaludin** [comment]
Is it right ? Xiaomi will release kernel source for some unreleased devices ?

**Comment by krasCGQ** [comment]
...what @dedejamaludin
rolex has been exist for more than 14 months already. They have rights to fight for their rights.

**Comment by tronajay** [comment]
It's Been More than 1 year. You hasn't released kernel Source For Redmi 4a (Rolex) . You are Violating the GpLv2 Rule . 

Release Now .

**Comment by Vessel09** [comment]
Release it please

**Comment by bams0038** [comment]
I believe@XiaoMiwill follow GPL rules. But why so long ago ? Its been one year but kernel source still not release yet. What the LOL???

**Comment by Nibi-git** [comment]
I already have neurosis due to the expectation of the kernel source :(

![watching](https://user-images.githubusercontent.com/6334382/35778693-c26b0e80-09b9-11e8-9a4b-28ed75f6d163.png)

**Comment by dedejamaludin** [comment]
Is there still no rrspons from xiaomi ? Very cruel...

**Comment by nutsalhan87** [comment]
+1

**Comment by muralivijay** [comment]
Xiaomi still not responding

**Comment by Remixuser** [comment]
+1

**Comment by WooDied** [comment]
+1

**Comment by krasCGQ** [comment]
Code-Review-2
Verified-1

**Comment by tremores** [comment]
@xiaomi you are no. 1 violetor of @GPLv2 licence. Bu we will never give up...

**Comment by akhilnarang** [comment]
LMFAO

**Comment by ghost** [comment]
Please respond #gpl2violation #xiaomi #redmi4A #kernelsource

**Comment by luk1337** [comment]
this isn't facebook, stop using these silly hashtags.

**Comment by punyapal** [comment]
It's more than a year please release the kernel source for redmi 4a you are violating
GPL and if u do not release kernel source for redmi 4a then you have to face consequences.

**Comment by luk1337** [comment]
too bad they won't face any.

**Comment by ghost** [comment]
+1

**Comment by krasCGQ** [comment]
It's China, sir. @punyapal

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by luk1337** [comment]
-9

**Comment by krasCGQ** [comment]
-∞

**Comment by muralivijay** [comment]
@bri stop spamming

**Comment by bams0038** [comment]
Please @xiaomi release kernel source for Redmi 4a.. We wait..

**Comment by luk1337** [comment]
no

**Comment by JPT77** [comment]
+1

**Comment by Dzikri630** [comment]
Please release kernel for redmi 4a

**Comment by SunnyRaj84348** [comment]
Release source

**Comment by shupitR** [comment]
Release kernel source for Redmi 4A rolex, for development our devices

**Comment by cengpo099** [comment]
Yeaa. Xiaomi please release the kernel sources. WTH here still not release after 1 years?

**Comment by nadeemalam178** [comment]
we are waiting for the release of kernel sources so that we can go ahead with the development of our device... Xiaomi is doing injustice with its customers...shame on Xiaomi

**Comment by cengpo099** [comment]
Release the rolex kernel sources now XIAOMI!!!

**Comment by cengpo099** [comment]
+1

**Comment by cengpo099** [comment]
+1

**Comment by cengpo099** [comment]
+1

**Comment by cengpo099** [comment]
+1

**Comment by cengpo099** [comment]
+9999999999999999999999999999999999999999999999999999999

**Comment by muralivijay** [comment]
Many users asking Source. But xiaomi still eating chips 😂😁.  What happened you @xiaomi . Respond please

**Comment by cengpo099** [comment]
XIAOMI please read this article https://en.wikipedia.org/wiki/GNU_General_Public_License

**Comment by VS0x01** [comment]
Release kernel source for Redmi 4A, please! The users are waiting for stable custom ROMs, Oreo roms. You have to give the opportunity. We do not want depend on you.

**Comment by WooDied** [comment]
+++++

**Comment by dedejamaludin** [comment]
It has been a week we ask to xiaomi buy they keep silent. Damnright...

**Comment by dedejamaludin** [comment]
It has been a week we ask to xiaomi to release kernel source but they keep silent. Damnright...

**Comment by krasCGQ** [comment]
Kek

**Comment by DEVviL1** [comment]
I can reverse engineer drivers from your stock firmware but I don't want to violate gpl by unofficial releasing it(

**Comment by DEVviL1** [comment]
But the drivers reversed not fully stable it comes with bugs!

**Comment by muralivijay** [comment]
@Stain995 im already tried CAF porting booting with plain blank screen . no usb works . any idea ? please mail me at muralidharan9845@gmail.com . i need your help

**Comment by luk7331** [comment]
@luk1337 no, means you have no brain? seems like so, fucking 12 yo internet gangster, trying to make fun of serious issue. jebac polska kurwa, CHUJ ci w dupe

**Comment by ghost** [comment]
Lol 😂😂

**Comment by bgcngm** [comment]
@luk7331 no

**Comment by bgcngm** [comment]
Just no!

**Comment by luk7331** [comment]
@luk1337 hvh me irl, 1v1 i'll rek and 1tap u ez fkin nn

**Comment by luk1337** [comment]
@luk7331 do I know you from somewhere?

**Comment by luk7331** [comment]
@luk1337 you probably faced me at some point if you play smfc/globe eu prime in night time

**Comment by luk1337** [comment]
fuck if i know, maybe if you post your acc i'll check if i have you on my tracker xD

**Comment by luk7331** [comment]
@luk1337 does it matter? you're such a jerk, trolling all the time 4a users
hope i will find and bite you lol

**Comment by luk1337** [comment]
yeah, i don't think that's going to happen.

**Comment by luk7331** [comment]
@luk1337 you prob don't have it, i play clean on main

**Comment by luk1337** [comment]
wow, people still play clean csgo. That's surprising.

**Comment by luk7331** [comment]
premade with friends = on main, no inj
solo = wingman only, if you know what i mean hehe

**Comment by krasCGQ** [comment]
@luk7331 no²

**Comment by ghost** [comment]
Another guy want attention too xD
Saying no lmfao

**Comment by krasCGQ** [comment]
Not me 🏃🏃🏃
I'm just seeing this issue thread that slowly became a drama. I don't need such attention. Kthxbye.

**Comment by TheComputerGuy96** [comment]
+1

**Comment by luk1337** [comment]
-1

**Comment by krasCGQ** [comment]
`--- issues/825
+++ /dev/null`

**Comment by muralivijay** [comment]
@krasCGQ ??

**Comment by muralivijay** [comment]
Xiaomi enjoying holiday .and eating chips don't distrub 😂😂

**Comment by muralivijay** [comment]
Wait and see Xiaomi release source at 2030

**Comment by ghost** [comment]
😂😂😂😂😂

**Comment by kshitijsubedi** [comment]
We need kernel. We need oreo.

**Comment by muralivijay** [comment]
Redmi 4/4x kernel source code released 😞

**Comment by muralivijay** [comment]
Still Rolex not

**Comment by krasCGQ** [comment]
Xiaomi will release it in year 8102.

**Comment by DEVviL1** [comment]
Guys just wait a decade and it'll be released)

**Comment by ghost** [comment]
Good news will come to Rolex users soon™

**Comment by muralivijay** [comment]
But when ??

**Comment by luk1337** [comment]
@jawaadsaeed hope not. I will miss people crying about it everyday.

**Comment by muralivijay** [comment]
Who crying @luk1337 ?

**Comment by ghost** [comment]
Waiting

**Comment by ghost** [comment]
@jawaadsaeed what is the good news.

**Comment by krasCGQ** [comment]
The good news is Xiaomi will probably release it on 8102.

**Comment by ghost** [comment]
@luk1337 xD

**Comment by maxismangh** [comment]
1 year, 4 months and counting.

**Comment by nutsalhan87** [comment]
We are waiting for kernel source!

**Comment by luk1337** [comment]
I'm not waiting for it tbh

**Comment by muralivijay** [comment]
Then why you are weast with this issue? Get out @luk1337

**Comment by muralivijay** [comment]
* time

**Comment by luk1337** [comment]
- time
  - time 
    - time
      - time
        - time 
          - time
            - time
              - time 
                - time
                  - time

**Comment by muralivijay** [comment]
Don't spam @luk1337

**Comment by maxismangh** [comment]
Don't feed the troll(s) please. Thank you.

**Comment by luk1337** [comment]
lol

**Comment by muralivijay** [comment]
@luk1337 illuminate I think

**Comment by muralivijay** [comment]
@xiaomi where are you ?. Are you reading comments. Please release the kernel source of Rolex . To much spams coming

**Comment by ghost** [comment]
@Xiaomi Oreo kernel source released for Mi A1 but still no kernel source for Rolex. Please release it .

**Comment by krasCGQ** [comment]
Calm your head @Dilip1998
It isn't true source, they pushed Redmi 1S source to `tissot-o-oss` branch instead.

**Comment by krasCGQ** [comment]
And it's released for real.

**Comment by TheComputerGuy96** [comment]
Kernel source for this device is out (kind of):
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/commit/2dd7cd829e165917bfe384febf21d9727b05fba4

**Comment by muralivijay** [comment]
kernel source released For rolex checkout  (riva-n-oss)
