### ISSUE TITLE
k30 pro无限重启

### ISSUE THREAD

**Issue by fIappy** [MiCode/Xiaomi_Kernel_OpenSource#8276]
用的cas-q-oss分支，改了源码里面n个坑后，编译出来的kernel(只)替换boot.img的kernel后，开机无限重启。
原boot.img的kernel 40多M，而编译出来的只有39M，是什么原因呢

make O=out REAL_CC=${PWD}/toolchains/llvm-Snapdragon_LLVM_for_Android_8.0/prebuilt/linux-x86_64/bin/clang CLANG_TRIPLE=aarch64-linux-gnu- cas_user_defconfig
make -j$(nproc) O=out REAL_CC=${PWD}/toolchains/llvm-Snapdragon_LLVM_for_Android_8.0/prebuilt/linux-x86_64/bin/clang CLANG_TRIPLE=aarch64-linux-gnu-

**Comment by UncleLiuYe** [comment]
你好，我也是K30PRO的用户，我最近也在尝试编译官方的4.19.81的内核，但是只能在Android10的MIUI系统启动。最后建议使用lmi分支。

**Comment by jianyi520** [comment]
> 用的cas-q-oss分支，改了源码里面n个坑后，编译出来的kernel(只)替换boot.img的kernel后，开机无限重启。 原boot.img的kernel 40多M，而编译出来的只有39M，是什么原因呢
> 
> make O=out REAL_CC=${PWD}/toolchains/llvm-Snapdragon_LLVM_for_Android_8.0/prebuilt/linux-x86_64/bin/clang CLANG_TRIPLE=aarch64-linux-gnu- cas_user_defconfig make -j$(nproc) O=out REAL_CC=${PWD}/toolchains/llvm-Snapdragon_LLVM_for_Android_8.0/prebuilt/linux-x86_64/bin/clang CLANG_TRIPLE=aarch64-linux-gnu-

大佬解决了吗

**Comment by jianyi520** [comment]
> 用的cas-q-oss分支，改了源码里面n个坑后，编译出来的kernel(只)替换boot.img的kernel后，开机无限重启。 原boot.img的kernel 40多M，而编译出来的只有39M，是什么原因呢
> 
> make O=out REAL_CC=${PWD}/toolchains/llvm-Snapdragon_LLVM_for_Android_8.0/prebuilt/linux-x86_64/bin/clang CLANG_TRIPLE=aarch64-linux-gnu- cas_user_defconfig make -j$(nproc) O=out REAL_CC=${PWD}/toolchains/llvm-Snapdragon_LLVM_for_Android_8.0/prebuilt/linux-x86_64/bin/clang CLANG_TRIPLE=aarch64-linux-gnu-

大佬解决了吗
