### ISSUE TITLE
请更新红米note1s gucci的源码

### ISSUE THREAD

**Issue by luhux** [MiCode/Xiaomi_Kernel_OpenSource#829]
请更新源码，我想编译6.0

**Comment by pradeepvarma107** [comment]
i am working on cm14.1 for gucci if u can u can contact me

**Comment by pradeepvarma22** [comment]
目前我正在建设android n如果你想你能帮助我

**Comment by pradeepvarma22** [comment]
officially these xiaomi wont release kernel 

kikat kernel is released but full of bugs and incompleted kernel

**Comment by luhux** [comment]
pradeepvarma107 ,Can you use double card for your cm14?

**Comment by luhux** [comment]
我只是想要解决双卡问题😓

**Comment by brlin-tw** [comment]
所以 HM Note 1S 搭配的 MIUI 系統有基於 Android 6.0 嗎？
根據 GPL 小米沒有義務釋出從未釋出 binary 過的軟體源碼

**Comment by pradeepvarma22** [comment]
https://github.com/Wzedlare/android_kernel_xiaomi_msm8916/tree/cm-13.0?files=1
