### ISSUE TITLE
Source for Mi MIX Please!

### ISSUE THREAD

**Issue by Nokius** [MiCode/Xiaomi_Kernel_OpenSource#83]
Having sources for this device would be really nice!

Thanks in advance

**Comment by infeedel** [comment]
Upvoted !

**Comment by anetar** [comment]
Hopefully source version as soon as the suspended updated with other Source  versions I see oneplus company going in the way of adsorbed all its devices is  updated source
very soon released  to kernel sources and camera blobs

https://github.com/OnePlusOSS

I hope Xiaomi to become like oneplus

**Comment by infeedel** [comment]
bump

**Comment by mjevange** [comment]
bump

**Comment by blackjetcat** [comment]
Now you can close issue, source released ( scorpio-m-oss ).

**Comment by infeedel** [comment]
These are still scorpio sources and not lithium sources

**Comment by luca020400** [comment]
@infeedel this release support every msm8996 device by xiaomi, including lithium

**Comment by infeedel** [comment]
@luca020400 my bad, wasn't entirely up to date, thanks !

**Comment by Nokius** [comment]
request done with [commit  671c431 ](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/commit/671c431f6dd350fb702d2b0b1441f80af6af2903)

Thanks
