### ISSUE TITLE
Update sources for mi5

### ISSUE THREAD

**Issue by zra123** [MiCode/Xiaomi_Kernel_OpenSource#830]
Please update the source for mi5. for myui 9, android N, kernel version 3.18.31

**Comment by krasCGQ** [comment]
`> myui`

**Comment by 0pLuS0** [comment]
This isn't a forum please knock off the spam and read!

--> https://github.com/MiCode/Xiaomi_Kernel_OpenSource/issues/854

**Comment by n1kolaa** [comment]
scorpio-o-oss | Mi 5, Mi Mix, Mi Note 2 | Android O | LA.UM.6.5.r1-04300-8x96.0 | scorpio-o-oss
-- | -- | -- | -- | --



https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/scorpio-o-oss
