### ISSUE TITLE
请求小米5x（Tiffany）开源！！！

### ISSUE THREAD

**Issue by Shadcloud** [MiCode/Xiaomi_Kernel_OpenSource#839]
小米5x是7月份发布的一款手机，比国际版小米A1（TISSOT）早了一个多月，A1都开源了将近半月，为什么5X依旧不开源？作为x系列的第一个手机，以高颜值高性价比著称，现在2017年发布的手机都已经开源，唯独5x特殊！甚至作为小米系列的手机，连红米都待遇都get不到。有些人就是为了刷机才买小米手机的，，不开源我们玩什么，希望我的发言能够起作用。

**Comment by ivan19871002** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/tiffany-n-oss
