### ISSUE TITLE
Source for MI5s

### ISSUE THREAD

**Issue by Gabriel-Campos** [MiCode/Xiaomi_Kernel_OpenSource#84]
Please Xiaomi, release the mi5s source asap!

**Comment by nicoula** [comment]
Follow the GPL please ...

**Comment by wspl** [comment]
and Mi 5s Plus too. ☹

**Comment by nazunamoeold** [comment]
SOURCE PLEASE!

**Comment by gtebbutt** [comment]
Would be great to get the source for the Mi5s

**Comment by CL0SeY** [comment]
GPL request for kernel source for Mi5s please.

Thanks!

**Comment by ghost** [comment]
Source Please.

**Comment by anarkia1976** [comment]
+1+2+3+4+5

**Comment by AdeonBlack** [comment]
Please release the kernel sources for the Mi 5s ASAP, you're not respecting the GPL

**Comment by tcraxs** [comment]
capricorn source please.

**Comment by anetar** [comment]
Hopefully source version as soon as the suspended updated with other Source  versions I see oneplus company going in the way of adsorbed all its devices is  updated source
very soon released  to kernel sources and camera blobs

https://github.com/OnePlusOSS

I hope Xiaomi to become like oneplus

**Comment by keks2293** [comment]
+

**Comment by emman-bautista** [comment]
It's been 4 months already after this is released and still we don't have the source of the kernel. I wonder how long this will take to release. They should respect the GPL requirements.

**Comment by fadeeveu** [comment]
I join the multiple requests for the mi5s kernel. I hope xiaomi follow the GPL requirement stricter.

**Comment by AYastrebov** [comment]
+1

**Comment by HITGIF** [comment]
release asap please +1

**Comment by pkhodaveissi** [comment]
Please do release the source, It only hurts your popularity and make people think that they need to run away from your stock rom, at least this way people can enjoy your smart phones while you get a good enough stock rom and people would actually consider coming back to you when you developed one

**Comment by jant90** [comment]
+1 release please

**Comment by blackjetcat** [comment]
+1

**Comment by anarkia1976** [comment]
+30

**Comment by luk1337** [comment]
-29, no cheating pls.

**Comment by anarkia1976** [comment]
I think we have to wait new mi6 or the new year :)

**Comment by emman-bautista** [comment]
Dont count on xiaomi. They have the worst support ever for updates and
kernel release. I've arleady returned back to oneplus3t. Still the best
choice i made after xiaomi.

**Comment by blackjetcat** [comment]
Now you can close issue, source released ( scorpio-m-oss ).
