### ISSUE TITLE
Tiffany开源

### ISSUE THREAD

**Issue by Shadcloud** [MiCode/Xiaomi_Kernel_OpenSource#840]
到底开不开源啊，小米应该给个说法，这样下去谁等得起啊，新年将至，2018了。

**Comment by cakeuui0414** [comment]
8102年了

**Comment by Shadcloud** [comment]
dalao，现在8210年了

**Comment by scafroglia93** [comment]
https://www.youtube.com/watch?v=0G7eDpMGe1k

**Comment by fengdechao** [comment]
是啊，都2018年了，，官方就会崇洋媚外，在国外挣到钱压根不管国内的用户

**Comment by Shadcloud** [comment]
一个月之内没动静怕是凉凉了，没事，小米有很多替代品的，不买你这东西就行了

**Comment by OnlyLady** [comment]
呵呵呵  小米我已经彻底的无语了

**Comment by OnlyLady** [comment]
我也只能呵呵几句

**Comment by fengdechao** [comment]
我去，，，红米4X都开源了，，作为小米系列的5X难道就绝代了？？算了，，以后打死不买小米了，，真让人失望。

**Comment by Shadcloud** [comment]
最后一次买小米，等换手机就把这破手机砸了

**Comment by OnlyLady** [comment]
以后要买小米的话 看准旗舰机买

**Comment by OnlyLady** [comment]
反正我不断买小米了。

**Comment by ivan19871002** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/tiffany-n-oss
