### ISSUE TITLE
Release the Kernel Source for Xiaomi Mi 5X (tiffany)

### ISSUE THREAD

**Issue by OnlyLady** [MiCode/Xiaomi_Kernel_OpenSource#844]
Is it time to think about open source? Don't make excuses that 5X is offline. Since you MIUI officials have no intention of upgrading android 8 to 5X, please open source the 5X kernel.

**Comment by OnlyLady** [comment]
hhehehehe

**Comment by 0pLuS0** [comment]
@OnlyLady stop spamming and READ, this isn't a forum!

https://github.com/MiCode/Xiaomi_Kernel_OpenSource/issues/854

**Comment by ivan19871002** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/tiffany-n-oss
