### ISSUE TITLE
Release the Kernel Source for Xiaomi Mi 5X (tiffany)

### ISSUE THREAD

**Issue by LE7ELS** [MiCode/Xiaomi_Kernel_OpenSource#846]
Please release the Kernel Source for Xiaomi Mi 5X (tiffany)🙏🙏🙏

**Comment by 0pLuS0** [comment]
@LE7ELS stop spamming and READ!
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/issues/854

**Comment by ivan19871002** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/tiffany-n-oss
