### ISSUE TITLE
Release the Kernel Source for Xiaomi Mi 5X (tiffany)

### ISSUE THREAD

**Issue by tklaon** [MiCode/Xiaomi_Kernel_OpenSource#847]
Release the Kernel Source for Xiaomi Mi 5X (tiffany)

**Comment by 0pLuS0** [comment]
@tklaon knock of spamming the Repo!

This is not a forum, this is a GitHub Repo.

Do you not understand any of this? If you don't then please learn to read!

```Issues``` is for ```Reporting Issues``` as it relates to problems with that Project!

Next time ask on the forums!

**Comment by pinoaffe** [comment]
@0pLuS0
The fact that Xiaomi is violating the GPL by not releasing their kernel patches is very much related to the project.
As you can see in other projects, feature requests, update requests, licensing issues, etc are a perfectly valid type of discussion for the `Issues` section.
However, making dozens of threads with the exact same thread is not.
Furthermore, it does not seem like xiaomi really cares about this section, I don't think I've ever seen them post or react here.

**Comment by ivan19871002** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/tiffany-n-oss
