### ISSUE TITLE
Source code error Santoni (redmi 4/4x)

### ISSUE THREAD

**Issue by ashishjohnson** [MiCode/Xiaomi_Kernel_OpenSource#853]
After succuss compilation the wifi (wlan) got error not working plz make sure what needs..
Plz make it 
I just added all modules with but wlan not working

**Comment by ashishjohnson** [comment]
Helppp

**Comment by x-Pepsy** [comment]
LoL

**Comment by ashishjohnson** [comment]
Plz make it

**Comment by ashishjohnson** [comment]
I just added all modules with but wlan not working
