### ISSUE TITLE
add sources for redmi note 2(hermes)

### ISSUE THREAD

**Issue by nofearnohappy** [MiCode/Xiaomi_Kernel_OpenSource#856]
MTK rip
![nigers_161714312_orig_](https://user-images.githubusercontent.com/3429783/37740837-45dfd5d2-2d70-11e8-9762-29886f59c5ec.jpg)

**Comment by Smosia** [comment]
RIP

**Comment by Dum4G** [comment]
![image](https://user-images.githubusercontent.com/5430116/37735676-d4154122-2d5f-11e8-8c62-310ab37d28aa.png)

**Comment by mario-rr** [comment]
Rest in Pepperoni

**Comment by andrea2107** [comment]
A "long cheer" for the release of the sources!

Rip.

**Comment by joe2k01** [comment]
![R.I.P](https://media2.giphy.com/media/3oFzmrqh43AvYwn9Cw/giphy.gif)

**Comment by MZO9400** [comment]
RIP²

**Comment by x-Pepsy** [comment]
Pls release kernel for mi 7

**Comment by nofearnohappy** [comment]
-
![chest](https://user-images.githubusercontent.com/3429783/37738246-6b2dd5a4-2d67-11e8-912d-d98ec13fe9e2.jpg)

**Comment by nofearnohappy** [comment]
![otdayot_chest](https://user-images.githubusercontent.com/3429783/37738261-79471128-2d67-11e8-8036-50606abb962d.gif)

**Comment by nofearnohappy** [comment]
![otdat_chest](https://user-images.githubusercontent.com/3429783/37738272-84430be0-2d67-11e8-99b9-1dda4a23af03.gif)

**Comment by GiaSen** [comment]
Release MIUI oreo for mido

**Comment by krasCGQ** [comment]
Wrong thread @GiaSen

**Comment by muralivijay** [comment]
RIP MTK

**Comment by pgeorgef** [comment]
rip

**Comment by ghost** [comment]
RIP MediaKetek

**Comment by nofearnohappy** [comment]
+

**Comment by DoveKi** [comment]
Mi Pad 3 also MTK, but Xiaomi open the source code now.

**Comment by dragonpt** [comment]
It's released, have fun
