### ISSUE TITLE
riva/rolex doesn't boots

### ISSUE THREAD

**Issue by MacTavishAO** [MiCode/Xiaomi_Kernel_OpenSource#862]
compiled many times for riva and rolex but not boots.

**Comment by ryan-andri** [comment]
you need linking the device tree into kernel or use dtc to link them if you only build the kernel.

**Comment by MacTavishAO** [comment]
not boots on twrp too. try yourself

**Comment by dragonpt** [comment]
check your build environment...

**Comment by MacTavishAO** [comment]
i know how to build a kernel :)

**Comment by MacTavishAO** [comment]
example https://github.com/MacTavishOT/codeaurora_kernel_xiaomi_msm8953 here is my codeaurora port kernel source for mido

**Comment by ivan19871002** [comment]
Before open source we have to make sure that everything is work well.


Let's confirm it internally.

**Comment by ivan19871002** [comment]
It is work for me, I confirm . I flash riva and rolex

What's about the others

**Comment by MacTavishAO** [comment]
Rebased kernel boots.
