### ISSUE TITLE
请求小米5x（Tiffany）开源！！！

### ISSUE THREAD

**Issue by dksslq** [MiCode/Xiaomi_Kernel_OpenSource#864]
open source for mi5x ,please

**Comment by dksslq** [comment]
请求小米5x（Tiffany）开源!!!!!等了好久了,小米不该这样的

**Comment by Shadcloud** [comment]
Maybe a year😡

**Comment by dksslq** [comment]
shhhhhhhhhhhhhhhhhhhhhhhhhht

**Comment by ivan19871002** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/tiffany-n-oss
