### ISSUE TITLE
请开源红米5P(vince)的内核代码

### ISSUE THREAD

**Issue by 0312birdzhang** [MiCode/Xiaomi_Kernel_OpenSource#871]
红米5p距离发布已经4个多月了，然而刚刚发布没多久的红米note5pro已经开源内核代码了，这样不是引起公愤吗？
或者你们给出一个说明一个理由为什么还不开源，起码有个官方说明好吧。

**Comment by bbw3000** [comment]
附议，等了好久了

**Comment by 0312birdzhang** [comment]
已开源 https://github.com/MiCode/Xiaomi_Kernel_OpenSource/commits/tiffany-n-oss
