### ISSUE TITLE
Please open Redmi 5 Plus(vince) kernel source.

### ISSUE THREAD

**Issue by Z5X67280** [MiCode/Xiaomi_Kernel_OpenSource#873]
Please open its kernel source code, we need it!

**Comment by 0312birdzhang** [comment]
We need it!

**Comment by obsvg216** [comment]
:angry:

**Comment by bbw3000** [comment]
waited too long

**Comment by mdeejay** [comment]
typical chinese company.... like rats..

**Comment by Haseo97** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/commits/tiffany-n-oss

**Comment by Z5X67280** [comment]
Yes, its kernel source code is open now.XD
Thank you Xiaomi,But we waited for a long time.
Especially Mi 5X :-(
So,done!

**Comment by ivan19871002** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/tiffany-n-oss
