### ISSUE TITLE
Redmi 5A (riva)

### ISSUE THREAD

**Issue by SunnyRaj84348** [MiCode/Xiaomi_Kernel_OpenSource#881]
Kernel source broken, it is giving error while compiling in bq2560x_charger.c  and bq27426

**Comment by ivan19871002** [comment]
double check it ,  it is work well.

**Comment by SunnyRaj84348** [comment]
I compiled kernel many times but got same error

**Comment by luca020400** [comment]
You're getting errors because you're likely building inline. Xiaomi uses out of tree build and it that case it properly loads the headers
Just do
```
make O=`pwd -P`/.
```
And it should work just fine

Anyways post your build error

**Comment by SunnyRaj84348** [comment]
I always use an output directory

Here's the eror https://pastebin.com/UP0pfCD7

**Comment by luca020400** [comment]
In this case just remove the bq2560x_enable_term function. Maybe you forgot to turn off some option in the defconfig for thermal control of the charging driver
@ivan19871002 might want to take a look \o/

**Comment by SunnyRaj84348** [comment]
After turning off , charging not working

**Comment by luca020400** [comment]
Not the charging driver itself :P
Just remove the function in this case

**Comment by Nikesh001** [comment]
@sunnyraj84348 add this KBUILD_CFLAGS := -Wno-unused-function. In Makefile. I fixed errorby this;_; and yeah Charging still not work.
