### ISSUE TITLE
Maybe push working Redmi 4 Prime defconfig?

### ISSUE THREAD

**Issue by nkrapivin** [MiCode/Xiaomi_Kernel_OpenSource#884]
defconfig in markw-m-oss branch is broken. Maybe push working?

**Comment by ryan-andri** [comment]
you can try take defconfig from stock kernel by using script extract-ikconfig.

**Comment by nkrapivin** [comment]
Really?! I think it is impossible. (ur kernel for 4x is the best)

**Comment by nkrapivin** [comment]
Ok. I got it.
