### ISSUE TITLE
Redmi 5A (RIVA) charging issue

### ISSUE THREAD

**Issue by rahulgkr** [MiCode/Xiaomi_Kernel_OpenSource#885]
Charging Not working In Compiled Kernel , Please Fix it Soon

**Comment by scafroglia93** [comment]
LOL

**Comment by rahulgkr** [comment]
Charging driver issue

**Comment by rahulgkr** [comment]
Don't ignore , always releases broken sources

**Comment by rahulgkr** [comment]
@ivan19871002

**Comment by ivan19871002** [comment]
charging issue on MIUI？  or others？

**Comment by rahulgkr** [comment]
On miui & others too

**Comment by ivan19871002** [comment]
OK， I will check it.

**Comment by liuguo09** [comment]
Charging Not working for Redmi 5A, and Fixed and updated in github，I'm sorry to trouble you.
