### ISSUE TITLE
Redmi 5A (RIVA) Charging Driver Missing

### ISSUE THREAD

**Issue by SunnyRaj84348** [MiCode/Xiaomi_Kernel_OpenSource#886]
Riva uses PMIC charging driver which is missing in kernel source , Add it to fix charging issue on kernel

Driver : qcom,qpnp-power-on qpnp-power-on-5: PMIC@SID0 Power-on reason: Triggered from Hard Reset and 'cold' boot

**Comment by liuguo09** [comment]
Charging Not working for Redmi 5A, and Fixed and updated in github，I'm sorry to trouble you.
