### ISSUE TITLE
Redmi 5A charging drivers are missing.

### ISSUE THREAD

**Issue by LordShenron** [MiCode/Xiaomi_Kernel_OpenSource#887]
The charging drivers of Redmi 5A are missing which is causing charging issue in compiled kernel. Please add it so the charging issue can be fixed. RIVA uses PMIC bq2560x-charger bq_fg charging driver which is missing. 
Driver : qcom,qpnp-power-on qpnp-power-on-5: PMIC@SID0 Power-on reason: Triggered from Hard Reset and 'cold' boot

**Comment by liuguo09** [comment]
Fixed and updated in github，I'm sorry to trouble you.

**Comment by LordShenron** [comment]
Thank you so much for your help, we are really happy you responded so quicky.
