### ISSUE TITLE
Mi Note 2 (scorpio) - Missing scorpio-o-oss branch

### ISSUE THREAD

**Issue by Alberto96** [MiCode/Xiaomi_Kernel_OpenSource#890]
Even nougat changes are missing (or at least not declared), the source code is stuck on the marshmallow release (scorpio-m-oss).
The official Oreo-Based ROM has been released a long while ago, but the related kernel source has not been uploaded.

http://bigota.d.miui.com/8.5.3/miui_MINote2_8.5.3_e90e7af48e_8.0.zip

@ivan19871002 @liuguo09

**Comment by luca020400** [comment]
They're on it

**Comment by sysxda** [comment]
They updated source to nougat

**Comment by luca020400** [comment]
O is next

**Comment by sysxda** [comment]
Not sure :) thats xiaomi

**Comment by nervehammer** [comment]
well it's released 2 days ago https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/scorpio-o-oss?files=1 
Have fun close this issue :)
