### ISSUE TITLE
Kernel release for whyred miui 9.5.11 update

### ISSUE THREAD

**Issue by rayzen66** [MiCode/Xiaomi_Kernel_OpenSource#896]
The current kernel source release of whyred-o-oss doesn't seem to work in the latest version of miui which was pushed recently I.e miui 9.5.11. camera doesn't seem to be working with latest release along with current kernel. Kindly update the kernel source for miui 9.5.11 release please. @ivan19871002

**Comment by Umang96** [comment]
I can confirm same, cameras not working, tried with 9.5.11, software information tab in ctt not showing any camera sensors. Brightness is also buggy for me, sets at either low level or high level, anything in middle doesn't work.

**Comment by rayzen66** [comment]
@hehao @ivan19871002

**Comment by amarpreetosahan** [comment]
+1 Kindly update the kernel source for miui 9.5.11.0 release

**Comment by ryan-andri** [comment]
i thinks santoni alone with buggy source, but yeah santoni have a friend now :/

**Comment by luca020400** [comment]
@ryan-andri it wasn't the first, won't be the last :)
They should be checking it anyways ...

**Comment by rayzen66** [comment]
The source is updated and can confirm above issue has been fixed. Thanks @hehao.
