### ISSUE TITLE
Missing WLAN driver source code

### ISSUE THREAD

**Issue by kn8wolf** [MiCode/Xiaomi_Kernel_OpenSource#9]
Hi,

Where do I find the source code for the Pronto WLAN driver of Prima specific to REDMI Note 4G?

It is required to successfully compile the kernel and make use of the WiFi on the handset. 

This kernel source is missing the driver's source code and hence wifi will not get enabled in custom kernel after compilation.
Other devices' kernel sources do provide the drivers for their h/w (pronto wlan) for compilation.

It would be great to have for DIOR as well..
CONFIG_PRONTO_WLAN=m

**Comment by fergy** [comment]
https://android.googlesource.com/kernel/msm/+/142f315b1fac51d07b9693c68a202c3a0211d965/drivers/staging/prima

**Comment by liuguo09** [comment]
Please refer to this [FAQ](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/wiki/FAQ#where-is-wifi-driver-module)

**Comment by fergy** [comment]
I got prima sources as those are available on github

**Comment by Vdragon** [comment]
@kn8wolf Since this issue is solved could you close it?
