### ISSUE TITLE
kernel problem in Xiaomi mi note prime 

### ISSUE THREAD

**Issue by vrlsrl675** [MiCode/Xiaomi_Kernel_OpenSource#901]
Please update the kernel because we want bug free rome for Xiaomi mi note prime

**Comment by Gah0** [comment]
i agree Please update the kernel

**Comment by ivan19871002** [comment]
We will update the lastest kernel for libra and leo

**Comment by ivan19871002** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/libra-n-oss
