### ISSUE TITLE
Any schedule for release kernel source of Redmi S2?(ysl)

### ISSUE THREAD

**Issue by copslock** [MiCode/Xiaomi_Kernel_OpenSource#902]
Hope that xiaomi will release kernel source for the Redmi S2(xiaomi E6,codename ysl ),although this phone wasn't designed for phone geeks,but will still be good if release kernel source for this device

**Comment by Haseo97** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/ysl-o-oss
