### ISSUE TITLE
因本人用错配置导致的问题，向小米开源团队道歉，对不起

### ISSUE THREAD

**Issue by sekaiacg** [MiCode/Xiaomi_Kernel_OpenSource#904]
因为本人因为用错了配置：sdm845...导致编译的内核无法启动。
之后在github以及xda上发泄不满情绪深表歉意。
在此，我对小米开源团队，特别是秋大道歉，对不起。
以后遇事我会多方求证之后冷静处理。
同时我会删除帖子上的负面表达。希望小米开源团队原谅。

**Comment by ivan19871002** [comment]
不能开机我能开源出来？

**Comment by ivan19871002** [comment]
我看看最新版本能不能起来吧。开源的那天是可以开机的 并且做过功能验证的，必须保证功能正常才能开源的。

**Comment by ivan19871002** [comment]
为了保证一切正常，我从github 把代码拉到本地编译的。
测试一切正常，开机没有任何问题，功能也测试了一下，也正常。

**Comment by simonsmh** [comment]
@ivan19871002 秋大好，我也是一位mix2s用户，使用的是国内6+128g非全网通的xe版的机子，刷了global的rom，就没办法使用源码编译的kernel开机，而国内版的rom正常。这与刷入magisk时对原kernel进行patch后无法开机的表现是相似的。请问我应该如何处理相关的错误？感谢！

**Comment by ivan19871002** [comment]
@simonsmh  MIX2S 应该是全网通的机器吧。为何会有非全网通的？？

**Comment by ivan19871002** [comment]
@simonsmh  你最好是重新开个issue，并且提供log 我才能帮你解决问题

**Comment by simonsmh** [comment]
@ivan19871002 不是啊，MIX2S有全球频段的版本m1803d5xa和非全球频段的版本m1803d5xe，我手上的是m1803d5xe版本。
我不知道怎么提供log，因为没法获取log（

**Comment by simonsmh** [comment]
@ivan19871002 MIX2s分全球频段m1803d5xa的国内8g+256g内存版本和非全球频段m1803d5xe的国内6g内存版本，我手上是非全球频段的版本。这个xe版本甚至刷global之后lock bootloader都会出现bootloop，很怪（
而且log不知道怎么提，因为根本没法开机的

**Comment by ivan19871002** [comment]
没有log 我就很难办了啊。重新开个issue讨论这个问题吧。不要到这里讨论了

**Comment by sanqiuu** [comment]
> 没有log 我就很难办了啊。重新开个issue讨论这个问题吧。不要到这里讨论了

5.4.86 civi1s你能开机就能见了鬼了
