### ISSUE TITLE
快点放出redmi 6a的源吧

### ISSUE THREAD

**Issue by xiaosongmao123** [MiCode/Xiaomi_Kernel_OpenSource#919]
刚上市就抢了一批6a，你倒是出源码啊。。。。2个月了

**Comment by xiaosongmao123** [comment]
刚整明白，，红米6a是联发科，估计不会出源码了，出源码的都是高通的

**Comment by ivan19871002** [comment]
我看了一下内部流程，开始走流程了

**Comment by NotKit** [comment]
@ivan19871002 please forgive me for English, but does that mean the source is planned to be released for this device? I hope Xiaomi can keep 3 months promise of GPL compliance.

**Comment by klwz** [comment]
@NotKit Yes.Always believe that something wonderful about to happen.
