### ISSUE TITLE
请快点放出小米8 的源码吧

### ISSUE THREAD

**Issue by xwwwb** [MiCode/Xiaomi_Kernel_OpenSource#922]
请快点放出小米8 的源码吧
请快点放出小米8 的源码吧
请快点放出小米8 的源码吧请快点放出小米8 的源码吧

**Comment by ivan19871002** [comment]
预计8月会开源出来，最近事情有点多。流程还没走完

**Comment by kalon33** [comment]
@ivan19871002 你知道它什么时候结束吗？

**Comment by 1nfrag** [comment]
@ivan19871002 its almost the end of august. Has any progress been made? :-)
We'd love some good news! 
Thanks!

**Comment by ivan19871002** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/dipper-o-oss
