### ISSUE TITLE
Please release the source code for Mi Pad 4

### ISSUE THREAD

**Issue by arter97** [MiCode/Xiaomi_Kernel_OpenSource#925]
It's nearly reaching 2 months since the release.

Please release the kernel source for the Mi Pad 4.

**Comment by PythonLimited** [comment]
I really hope that they will release it in under 3 months after release as they told...
In addition the device is nearly identical to the whyred so it should'nt be that kind of a big problem.

**Comment by ivan19871002** [comment]
We will release it this month.

**Comment by PythonLimited** [comment]
thanks for the reply

**Comment by Trozmagon** [comment]
Any updates on this?

**Comment by PythonLimited** [comment]
Dunno, seems like they force us to wait

**Comment by PythonLimited** [comment]
Any update @ivan19871002 ? Its only 6 days left this month

**Comment by arter97** [comment]
So the Mi A2 kernel sources were released today, and we're still yet to see Mi Pad 4's source.

@ivan19871002 @liuguo09 You guys have 3 days left. If the sources are not released til that point, you can count on me to get media coverage on how Xiaomi is ignoring yet another legal obligation and breaking a promise with the community.

Get your shit together.

**Comment by PythonLimited** [comment]
Count me in, in the last two days two more sdm660 kernels have been released but no sign or update about the Mi Pad 4.
Just frustrating

**Comment by Hero2457** [comment]
Legit just created an account here just to bash Xiaomi. 

Ya'll better get the kernel source out for the Mi Pad 4.

**Comment by PythonLimited** [comment]
Even the new pocophone got one. Why is the mi pad 4 so late??

**Comment by rcstar6696** [comment]
Waiting too now

**Comment by PythonLimited** [comment]
Last day if we can trust the words of @ivan19871002 ....

**Comment by PythonLimited** [comment]
Hello, @ivan19871002 we had the same situation nearly a month ago. JUST RELEASE IT. U SHOULD EVEN IMMIEDIATELY RELEASE THE SOURE CODE AFTER LAUNCHING THE DEVICE, IF NOT ITS VIOLATING THE GPL!!!! And relly telling everyone we will release it 3 months after release is a shame for a company like u. Take a look at Samsung they give u the links 1 to 2 days after. And thats also something why u will never grow that much as company if u dont get this working. I mean i wont fill a lawsuit against u, but if some companies decide to u are f*****. There are still devices from one year ago which havent recieved their kernel source. Fix that Xiaomi and u will See that this part oft the community will be happy.

**Comment by rcstar6696** [comment]
Up! We are still waiting

**Comment by PythonLimited** [comment]
The display of my pad started malfunctioning today. Let's see if the kernel got released when I get my replacement. :D

**Comment by whatismygithubid** [comment]
Any updates on this?

**Comment by BartekM01** [comment]
Dear @ivan19871002, when We can expect release of MiPad4 source code? 
Thank You

**Comment by BartekM01** [comment]
@liuguo09 @ivan19871002 we have September and still there is no sources released. Any news about release?

**Comment by Trozmagon** [comment]
This is very unfortunate, I bought this device because I though xiaomi were pretty honest with regards to releasing sources, guess I was wrong.

**Comment by BartekM01** [comment]
Hi again...
@liuguo09, @ivan19871002. How long it's gonna take? Xiaomi is VIOLATING the GPL!!! Please release sources ASAP!

**Comment by PythonLimited** [comment]
Ok I got my repaired pad back, but where the kernel?? 
It's even getting close to 3 months in which u told you'll release the kernel.

**Comment by PythonLimited** [comment]
And the only reason I can think of is that they either have some source code they don't want to share in the kernel and have to outsource first, or they use some proprietary code in like the camera or wherever else. But I mean they should have cleared the first with the OEMs or didnt released the pad until they have...

**Comment by zvanderbilt** [comment]
I would also like to see the kernel source released.

**Comment by moham96** [comment]
we need the kernel source for MI Pad 4 and MI Pad 4 plus

**Comment by PythonLimited** [comment]
JUST DO IT!!!!

**Comment by PythonLimited** [comment]
Two months since this issue has been opened....😐😥😫

**Comment by SpaceAgeHero** [comment]
Let's start a Shitstorm on Twitter.

**Comment by PythonLimited** [comment]
jo im in

**Comment by PythonLimited** [comment]
A friend of mine just reported this to GNU :D.
But I hardly assume it will do nothing.
Or someone from The Linux kernel contributor team could enforce this... Hopefully

**Comment by PythonLimited** [comment]
What we could try in meantime is building a kernel with whyred base and our config.
Unfortunately I don't got time for such a time consuming project.
Also it seems that most drivers for display and touch are missing...
Here's the .config link
https://mega.nz/#!ad8A1IiJ!jLqoW5QaoR29BNJTBTvcjMdHLAlP649cDWKGeb9AHeg

**Comment by zvanderbilt** [comment]
I understand your eagerness to roll your solution to this but trying to build a kernel for a tablet that is targeted towards a phone might end up sending you down a rabbit hole. I would definitely recommend not using a canned build.config either. Just take the time and go through the kernel menuconfig and add what you need and remove what you don't. Once/if they release the kernel I'll definitely post whatever I make to share.

**Comment by PythonLimited** [comment]
Well this config IS from Xiaomi :p 
U can extract the running kernel config from /proc/config.gz if the kernel is configured to provide support for CONFIG_IKCONFIG and CONFIG_IKCONFIG_PROC.

**Comment by arter97** [comment]
Unless you're willing to reverse engineer display and touch protocol, that's a near impossible task.
Not even worth starting it.
Device tree also differs a lot.

**Comment by PythonLimited** [comment]
Even XDA writes about that now.
Cmon Xiaomi
https://www.xda-developers.com/xiaomi-mi-pad-4-kernel-source-code-not-released/

**Comment by ruifcardoso** [comment]
Waiting for the kernel for the Mi Pad 4 and Mi Pad 4 Plus

**Comment by nachfuellbar** [comment]
Still no news on this? Bought some time ago...
It's kind of a show stopper for me...

**Comment by PythonLimited** [comment]
Not only for u :(

**Comment by zyonbao** [comment]
Any progress on this issue?

**Comment by apugacescu** [comment]
Disappointed, Oneplus 6t got their kernel source code released next day after the device was revealed. https://github.com/OnePlusOSS/android_kernel_oneplus_sdm845/commit/ea0847d32a41c41320333113966f8a719d482f47

**Comment by sxxylz** [comment]
I'm still waiting...
any progress?

**Comment by PythonLimited** [comment]
Nah :/

**Comment by steadramon** [comment]
Weekly prod....

Are Xiaomi actually planning to release this Kernel? @ivan19871002 @liuguo09

**Comment by thomasvt1** [comment]
> Weekly prod....
> 
> Are Xiaomi actually planning to release this Kernel? @ivan19871002 @liuguo09

I think it will be a long wait...

**Comment by steadramon** [comment]
https://en.miui.com/forum.php?mod=viewthread&tid=4025675

**Comment by PythonLimited** [comment]
well i asked there too a month ago or so
no answer but even the 6 months are nearly over...

**Comment by zvanderbilt** [comment]
The best thing we can do at this point is just think back to this issue when we want to purchase a new device to develop on. 

If oneplus can release their source code the day after a release there is no reason xiaomi shouldnt do the same, if nothing more than to compete.

**Comment by filjusz** [comment]
What a fu*kin shame! I will never buy xiaomi device ever again

**Comment by PythonLimited** [comment]
I would but only after the kernel release...

**Comment by Mirr0ch1** [comment]
nearly the end of 2018, still no sign of code-releasing.

**Comment by Deses** [comment]
Still waiting for kernel sources to buy this tablet. I'll NOT use MIUI, not even once.

**Comment by moham96** [comment]
I'm waiting the sources to buy the tablet as well

**Comment by PythonLimited** [comment]
Maybe a Christmas present for us XD?

**Comment by filjusz** [comment]
I dont think they will relase the sources...

**Comment by bendep** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/clover-o-oss
i think thats it what we all have been waiting for! :)

**Comment by PythonLimited** [comment]
OMG thanks for releasing.

**Comment by Mirr0ch1** [comment]
yeah, been so long

**Comment by arter97** [comment]
I was literally hours away from selling my Mi Pad 4.

Thanks but no thanks. You are still a disgrace for the community and I won't purchase another Xiaomi products just because of this horrible experience.

Fuck you.
