### ISSUE TITLE
kernel source Ulysse error camera 

### ISSUE THREAD

**Issue by Aarqw12** [MiCode/Xiaomi_Kernel_OpenSource#926]
Hello  oreo for redmi note 5a/prime planned? And will be oreo kernel sources available please ? Is necessary ... We already have oreo custom rom, but there is not camera and flashlight working. Could you pleases release oreo kernel sources for redmi note 5a/prime, or at least help fixing camera and flashlight?

thanks for your response

**Comment by muznyo** [comment]
Yes please

**Comment by muznyo** [comment]
We are waiting so long xiaomi

**Comment by muznyo** [comment]
Xiaomi please release oreo kernel sources so we can fix camera!!!!

**Comment by Haise1991** [comment]
Release Oreo kernel sources, please. 🖤

**Comment by nayefhaidir** [comment]
Yes Release THAT!!!

**Comment by Hryniuk1** [comment]
better to skip oreo and release pie

**Comment by stydent21rus** [comment]
pliz oreo fix cam !!!!

**Comment by reza740** [comment]
Please give us freedom for thats reason Xioami,thanks...

**Comment by adislice** [comment]
Please xiaomi....

**Comment by Aarqw12** [comment]
thanks to close without response ...

**Comment by luk1337** [comment]
@Aarqw12 you're welcome!

**Comment by reza740** [comment]
Why this clossed?I dont get it...

**Comment by muznyo** [comment]
@reza740 same.... They don't give a fck about us

**Comment by DarkLordLPCZ** [comment]
K
