### ISSUE TITLE
Please provide Mi8 source

### ISSUE THREAD

**Issue by 1nfrag** [MiCode/Xiaomi_Kernel_OpenSource#927]
I cant/wont buy this phone till the source code for kernel is released. If you could provide an ETA for xiaomi mi 8 kernel source that would be greatly appreciated!

Thanks!

**Comment by 1nfrag** [comment]
pretty please?

**Comment by 1nfrag** [comment]
Not trying to be rude but I'd like some clarification to when/if Xiaomi will release the source for Mi8? Could you help out with this please @ivan19871002 ?
Sorry for tagging you but you seem to consistently reply with any knowledge so if you could help? Thanks!

**Comment by Appiq-Solutions** [comment]
Here too waiting for kernel Release for Dipper. I cant build Havoc OS, Aosp Pie Roms and so on for Dipper.

Please release the sources

**Comment by bassbounce** [comment]
Waiting for it too, can u give more information about the release date for the source?

Mi 8SE source is already released, why the delay for the Mi 8?

**Comment by kalon33** [comment]
Duplicate of https://github.com/MiCode/Xiaomi_Kernel_OpenSource/issues/922.
In this original issue, it has been declared "It is expected to be open source in August, and there have been a lot of things lately. The process has not finished"

**Comment by viabary** [comment]
Anxiously waiting for a release, to begin dev of custom ROMs. Thank you Xiaomi in advance!

**Comment by 1nfrag** [comment]
@kalon33 Thanks for translating that for me. Lets call this the English version of that issue then as I couldnt even tell that was to do with Mi8 from the title :(

Its almost September now so hopefully they hurry up and release it soon!

**Comment by ghost** [comment]
@1nfrag I am a Chinese developer, I'm axiously waiting for the source code as well. I'm pretty sure that xiaomi will eventually release the code. According to the developer's words, the code should have been released in August.But there is still some work to do.so they didnt release it.I think it's mainly because they're working hard to get Android P working on dipper. This is undoubtedly a groundswell in Chinese forum:)

**Comment by carolef1984** [comment]
1nfrag, you did some great work for the x2. I have now got mi8 and am eagerly awaiting the release of the code. It's actually a really great phone, just a shame they can't release the source code sooner than this.

**Comment by mamilux** [comment]
Already there!!

**Comment by NhatHuyNguyen** [comment]
Problem solved :D

**Comment by 1nfrag** [comment]
Sweet. thanks Xiaomi for releasing the sources as requested!
