### ISSUE TITLE
Release oreo sources for ugglite/ugg!

### ISSUE THREAD

**Issue by muznyo** [MiCode/Xiaomi_Kernel_OpenSource#929]
Hello oreo for redmi note 5a/prime planned? And will be oreo kernel sources available please ? Is necessary ... We already have oreo custom rom, but there is not camera and flashlight working. Could you pleases release oreo kernel sources for redmi note 5a/prime, or at least help fixing camera and flashlight?

thanks for your response

**Comment by Aarqw12** [comment]
It's a very good question... Yes please do you can update kernel source and miui to oreo? Or not explain the reason please...Every users demand to update in oreo ... Do you have see reccurent message in your forum miui? I wait your response... Please response and no close this issue...

**Comment by azhe403** [comment]
up up
