### ISSUE TITLE
Xiaomi, please share the source code of GPL components used by you. Thank you!

### ISSUE THREAD

**Issue by viabary** [MiCode/Xiaomi_Kernel_OpenSource#934]
This is key for the success of this device and the wider community that uses and invests in the amazing tech you continue to put out.

**Comment by bademux** [comment]
Lets rephrase @viabary.
Xiaomi, please share the source code of GPL components used by you.

**Comment by viabary** [comment]
@bademux title edited ! Thanks

**Comment by viabary** [comment]
@bademux It out! We won! Let the games begin ! https://www.xda-developers.com/xiaomi-poco-f1-xiaomi-mi-8-explorer-edition-kernel-source-code-available/

**Comment by bademux** [comment]
Xiaomi, thank you
