### ISSUE TITLE
Missing Files in A2 Source

### ISSUE THREAD

**Issue by ghost** [MiCode/Xiaomi_Kernel_OpenSource#937]
Tried to Compile A2 source but there's missing files that uses sign-file.c

openssl/opensslv.h
openssl/bio.h
openssl/evp.h
openssl/pem.h
openssl/err.h
openssl/engine.h

Please Fix them

**Comment by luk1337** [comment]
fix your pc lmao

**Comment by ghost** [comment]
fixed lol

sudo apt-get install libssl-dev

**Comment by brlin-tw** [comment]
Maybe close the issue?
