### ISSUE TITLE
A2: not booting

### ISSUE THREAD

**Issue by infus38** [MiCode/Xiaomi_Kernel_OpenSource#941]
Hi, I compiled with 4.9 google toolchain your kernel ( branch jasmine obviously ), defconfig: jasmine-perf_defconfig
But it's not possible to boot it, just goes into bootloop ( and no adb ) 
any help would be appreciated, thanks

**Comment by uvera** [comment]
Boot img needs some changes for signaturing, etc, join @mia2official on telegram for more info

**Comment by Gah0** [comment]
hi, try another_defconfig

**Comment by abbyck** [comment]
@zah0 that isn't really the problem. We've tried many, with the preferred defconfig and pulled the one pulled from stock. In our opinion if it is with defconfig please provide that or else tell us what is it missing which causes bootloop.

**Comment by infus38** [comment]
Booted
