### ISSUE TITLE
Redmi 5 Plus vince-o-oos

### ISSUE THREAD

**Issue by ai94iq** [MiCode/Xiaomi_Kernel_OpenSource#943]
Hi Vince/Redmi 5 Plus was updated to O on stable branch aka Miui 9.6

so please update kernel source accordingly

**Comment by 0312birdzhang** [comment]
+1

**Comment by ramabondanp** [comment]
yes, we need oreo kernel source

**Comment by 4PERTURE** [comment]
Yos gib da sauce xiaomeme

**Comment by 1chinke** [comment]
Without kernel source device won't be supported well by community. Please publish the kernel source code.

**Comment by Blacksuan19** [comment]
WE NEED SAUCE BITCHES!!!

**Comment by EnesSastim** [comment]
up xd

**Comment by motoralbi** [comment]
UP

**Comment by 4PERTURE** [comment]
My email has been successfully spammed

**Comment by EriecTanijaya** [comment]
UP UP UP

**Comment by dipanjandas1234** [comment]
Yes we need oreo kernel source

**Comment by EriecTanijaya** [comment]
what you waiting for m8?

**Comment by ai94iq** [comment]
Vince O kernel source :\

**Comment by 1chinke** [comment]
C'mon

**Comment by doctord98** [comment]
what r u waiting for, give us vince sources already, development  stuck, don't wait nomore

**Comment by EriecTanijaya** [comment]
gPL sOfTwArE LiCeNsE ?

**Comment by 4PERTURE** [comment]
We're waiting

**Comment by EriecTanijaya** [comment]
gib sauce, git luv

**Comment by EriecTanijaya** [comment]
BUMP!

**Comment by EriecTanijaya** [comment]
now we got miui 10 stable, so please release source code asap. thanks

**Comment by laststandrighthere** [comment]
waiting for it

**Comment by doctord98** [comment]
So how much time you guys gonna take? Release sources..

**Comment by ramabondanp** [comment]
Its time for releasing source code.

**Comment by EriecTan** [comment]
HeHao, release please

**Comment by EriecTanijaya** [comment]
still waiting..

**Comment by doctord98** [comment]
Thats sad, why this delay?, don't ignore issue pls

**Comment by itslyney** [comment]
🕒 JUST DO IT . 🕒

**Comment by EriecTanijaya** [comment]
*really* **dude**?

**Comment by Bx16** [comment]
please update sources

**Comment by Z5X67280** [comment]
Some intersting thing, MIUI Global version (based Android O) is use "daisy" kernel src.😂
so...... **We should be Wait to MIUI China version update to Android O.Although we have to accept this reality.** 😂

**Comment by 0312birdzhang** [comment]
It's time to release **vince-o-oos** now, as XiaoMi released the stable MIUI China O version .

**Comment by EriecTanijaya** [comment]
> It's time to release **vince-o-oos** now, as XiaoMi released the stable MIUI China O version .

really? i think its not released yet

**Comment by ramabondanp** [comment]
Yeah it still closed beta for Miui China oreo

**Comment by ramabondanp** [comment]
Today xiaomi released public beta for miui china oreo, hope they release **vince-o-oss** soon

**Comment by EriecTanijaya** [comment]
omfg im so hyped

**Comment by laststandrighthere** [comment]
waiting for

**Comment by ramabondanp** [comment]
maybe we must waiting for tiffany o oss, vince kernel unified in there

**Comment by ghost** [comment]
+++1

**Comment by EriecTanijaya** [comment]
I hope its gonna be christmas gift

**Comment by ramabondanp** [comment]
its mid desember and still no **vince-o-oss** 
@liuguo09

**Comment by EriecTanijaya** [comment]
Please dont ignore

**Comment by Z5X67280** [comment]
open src is long long way...

**Comment by scafroglia93** [comment]
We hate communism but at the same time we adore the Chinese business model because prices are low

**Comment by EriecTanijaya** [comment]
give source please

**Comment by 0312birdzhang** [comment]
> It's time to release **vince-o-oos** now, as XiaoMi released the stable MIUI China O version .

This time it is true. 😂 
![image](https://user-images.githubusercontent.com/1762041/50325107-d8bd8400-051d-11e9-900a-adaf8af1bc31.png)

**Comment by EriecTanijaya** [comment]
Yes, please

**Comment by ramabondanp** [comment]
Xiaomi already release miui china oreo stable to common user.
So its time to release kernel source.

**Comment by EriecTanijaya** [comment]
Tag the dev please

**Comment by Z5X67280** [comment]
What are you doing, xiaomi?
Where is GPLv2 license?
Are you eating GPLv2?
I suspect that Xiaomi's computers is still running Ubuntu with Pentium 2 (laugh)
Even Intel 386... (laugh)


_Send from [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/) for Redmi 5 Plus on Android P_

**Comment by ghost** [comment]
> What are you doing, xiaomi?
> Where is GPLv2 license?
> Are you eating GPLv2?
> I suspect that Xiaomi's computers is still running Ubuntu with Pentium 2 (laugh)
> Even Intel 386... (laugh)
> 
> _Send from [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/) for Redmi 5 Plus on Android P_

Xiaomi is working on Android Q

**Comment by EriecTanijaya** [comment]
no love for redmi 5 plus ? :(

**Comment by scafroglia93** [comment]
You complain and continue to support this shit producer. you are very strange

**Comment by Z5X67280** [comment]
Well done, guys. [sakura-o-oss](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/sakura-o-oss).

**Comment by scafroglia93** [comment]
LOL

It's based on 9 April 2018 Qualcomm patchset

Truly supa optmized fast AI battery supa pefomance

**Comment by EriecTanijaya** [comment]
close this please

**Comment by ai94iq** [comment]
Closed sources were pushed

**Comment by NCLnclNCL** [comment]
> Well done, guys. [sakura-o-oss](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/sakura-o-oss).

Ok
