### ISSUE TITLE
Xiaomi Redmi S2 (ysl) touchscreen driver !!

### ISSUE THREAD

**Issue by amir-s86** [MiCode/Xiaomi_Kernel_OpenSource#958]
touchscreen driver is missing in Redmi S2 (ysl) kernel source .. could you please add it ? thanks in advance .. 
fatal error: include/firmware/LQ_ysl_FT5446_Ofilm_EBBG_V0d_D01_20180403_app.i: No such file or directory

**Comment by ghost** [comment]
#985 fixes it
