### ISSUE TITLE
Whyred huaxing panel

### ISSUE THREAD

**Issue by akhilnarang** [MiCode/Xiaomi_Kernel_OpenSource#962]
The current sources don't work on devices with huaxing nt36672 panel, we just get a black screen
Kindly update the source for it

**Comment by faiyazsheth** [comment]
@hehao

**Comment by Haseo97** [comment]
@hehao

**Comment by shamith16** [comment]
Nahi degi

**Comment by DevanshBajaj** [comment]
^^^^

**Comment by azrulhaifan** [comment]
Up, please update the source

**Comment by SentinelX** [comment]
Update source!!!

**Comment by Meraj018** [comment]
@hehao

**Comment by Meraj018** [comment]
Pls xiaomi update whyred source..

**Comment by IntelliJAbhishek** [comment]
Xiaomi Please update the sources. Support us for custom rom development

**Comment by GuaiYiHu** [comment]
Having informed the developer.

**Comment by scafroglia93** [comment]
CIAO MAMMA

**Comment by faiyazsheth** [comment]
@hehao :-|

**Comment by NiNoXowl** [comment]
up

**Comment by idileepd** [comment]
up

**Comment by Tao-kun** [comment]
Is [this](https://github.com/MiCode/Xiaomi_Kernel_OpenSource/blob/whyred-o-oss/arch/arm/boot/dts/qcom/dsi-panel-huaxing-nt36672-1080p-video.dtsi) the driver of huaxing panel?

**Comment by NiNoXowl** [comment]
up up

**Comment by Haseo97** [comment]
@hehao bdsk hear us here ;-;

**Comment by ghost** [comment]
Is this issue fixed in recent xiaomi firmwares?

**Comment by Haseo97** [comment]
This commit fixed the panel for huaxing: https://github.com/psndna88/AGNi_pureMIUI/commit/ce73a14bf988280fbd535968ef4819b74fbdf296

**Comment by lezysul** [comment]
Nahi degi (2)
