### ISSUE TITLE
Kernel pie source for polaris

### ISSUE THREAD

**Issue by palaych** [MiCode/Xiaomi_Kernel_OpenSource#974]
On http://www.miui.com/download-342.html have published stable android 9.0.
When to approximately expect the source? After released stable on mi8/poco or earlier?
@ivan19871002  ?

**Comment by DaWy** [comment]
Yes please, releas the Kernel source for Pie for the Mi Mix 2S (Polaris)

**Comment by ivan19871002** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/perseus-p-oss
