### ISSUE TITLE
Push kernel source of Redmi 6 and 6A

### ISSUE THREAD

**Issue by SamarV-121** [MiCode/Xiaomi_Kernel_OpenSource#975]

**Comment by XC16** [comment]
agree,please release redmi 6's kernel source

**Comment by ramabondanp** [comment]
Its always hard to release mtk source

**Comment by Dreyk007** [comment]
So, we still need Redmi 6A sources...

**Comment by 0xXA** [comment]
> Its always hard to release mtk source

No, as usual you can release your modified kernel but not mtk's ALPS sources. Like sources for Hals, lk, bootloader.
If they have released sources for one mtk device in any of the branches of this repo than you can appeal them to release for this device too

**Comment by ghost** [comment]
> Its always hard to release mtk source

No, as usual oem can release their modified kernel but not mtk's ALPS sources. Like sources for Hals, lk, bootloader,etc
If they want to release it too than have to pay extra for this.
If they have released sources for one mtk device in any of the branches of this repo than you can appeal them to release for this device too

**Comment by Dreyk007** [comment]
Closed due to released Redmi 6/6A sources or what?

**Comment by XC16** [comment]
ya it released

> Closed due to released Redmi 6/6A sources or what?
