### ISSUE TITLE
Redmi Note 6 pro (tulip) kernel sources

### ISSUE THREAD

**Issue by DrRamm** [MiCode/Xiaomi_Kernel_OpenSource#981]
Even mi 8 lite is now available. And we know that you respect GPLv2

**Comment by qttc** [comment]
please publish sources!

**Comment by sayaadali** [comment]
Yah please do it we really need it

**Comment by sodacost** [comment]
+++ please

**Comment by Rekembus** [comment]
+++

**Comment by Niko8080** [comment]
Please publish the sources of the kernel.++++

**Comment by ctopoj** [comment]
+++

**Comment by SenyaHoi** [comment]
Please publish the sources of the kernel.++++

**Comment by ieprst** [comment]
Please publish  tulip kernel sources

**Comment by dadalife1** [comment]
Please publish the sources of the kernel.+++

**Comment by hronus** [comment]
please publish sources! I like stock android!

**Comment by shivamdev-lgtm** [comment]
Please publish kernel sources respecting GPLv2

**Comment by szltom** [comment]
Please publish kernel source

**Comment by cheicho** [comment]
Please publish the sources of the kernel.

**Comment by akwizard** [comment]
Please publish tulip kernel sources.++++

**Comment by prateekpunetha** [comment]
Bitches Release It :laughing:

**Comment by taranhora** [comment]
We need kernel source to start the development of redmi note 6 pro (tulip)  so provide ASAP.

**Comment by Daniel8821** [comment]
Please publish the sources of the kernel

**Comment by ProfessorMi** [comment]
Please publish the tulip kernel sources

**Comment by ux1** [comment]
Please publish kernel source.

**Comment by msrshahkar** [comment]
Please publish the kernel sources. We love Xiaomi Devices but without kernel sources it's no fun.

**Comment by ghost** [comment]
@ivan19871002 @hehao any ETA ?

**Comment by AziKoo** [comment]
Please publish kernel sources++++

**Comment by joiannariello** [comment]
please release kernel sources

**Comment by mtpockets1** [comment]
Please publish the kernel source ASAP

**Comment by ramabondanp** [comment]
Please release tulip kernel source, and vince oreo kernel source too

**Comment by prateekpunetha** [comment]
@rama982😆😆😆 hahahah yesssss

**Comment by athulharold** [comment]
Please publish the kernel Sources

**Comment by davideriboli** [comment]
Please publish tulip kernel sources.

In this century.

**Comment by ghost** [comment]
Man push the tulip source ffs. Look at other brands. They release the source within days of release... But you guys wanna delay it. Ffs release them...

**Comment by illnyang** [comment]
no, it's not happening.

**Comment by tankist8879** [comment]
Please publish tulip kernel sources.

**Comment by mountytest** [comment]
Please publish the kernel source

**Comment by Dark-Cod3r** [comment]
Please Publish Source Code..  Why you always Do that Xiaomi.. :/

**Comment by ghost** [comment]
Please release kernel source.

**Comment by thesprintster** [comment]
Please release kernel source.

**Comment by ghost** [comment]
Its been **more than 3 months** since phone was announced. Mi promised to publish source within 3 months.

**Please give us kernel source.**

**Comment by thesprintster** [comment]
@Luk1337 are you buying this phone? ;)

Saw your down-vote on @Saksham033 comment.

**Comment by ghost** [comment]
For the love of god give us tulip kernel source! :(

**Comment by ghost** [comment]
Release sources. Respect GPLv2 licence

**Comment by sayaadali** [comment]
Yes please release  it

**Comment by sayaadali** [comment]
According to Xiaomi they said that they will release kernel source after 3 month of device lunche

**Comment by daniil20** [comment]
Please publish the sources of the kernel:sob:

**Comment by ihsanepixel** [comment]
Please publish the sources of the kernel.

**Comment by ihsanepixel** [comment]
> According to Xiaomi they said that they will release kernel source after 3 month of device lunche

after the launch in India or the world?

**Comment by cinghkreations** [comment]
Its been more than 3 months since phone was announced. Mi promised to publish source within 3 months. So i request them to release the sources to continue the development

**Comment by Agneton** [comment]
Please publish the sources of the kernel

**Comment by esashwin** [comment]
please publish sources......

**Comment by rashedsahaji** [comment]
Please sir it's our request

**Comment by ramabondanp** [comment]
Even jasmine-p-oss have tulip driver on it lol.

Please xiaomi release full kernel source for tulip.

**Comment by ryan-andri** [comment]
that's xiaomi @rama982

**Comment by DamnUlittle** [comment]
+1!

**Comment by huluyige** [comment]
+1

**Comment by vitorjrc** [comment]
Would be lovely if you do publish the sources.

**Comment by zignd** [comment]
Release the kernel source code please, I have never asked you anything.

**Comment by ramabondanp** [comment]
its released now

**Comment by satana666luciferka** [comment]
Кто может собрать ядро NETHUNTER please

**Comment by ghost** [comment]
PLEASE RELEASE IT!!! GUYS ITS FOR IT! NOW RN7 WILL BE OUT THEN WHY NOT JUST A SOURCE !!

**Comment by ramabondanp** [comment]
> PLEASE RELEASE IT!!! GUYS ITS FOR IT! NOW RN7 WILL BE OUT THEN WHY NOT JUST A SOURCE !!

Really m8? its already released inside whyred-o-oss (full changes, latest patch) and jasmine-p-oss (partial changes)
