### ISSUE TITLE
What i doing wrong when trying compiling?

### ISSUE THREAD

**Issue by artyom5613** [MiCode/Xiaomi_Kernel_OpenSource#986]
I trying compiling daisy-o-oss , scorpio-m-oss , but i face with errors(compilation successively started and go. But after 5-8 min i take error.  ).
Typical error:
```
 In file included from drivers/media/platform/msm/camera_v2/isp/msm_isp_util.c:24:0:
include/trace/events/msm_cam.h:19:21: fatal error: msm_isp.h: No such file or directory
 #include "msm_isp.h"
                     ^
```

What i do wrong? Download kernel source code->Download toolchain -> cd to the toolchain , type  export ARCH=arm64 && export SUBARCH=arm64 ->  export CROSS_COMPILE=$(pwd)/bin/aarch64-linux-android- -> cd to the source code -> make clean -> make mrproper -> make -j4.

Can you help me with instruction if I do something wrong?

OS: Ubuntu 18.04.1LTS. Maybe i need to try compile on another OS?

**Comment by ramabondanp** [comment]
Specify output dir with make O=out.

**Comment by Revanth** [comment]
`export ARCH=arm64
export CROSS_COMPILE=~/Toolchain/bin/aarch64-linux-android-
mkdir output
make -C $(pwd) O=output rosy_defconfig
make -j32 -C $(pwd) O=output`

**Comment by ghost** [comment]
@artyom5613 U need to make a folder called as out. Posting the build Script in HasteBin have a look

https://hastebin.com/idunehujat.js

**Comment by ivan19871002** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/issues/987

**Comment by ghost** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/wiki/How-to-compile-kernel-standalone

Maybe you'll get some help from wiki page

Moreover, you can paste link to a log file here if it really have anything to do with kernel

**Comment by artyom5613** [comment]
thank you! It's help
