### ISSUE TITLE
Wifi issue mi a 2 lite stock kernel

### ISSUE THREAD

**Issue by artyom5613** [MiCode/Xiaomi_Kernel_OpenSource#988]
I compile stock kernel without any changes. And boot in this. Wifi don't work... Thay can't on
Please fix
(If i boot into boot.img that located in ROM that wifi work good.)

**Comment by ghost** [comment]
Attach a dmesg here,
You trying to boot stock miui kernel on any custom os ?

Guess: after building you need to place wifi module to its right place in system

```
find . -type f -name 'wlan.ko' -exec cp {} . \;
```

use AnyKernel2 to flash your compiled kernel and kernel modules along with it.

https://github.com/osm0sis/AnyKernel2

**Comment by Z5X67280** [comment]
You should find "wlan.ko" module, and you should use AnyKernel2 to flash your kernel.:kissing:

**Comment by Rprop** [comment]
You have to compile wifi driver yourself and sign it.
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/wiki/FAQ

**Comment by artyom5613** [comment]
Can somebody help with compiling wifi driver? @artyom5613 (Telegram)
Or where i can take done compiled driver in kernel source code snapdragon 625 kernel?

**Comment by ramabondanp** [comment]
@artyom5613 i can.
Contact me @rama982 on telegram
