### ISSUE TITLE
Pocophone Touchscreen Update FW

### ISSUE THREAD

**Issue by scafroglia93** [MiCode/Xiaomi_Kernel_OpenSource#990]
8.12.13

Fixed: Touchscreen responses slowly（POCO F1）

Where's the updated source ? Is this the real community support ?

![hqdefault](https://user-images.githubusercontent.com/8227101/50034133-b72f3a80-fffb-11e8-98d1-4af520e2fac6.jpg)

**Comment by 0xXA** [comment]
Hey, Pick changes from Los Gerrit

**Comment by scafroglia93** [comment]
Hey, where's the support from OEM ?

**Comment by 0xXA** [comment]
They're repeatedly experimenting with it.

**Comment by scafroglia93** [comment]
And I repeat that it should be the manufacturer to release updates to keep the kernel source updated rather than release a useless snapshot;

I do not pay lineageos but Xiaomi and I expect them to release updates
