### ISSUE TITLE
MITV 3 60'' kernel source 

### ISSUE THREAD

**Issue by saalmaan** [MiCode/Xiaomi_Kernel_OpenSource#992]
Hello, 

Can you please release MITV 3 60'' kernel source code. Its been years since new update has arrived, very frustrating that we are stuck with Android 5.1. With the release of this Kernel source code, developer can at least bring latest Android TV to MITV 3 60'' and give this TV new lease of life. 
If this is not the right forum for asking kernel source for MITV, then please direct me to correct forum.
Thanks

**Comment by saalmaan** [comment]
@ivan19871002 Any update on this? You mentioned on Weibo that MITV source kernel is coming soon, do you know any approximate dates? https://m.weibo.cn/detail/4341835327348409

**Comment by ivan19871002** [comment]
https://github.com/MiCode/MiBox_Kernel_OpenSource
this repo

if you have some question, pls create issue

**Comment by saalmaan** [comment]
@ivan19871002 Thank you for replying. Repo you linked is for MiBox3 (Global), my request was for MiTV 3 60''. Can you please help/update us with source kernel for MiTV 3 60''? 

Or you are suggesting that MIBOX3(global) kernel can be used for MiTV 3 60''?
