### ISSUE TITLE
whyred touchscreen firmware update for tulip

### ISSUE THREAD

**Issue by ghost** [MiCode/Xiaomi_Kernel_OpenSource#993]
whyred stock 10.0.4.0 kernel boots in tulip but touch is not working.
Please update whyred kernel with tulip changes.

**Comment by ramabondanp** [comment]
Yo wtf

**Comment by 0xXA** [comment]
> whyred stock 10.0.4.0 kernel boots in tulip but touch is not working.
> Please update whyred kernel with tulip changes.

FYI,
For every touchscreen delays and touchscreen data differs.
I can help you but that'll be pointless

**Comment by Haseo97** [comment]
pLeAsE uPdAtE WhYrEd kErNeL wItH tULiP ChAnGeS

Xiaomi: Excuse me waduhek

**Comment by 0xXA** [comment]
> whyred stock 10.0.4.0 kernel boots in tulip but touch is not working.
> Please update whyred kernel with tulip changes.

Is both device have same touchscreen model?

**Comment by ramabondanp** [comment]
@yuvrajx actually no

**Comment by 0xXA** [comment]
> whyred stock 10.0.4.0 kernel boots in tulip but touch is not working.
> Please update whyred kernel with tulip changes.

If I have time I'll try to adapt touchscreen driver for your device you can ping me on [telegram](https://t.me/yuvrajx), the problem is that there's many drivers that one device xiaomi can ship.
And unfortunately I can't do all of them due to lack of time I'll try if I have sometime to figure this out and as you have mentioned above that it boots without touchscreen than it can boot after adapting the needed touchscreen drivers.

**Comment by ramabondanp** [comment]
@yuvrajx actually, tulip novatek ts driver is 'accidentaly' pushed on jasmine-p-oss already, with some other stuff too.
Even i already rebased it and make boot of it on my phone.
What left is tulip focaltech ts driver. On jasmine-p-oss missing firmware .i file.

**Comment by 0xXA** [comment]
> @yuvrajx actually, tulip novatek ts driver is 'accidentaly' pushed on jasmine-p-oss already, with some other stuff too.
> Even i already rebased it and make boot of it on my phone.
> What left is tulip focaltech ts driver. On jasmine-p-oss missing firmware .i file.

I can help you
Let's see you on telegram I can fix it :)

**Comment by yuvrajx** [comment]
> whyred stock 10.0.4.0 kernel boots in tulip but touch is not working.
> Please update whyred kernel with tulip changes.

Can you try flash this kernel?
Make sure you flash it on custom roms
https://drive.google.com/a/my.cuesta.edu/uc?id=1h_i0lAryMNmCIoNDgSQmTspkpIDLm1fI&export=download

**Comment by 0xXA** [comment]
> whyred stock 10.0.4.0 kernel boots in tulip but touch is not working.
> Please update whyred kernel with tulip changes.

Can you try flash this [kernel](https://drive.google.com/a/my.cuesta.edu/uc?id=1voi3SSTBVXfoCGJRB974nU8O67Bnsbg8&export=download)
Make sure you flash it on custom roms.

**Comment by ghost** [comment]
> pLeAsE uPdAtE WhYrEd kErNeL wItH tULiP ChAnGeS
> 
> Xiaomi: Excuse me waduhek

@Haseo97 Take the L!
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/commit/efbbb9cce47475c49f28d227b2a52eca6f0d02a7

**Comment by Haseo97** [comment]
Yes i’m taking the L now
