### ISSUE TITLE
make mido_defconfig

### ISSUE THREAD

**Issue by HelbAndHelb** [MiCode/Xiaomi_Kernel_OpenSource#994]
A am paste command: make mido_defconfig
fs/Kconfig:92: can't open file "fs/exfat/Kconfig"
make[1]: *** [scripts/kconfig/Makefile:105: mido_defconfig] Error1
make: *** [Makefile:545: mido_defconfig] Error 2

**Comment by krasCGQ** [comment]
Comment that line in Kconfig. Xiaomi excluded exFAT driver most likely due to patent issues.

**Comment by HelbAndHelb** [comment]
Very thanks!!!
