### ISSUE TITLE
Please release Android P kernel source for Mi 8 SE (sirius)

### ISSUE THREAD

**Issue by longnt2007** [MiCode/Xiaomi_Kernel_OpenSource#996]
As Mi8 SE china beta rom have been upgraded to Android 9.0 nearly two months, please release Android P kernel source for Mi 8 SE (sirirus) too. Also please check the DTB building config as default config doesn't work correctly, enable CONFIG_BUILD_ARM64_DT_OVERLAY will show error when building source, disable CONFIG_BUILD_ARM64_DT_OVERLAY (as default config) is ok but dtbs cooked is not compatible with stock dtbo.img partition.

Thank you.

**Comment by Titokhan** [comment]
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/grus-p-oss

**Comment by rama982** [comment]
Mi8 SE Pie kernel source already released
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/commit/b18c42adc8a20c2775cc55f079b2bea047674a4d

**Comment by dkmgfk** [comment]
longnt2007

Hello! Do you have any plan for porting AOSP based ROM to this device?

Regards
