### ISSUE TITLE
Vince-o-oss

### ISSUE THREAD

**Issue by EriecTanijaya** [MiCode/Xiaomi_Kernel_OpenSource#997]
As China Stable for Vince released, will you release the kernel source?

**Comment by EriecTanijaya** [comment]
请发布Redmi 5 plus内核源代码 @ivan19871002 @liuguo09

**Comment by Z5X67280** [comment]
when they want to release, they will open src lol

_Send by  [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/) _
